"use strict";
(()=>{const $=id=>document.getElementById(id);let proposal=null,exampleIndex=0;const examples=["Tee 120 x 60 mm kiinnikelevy, paksuus 5 mm, neljä 8 mm reikää 10 mm reunoista, pyöristetyt kulmat 5 mm PETG:stä.","Tee 100 x 50 mm kiinnikelevy, paksuus 4 mm, keskelle 10 mm reikä ja pyöristetyt kulmat 6 mm.","Tee 33 mm mutterille 90 mm pitkä terävä piikkisuoja ASA:sta.","Tee holkki, sisähalkaisija 20 mm, seinämä 3 mm ja pituus 35 mm PETG:stä."];
const num=s=>Number(String(s).replace(",",".")),find=(t,re)=>{const m=t.match(re);return m?num(m[1]):null},mat=t=>/\basa\b/i.test(t)?"ASA":/\bpetg\b/i.test(t)?"PETG":/\bpla\b/i.test(t)?"PLA":null;
function detectType(t){if(/päätytulppa|paatytulppa|suorakaideputk|putken tulppa/.test(t))return"plug";if(/holkki|soviterengas|soviteholkki/.test(t))return"sleeve";if(/levy|kiinnikeaihio|kiinnikelevy/.test(t))return"plate";if(/piikk|mutteri|pyöränmutter|pyoranmutter/.test(t))return"spike";return null}
function parse(raw){const t=raw.toLowerCase().replace(/×/g,"x").replace(/\s+/g," ").trim();if(!t)throw Error("Kirjoita ensin mitä haluat suunnitella.");const type=detectType(t),material=mat(t)||(/ulko|uv|rekka|kuorma-auto/.test(t)?"ASA":$("material").value),values={},found=[],missing=[],warnings=[];if(!type){missing.push("osatyyppi");return{type:null,values,material,found,missing,warnings,raw}}
if(type==="spike"){const n=find(t,/(\d+(?:[.,]\d+)?)\s*mm\s*(?:mutter|pyöränmutter|pyoranmutter)/)||find(t,/(?:mutter|avainkoko)[^\d]{0,12}(\d+(?:[.,]\d+)?)/),h=find(t,/(?:pitkä|pitka|korkeus|korkea)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),w=find(t,/(?:seinämä|seinama)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(n!==null)values.nutAf=n;else missing.push("mutterin avainkoko");values.totalHeight=h??75;if(w!==null)values.wall=w;if(/napakka|tiukka/.test(t)){values.lockAmount=.25;values.clearance=.20}if(/terävä|terava/.test(t))values.tipRadius=.35}
if(type==="plug"){const d=t.match(/(\d+(?:[.,]\d+)?)\s*x\s*(\d+(?:[.,]\d+)?)\s*mm/),tw=find(t,/(?:seinämä|seinama)[^\d]{0,12}(\d+(?:[.,]\d+)?)\s*mm/);if(d){values.tubeW=num(d[1]);values.tubeH=num(d[2])}else missing.push("putken ulkomitat");if(tw!==null)values.tubeWall=tw;else missing.push("putken seinämä");values.insertDepth=find(t,/(?:upotus|upotussyvyys)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/)??18;values.capThickness=3;values.plugClear=.25;values.capOverhang=1}
if(type==="sleeve"){const id=find(t,/(?:sisähalkaisija|sisahalkaisija|sisä ?ø|sisa ?ø|id)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),w=find(t,/(?:seinämä|seinama)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),h=find(t,/(?:pituus|pitkä|pitka)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(id!==null)values.sleeveID=id;else missing.push("holkin sisähalkaisija");if(w!==null)values.sleeveWall=w;else missing.push("holkin seinämä");if(h!==null)values.sleeveLength=h;else missing.push("holkin pituus")}
if(type==="plate"){const d=t.match(/(\d+(?:[.,]\d+)?)\s*x\s*(\d+(?:[.,]\d+)?)\s*mm/),th=find(t,/(?:paksuus|paksu)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(d){values.plateL=num(d[1]);values.plateW=num(d[2])}else missing.push("levyn pituus ja leveys");if(th!==null)values.plateT=th;else missing.push("levyn paksuus");const four=/neljä\s+(\d+(?:[.,]\d+)?)\s*mm\s*reik|4\s*[x×]?\s*(\d+(?:[.,]\d+)?)\s*mm\s*reik/.exec(t);if(four){values.plateHolePattern="four";values.plateHoleD=num(four[1]||four[2]);const edge=find(t,/(\d+(?:[.,]\d+)?)\s*mm\s*(?:reunoista|reunasta)/)||find(t,/(?:reunaetäisyys|reunaetaisyys)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(edge===null)missing.push("reikien keskipisteen etäisyys reunoista");else values.plateHoleEdge=edge;found.push(`4 × Ø${values.plateHoleD} mm`)}else{const hole=find(t,/(?:keskireikä|keskireika|keskelle|reikä|reika)[^\d]{0,16}(\d+(?:[.,]\d+)?)\s*mm/);values.plateHolePattern=hole!==null?"center":"none";values.plateHoleD=hole??0}const c=find(t,/(?:pyöristetyt kulmat|pyoristetyt kulmat|pyöristys|pyoristys|viistetyt kulmat|viiste)[^\d]{0,16}(\d+(?:[.,]\d+)?)\s*mm/);if(/pyöristet|pyoristet|pyöristys|pyoristys/.test(t)){values.plateCornerStyle="round";values.plateCornerSize=c??5}else if(/viistet|viiste/.test(t)){values.plateCornerStyle="chamfer";values.plateCornerSize=c??5}else{values.plateCornerStyle="square";values.plateCornerSize=0}}
return{type,values,material,found,missing,warnings,raw}}
function typeName(t){return{spike:"Piikkimutterinsuojus",plug:"Suorakaideputken päätytulppa",sleeve:"Holkki / soviterengas",plate:"Levy / kiinnikeaihio"}[t]||"Tuntematon"}
function show(r){$("aiProposal").hidden=false;const miss=r.missing.length>0;$("aiApproval").hidden=miss;const vals=Object.entries(r.values).map(([k,v])=>`<span>${k} <b>${typeof v==="number"?v.toFixed(2):v}</b></span>`).join("");$("aiProposal").innerHTML=`<div class="proposal-title">${typeName(r.type)}</div><div class="proposal-grid">${vals}</div>${r.found.length?`<div class="proposal-note">Tulkittu: ${r.found.join(" • ")}</div>`:""}${miss?`<div class="proposal-warn"><b>Tarvitsen vielä:</b><br>• ${r.missing.join("<br>• ")}</div>`:""}`;$("aiStatus").textContent=miss?"Lisää puuttuvat mitat pyyntöön ja analysoi uudelleen.":"Ehdotus valmis. Tarkista mitat ja hyväksy."}
function apply(){if(!proposal||proposal.missing.length)return;$("material").value=proposal.material;window.AI3D.setPart(proposal.type,proposal.values);$("aiStatus").textContent=`✓ ${typeName(proposal.type)} luotu.`;$("aiProposal").hidden=true;$("aiApproval").hidden=true;document.querySelector(".preview-panel")?.scrollIntoView({behavior:"smooth",block:"start"})}
$("btnAiAnalyze").onclick=()=>{try{proposal=parse($("aiPrompt").value);show(proposal)}catch(e){$("aiStatus").textContent="Virhe: "+e.message}};$("btnAiExample").onclick=()=>{$("aiPrompt").value=examples[exampleIndex++%examples.length]};$("btnAiAccept").onclick=apply;$("btnAiReject").onclick=()=>{proposal=null;$("aiProposal").hidden=true;$("aiApproval").hidden=true;$("aiStatus").textContent="Ehdotus hylätty."};})();