"use strict";
(()=>{const $=id=>document.getElementById(id);let proposal=null,exampleIndex=0;const examples=["Tee 33 mm mutterille 90 mm pitkä terävä piikkisuoja ASA:sta. Seinämä 3 mm ja napakka lukitus.","Tee 50 x 30 mm suorakaideputkeen päätytulppa. Putken seinämä 2,5 mm, upotus 18 mm ja ASA.","Tee holkki, sisähalkaisija 20 mm, seinämä 3 mm ja pituus 35 mm PETG:stä.","Tee 100 x 50 mm kiinnikelevy, paksuus 4 mm, keskelle 10 mm reikä ja pyöristetyt kulmat 6 mm PETG:stä.","Tee 80 x 40 mm levy, paksuus 5 mm, keskireikä 8 mm ja viistetyt kulmat 4 mm."];
const num=s=>Number(String(s).replace(",",".")),find=(t,re)=>{const m=t.match(re);return m?num(m[1]):null},mat=t=>/\basa\b/i.test(t)?"ASA":/\bpetg\b/i.test(t)?"PETG":/\bpla\b/i.test(t)?"PLA":null;
function detectType(t){if(/päätytulppa|paatytulppa|suorakaideputk|putken tulppa/.test(t))return"plug";if(/holkki|soviterengas|soviteholkki/.test(t))return"sleeve";if(/levy|kiinnikeaihio|kiinnikelevy/.test(t))return"plate";if(/piikk|mutteri|pyöränmutter|pyoranmutter/.test(t))return"spike";return null}
function parse(raw){const t=raw.toLowerCase().replace(/×/g,"x").replace(/\s+/g," ").trim();if(!t)throw Error("Kirjoita ensin mitä haluat suunnitella.");const type=detectType(t),material=mat(t)||(/ulko|uv|rekka|kuorma-auto/.test(t)?"ASA":$("material").value),values={},found=[],missing=[],warnings=[];if(!type){missing.push("osatyyppi (esim. piikkimutteri, päätytulppa, holkki tai levy)");return{type:null,values,material,found,missing,warnings,raw}}
if(type==="spike"){let n=find(t,/(\d+(?:[.,]\d+)?)\s*mm\s*(?:mutter|pyöränmutter|pyoranmutter)/)||find(t,/(?:mutter|avainkoko)[^\d]{0,12}(\d+(?:[.,]\d+)?)/);let h=find(t,/(?:pitkä|pitka|korkeus|korkea)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/)||find(t,/(\d+(?:[.,]\d+)?)\s*mm\s*(?:pitkä|pitka|korkea)/);let w=find(t,/(?:seinämä|seinama)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(n!==null){values.nutAf=n;found.push(`mutteri ${n} mm`)}else missing.push("mutterin avainkoko");if(h!==null){values.totalHeight=h;found.push(`korkeus ${h} mm`)}else values.totalHeight=75;if(w!==null)values.wall=w;if(/napakka|tiukka|pitävä|pitava/.test(t)){values.lockAmount=.25;values.clearance=.20}if(/terävä|terava/.test(t))values.tipRadius=.35;warnings.push("Tulosta aina ensin sovitustesti ennen liikennekäyttöä.")}
if(type==="plug"){const dims=t.match(/(\d+(?:[.,]\d+)?)\s*[x]\s*(\d+(?:[.,]\d+)?)\s*mm/);const tw=find(t,/(?:putken seinämä|putken seinama|seinämä|seinama)[^\d]{0,12}(\d+(?:[.,]\d+)?)\s*mm/),ins=find(t,/(?:upotus|upotussyvyys|sisään|sisaan)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),ct=find(t,/(?:päätylevyn paksuus|paatylevyn paksuus|kannen paksuus)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(dims){values.tubeW=num(dims[1]);values.tubeH=num(dims[2]);found.push(`putki ${values.tubeW} × ${values.tubeH} mm`)}else missing.push("putken ulkomitat, esim. 50 × 30 mm");if(tw!==null){values.tubeWall=tw;found.push(`putken seinämä ${tw} mm`)}else missing.push("putken seinämän paksuus");values.insertDepth=ins??18;values.capThickness=ct??3;values.plugClear=.25;values.capOverhang=1;warnings.push("Putken todellinen sisämitta kannattaa mitata työntömitalla ennen lopullista tulostusta.")}
if(type==="sleeve"){const id=find(t,/(?:sisähalkaisija|sisahalkaisija|sisä ?ø|sisa ?ø|id)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),w=find(t,/(?:seinämä|seinama)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/),h=find(t,/(?:pituus|pitkä|pitka)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(id!==null)values.sleeveID=id;else missing.push("holkin sisähalkaisija");if(w!==null)values.sleeveWall=w;else missing.push("holkin seinämä");if(h!==null)values.sleeveLength=h;else missing.push("holkin pituus")}
if(type==="plate"){const dims=t.match(/(\d+(?:[.,]\d+)?)\s*x\s*(\d+(?:[.,]\d+)?)\s*mm/),th=find(t,/(?:paksuus|paksu)[^\d]{0,10}(\d+(?:[.,]\d+)?)\s*mm/);if(dims){values.plateL=num(dims[1]);values.plateW=num(dims[2]);found.push(`levy ${values.plateL} × ${values.plateW} mm`)}else missing.push("levyn pituus ja leveys, esim. 100 × 50 mm");if(th!==null)values.plateT=th;else missing.push("levyn paksuus");
const hole=find(t,/(?:keskireikä|keskireika|keskelle|reikä|reika|pultinreikä|pultinreika)[^\d]{0,16}(\d+(?:[.,]\d+)?)\s*mm/);if(hole!==null){values.plateHoleD=hole;found.push(`keskireikä Ø ${hole} mm`)}else values.plateHoleD=0;
const corner=find(t,/(?:pyöristetyt kulmat|pyoristetyt kulmat|pyöristys|pyoristys|viistetyt kulmat|viiste)[^\d]{0,16}(\d+(?:[.,]\d+)?)\s*mm/);if(/pyöristet|pyoristet|pyöristys|pyoristys/.test(t)){values.plateCornerStyle="round";values.plateCornerSize=corner??5;found.push(`pyöristetyt kulmat ${values.plateCornerSize} mm`)}else if(/viistet|viiste/.test(t)){values.plateCornerStyle="chamfer";values.plateCornerSize=corner??5;found.push(`viistetyt kulmat ${values.plateCornerSize} mm`)}else{values.plateCornerStyle="square";values.plateCornerSize=0}
if(/kaksi reik|2 reik|reikiä|reikia/.test(t))warnings.push("v0.8 tekee vielä yhden keskireiän. Useiden reikien sijainnit lisätään seuraavassa CAD-vaiheessa.")}
return{type,values,material,found,missing,warnings,raw}}
function typeName(t){return{spike:"Piikkimutterinsuojus",plug:"Suorakaideputken päätytulppa",sleeve:"Holkki / soviterengas",plate:"Levy / kiinnikeaihio"}[t]||"Tuntematon"}
function show(r){$("aiProposal").hidden=false;const miss=r.missing.length>0;$("aiApproval").hidden=miss;const vals=Object.entries(r.values).map(([k,v])=>`<span>${k} <b>${typeof v==="number"?v.toFixed(2):v}</b></span>`).join("");$("aiProposal").innerHTML=`<div class="proposal-title">${typeName(r.type)}</div>${vals?`<div class="proposal-grid">${vals}</div>`:""}${r.found.length?`<div class="proposal-note">Tulkittu: ${r.found.join(" • ")}</div>`:""}${miss?`<div class="proposal-warn"><b>Tarvitsen vielä:</b><br>• ${r.missing.join("<br>• ")}</div>`:""}${r.warnings.length?`<div class="proposal-warn">${r.warnings.map(x=>`⚠ ${x}`).join("<br>")}</div>`:""}`;$("aiStatus").textContent=miss?"Pyyntö tunnistettiin, mutta kriittisiä mittoja puuttuu. Lisää ne tekstiin ja analysoi uudelleen.":"Ehdotus valmis. Tarkista mitat ja hyväksy."}
function apply(){if(!proposal||proposal.missing.length)return;$("material").value=proposal.material;window.AI3D.setPart(proposal.type,proposal.values);$("aiStatus").textContent=`✓ ${typeName(proposal.type)} luotu ja tarkistettu.`;$("aiProposal").hidden=true;$("aiApproval").hidden=true;document.querySelector(".preview-panel")?.scrollIntoView({behavior:"smooth",block:"start"})}
$("btnAiAnalyze").onclick=()=>{try{proposal=parse($("aiPrompt").value);show(proposal)}catch(e){$("aiStatus").textContent="Virhe: "+e.message}};$("btnAiExample").onclick=()=>{$("aiPrompt").value=examples[exampleIndex++%examples.length]};$("btnAiAccept").onclick=apply;$("btnAiReject").onclick=()=>{proposal=null;$("aiProposal").hidden=true;$("aiApproval").hidden=true;$("aiStatus").textContent="Ehdotus hylätty."};})();