"use strict";
const $=id=>document.getElementById(id);
const canvas=$("preview"),ctx=canvas.getContext("2d");
let currentMesh=null,currentFitMesh=null,drag=false,lastX=0,lastY=0,yaw=-0.55,pitch=0.32,measureMode=true;
const defaults={nutAf:33,clearance:.25,lockAmount:.20,lockZ:7,wall:2.5,baseHeight:24,totalHeight:75,tipRadius:.8,material:"ASA"};
const profiles={
 PLA:{label:"PLA",use:"Koekappaleet ja sisäkäyttö",nozzle:"210–220 °C",bed:"55–60 °C",note:"Helpoin ensimmäisiin sovitustesteihin."},
 PETG:{label:"PETG",use:"Käyttöosat ja kohtalainen ulkokäyttö",nozzle:"235–250 °C",bed:"70–85 °C",note:"Sitkeä ja helppo vaihtoehto ennen ASA:aa."},
 ASA:{label:"ASA",use:"Ulkokäyttö, UV ja sää",nozzle:"250–270 °C",bed:"90–105 °C",note:"Suositus lopulliseen rekkaosaan suljetulla tulostimella."}
};
function params(){const p={};for(const k of ["nutAf","clearance","lockAmount","lockZ","wall","baseHeight","totalHeight","tipRadius"])p[k]=Number($(k).value);p.material=$("material").value;if(!Object.values(p).filter(v=>typeof v==="number").every(Number.isFinite))throw Error("Tarkista mitat.");if(p.nutAf<=0)throw Error("Mutterin avainkoon pitää olla positiivinen.");if(p.clearance<0)throw Error("Välys ei voi olla negatiivinen.");if(p.wall<1)throw Error("Seinämän pitää olla vähintään 1 mm.");if(p.baseHeight<8)throw Error("Mutteriosan korkeus on liian pieni.");if(p.lockZ<2||p.lockZ>p.baseHeight-4)throw Error("Lukituksen korkeus pitää olla mutteriosan sisällä.");if(p.totalHeight<=p.baseHeight+8)throw Error("Kokonaiskorkeuden pitää olla selvästi mutteriosaa suurempi.");return p}
const v=(x,y,z)=>({x,y,z}),tri=(a,b,c)=>[a,b,c];
function normal(t){const[a,b,c]=t,u=v(b.x-a.x,b.y-a.y,b.z-a.z),w=v(c.x-a.x,c.y-a.y,c.z-a.z),n=v(u.y*w.z-u.z*w.y,u.z*w.x-u.x*w.z,u.x*w.y-u.y*w.x),l=Math.hypot(n.x,n.y,n.z)||1;return v(n.x/l,n.y/l,n.z/l)}
function hexVertices(af,z){const r=af/Math.sqrt(3),ph=Math.PI/6;return Array.from({length:6},(_,i)=>v(r*Math.cos(ph+i*Math.PI/3),r*Math.sin(ph+i*Math.PI/3),z))}
function hexRing(af,z,s=4){const a=hexVertices(af,z),out=[];for(let i=0;i<6;i++){const b=a[i],c=a[(i+1)%6];for(let j=0;j<s;j++){const t=j/s;out.push(v(b.x+(c.x-b.x)*t,b.y+(c.y-b.y)*t,z))}}return out}
function circleRing(r,z,n=24,ph=Math.PI/24){return Array.from({length:n},(_,i)=>v(r*Math.cos(ph+i*2*Math.PI/n),r*Math.sin(ph+i*2*Math.PI/n),z))}
function bridge(T,a,b,rev=false){for(let i=0;i<a.length;i++){const j=(i+1)%a.length;if(rev)T.push(tri(a[i],b[j],a[j]),tri(a[i],b[i],b[j]));else T.push(tri(a[i],a[j],b[j]),tri(a[i],b[j],b[i]))}}
function annulus(T,o,i,up=true){for(let n=0;n<o.length;n++){const j=(n+1)%o.length;if(up)T.push(tri(o[n],o[j],i[j]),tri(o[n],i[j],i[n]));else T.push(tri(o[n],i[j],o[j]),tri(o[n],i[n],i[j]))}}
function cap(T,r,z){const c=v(0,0,z);for(let i=0;i<r.length;i++)T.push(tri(r[i],r[(i+1)%r.length],c))}
function buildMesh(p){const n=24,innerAF=p.nutAf+2*p.clearance,lockAF=Math.max(p.nutAf-.1,innerAF-2*p.lockAmount),outerAF=innerAF+2*p.wall,innerTop=p.baseHeight-p.wall-1,hexTopZ=Math.max(innerTop+1,p.baseHeight-3),outerR=outerAF/2*1.02,tipBaseZ=p.totalHeight-p.tipRadius,tipR=Math.max(.18,p.tipRadius*.72),o0=hexRing(outerAF,0),o1=hexRing(outerAF,hexTopZ),sh=circleRing(outerR,p.baseHeight,n),i0=hexRing(innerAF,0),il=hexRing(lockAF,p.lockZ),it=hexRing(innerAF,innerTop),tr=circleRing(tipR,tipBaseZ,n),ap=v(0,0,p.totalHeight),T=[];bridge(T,o0,o1);bridge(T,o1,sh);bridge(T,i0,il,true);bridge(T,il,it,true);annulus(T,o0,i0,false);cap(T,it,innerTop);bridge(T,sh,tr);for(let i=0;i<n;i++)T.push(tri(tr[i],tr[(i+1)%n],ap));return{triangles:T,innerAF,lockAF,outerAF,height:p.totalHeight,baseHeight:p.baseHeight,lockZ:p.lockZ}}
function buildFitMesh(p){const innerAF=p.nutAf+2*p.clearance,lockAF=Math.max(p.nutAf-.1,innerAF-2*p.lockAmount),outerAF=innerAF+2*p.wall,h=Math.max(10,p.lockZ+4),o0=hexRing(outerAF,0),o1=hexRing(outerAF,h),i0=hexRing(innerAF,0),il=hexRing(lockAF,p.lockZ),i1=hexRing(innerAF,h),T=[];bridge(T,o0,o1);bridge(T,i0,il,true);bridge(T,il,i1,true);annulus(T,o0,i0,false);annulus(T,o1,i1,true);return{triangles:T,innerAF,lockAF,outerAF,height:h}}
function key(q){return`${q.x.toFixed(6)},${q.y.toFixed(6)},${q.z.toFixed(6)}`}function edge(a,b){const A=key(a),B=key(b);return A<B?A+"|"+B:B+"|"+A}
function validate(m){const edges=new Map();let deg=0;for(const t of m.triangles){const[a,b,c]=t,ar=Math.hypot((b.y-a.y)*(c.z-a.z)-(b.z-a.z)*(c.y-a.y),(b.z-a.z)*(c.x-a.x)-(b.x-a.x)*(c.z-a.z),(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));if(ar<1e-8)deg++;for(const[p1,p2]of[[a,b],[b,c],[c,a]]){const k=edge(p1,p2);edges.set(k,(edges.get(k)||0)+1)}}const bad=[...edges.values()].filter(n=>n!==2).length;if(deg)return{ok:false,message:`Meshissä on ${deg} nollapinta-alaista kolmiota.`};if(bad)return{ok:false,message:`Mesh ei ole suljettu: ${bad} reunaa ei jakaudu täsmälleen kahdelle pinnalle.`};return{ok:true,message:`Suljettu manifold-mesh: ${m.triangles.length} kolmiota, ${edges.size} reunaa.`}}
function stl(m,name){let s=`solid ${name}\n`;for(const t of m.triangles){const n=normal(t);s+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n`;for(const q of t)s+=`   vertex ${q.x} ${q.y} ${q.z}\n`;s+="  endloop\n endfacet\n"}return s+`endsolid ${name}\n`}
function project(q,sc,cx,cy){const x=q.x*Math.cos(yaw)-q.y*Math.sin(yaw),y=q.x*Math.sin(yaw)+q.y*Math.cos(yaw),yy=y*Math.cos(pitch)-q.z*Math.sin(pitch),zz=y*Math.sin(pitch)+q.z*Math.cos(pitch);return{x:cx+x*sc,y:cy-zz*sc,d:yy}}
function drawArrow(x1,y1,x2,y2){ctx.save();ctx.strokeStyle="#fbbf24";ctx.fillStyle="#fbbf24";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y1,x2-x1);for(const[x,y,ang]of[[x1,y1,a],[x2,y2,a+Math.PI]]){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+12*Math.cos(ang+.5),y+12*Math.sin(ang+.5));ctx.lineTo(x+12*Math.cos(ang-.5),y+12*Math.sin(ang-.5));ctx.closePath();ctx.fill()}ctx.restore()}
function drawText(text,x,y){ctx.save();ctx.font="700 20px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";const w=ctx.measureText(text).width+18,h=32;ctx.fillStyle="rgba(8,13,22,.94)";ctx.strokeStyle="#fbbf24";ctx.lineWidth=2;ctx.fillRect(x-w/2,y-h/2,w,h);ctx.strokeRect(x-w/2,y-h/2,w,h);ctx.fillStyle="#fde68a";ctx.fillText(text,x,y);ctx.restore()}
function drawMeasures(sc,cx,cy){if(!measureMode||!currentMesh)return;const m=currentMesh,baseY=cy,topY=cy-m.height*sc,right=cx+m.outerAF*sc/2+80,left=cx-m.outerAF*sc/2-80;drawArrow(right,baseY,right,topY);drawText(`${m.height.toFixed(1)} mm`,right,(baseY+topY)/2);const rows=[[m.outerAF,baseY+45,`Ulko-AF ${m.outerAF.toFixed(2)} mm`],[m.innerAF,baseY+95,`Sisä-AF ${m.innerAF.toFixed(2)} mm`],[m.lockAF,baseY+145,`Lukitus-AF ${m.lockAF.toFixed(2)} mm`]];for(const[af,y,t]of rows){drawArrow(cx-af*sc/2,y,cx+af*sc/2,y);drawText(t,cx,y+24)}const by=baseY-m.baseHeight*sc;drawArrow(left,baseY,left,by);drawText(`Mutteriosa ${m.baseHeight.toFixed(1)} mm`,left,(baseY+by)/2)}
function updateOverlay(){const o=$("measureOverlay");if(!o||!currentMesh)return;o.hidden=!measureMode;if(!measureMode)return;const m=currentMesh;o.innerHTML=`<span>Korkeus <b>${m.height.toFixed(1)} mm</b></span><span>Ulko-AF <b>${m.outerAF.toFixed(2)} mm</b></span><span>Sisä-AF <b>${m.innerAF.toFixed(2)} mm</b></span><span>Lukitus-AF <b>${m.lockAF.toFixed(2)} mm</b></span><span>Mutteriosa <b>${m.baseHeight.toFixed(1)} mm</b></span>`}
function draw(){const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);if(!currentMesh)return;const sc=Math.min(W/(currentMesh.outerAF*5.2),H/(currentMesh.height*1.85)),cx=W/2,cy=H*.63,faces=currentMesh.triangles.map(t=>{const p=t.map(q=>project(q,sc,cx,cy));return{p,d:p.reduce((a,b)=>a+b.d,0)/3}}).sort((a,b)=>a.d-b.d);for(const f of faces){ctx.beginPath();ctx.moveTo(f.p[0].x,f.p[0].y);ctx.lineTo(f.p[1].x,f.p[1].y);ctx.lineTo(f.p[2].x,f.p[2].y);ctx.closePath();ctx.fillStyle="rgba(20,184,166,.74)";ctx.fill();ctx.strokeStyle="rgba(153,246,228,.22)";ctx.lineWidth=1;ctx.stroke()}drawMeasures(sc,cx,cy);updateOverlay()}
function updateMaterial(){const m=profiles[$("material").value];$("materialCard").innerHTML=`<strong>${m.label}: ${m.use}</strong><span>Suutin ${m.nozzle} • Alusta ${m.bed}</span><span>${m.note}</span>`;$("legend").innerHTML=`<span>Valittu materiaali: <strong>${m.label}</strong></span><span>${m.note}</span>`}
function generate(){try{const p=params();currentMesh=buildMesh(p);currentFitMesh=buildFitMesh(p);const a=validate(currentMesh),b=validate(currentFitMesh),ok=a.ok&&b.ok;$("validation").innerHTML=`<div class="check ${ok?"ok":"fail"}"><strong>${ok?"✓ Automaattitarkistus OK":"✕ Automaattitarkistus epäonnistui"}</strong><br>${a.message}<br>Sovitustesti: ${b.message}</div>`;$("btnDownload").disabled=$("btnFitTest").disabled=!ok;$("status").textContent=ok?`Malli luotu ja tarkistettu. Perusaukko ${currentMesh.innerAF.toFixed(2)} mm, lukituskohdassa ${currentMesh.lockAF.toFixed(2)} mm.`:"Mallia ei anneta ladattavaksi ennen kuin mesh-tarkistus menee läpi.";$("dimensions").textContent=`Sisä-AF ${currentMesh.innerAF.toFixed(2)} mm • Lukitus-AF ${currentMesh.lockAF.toFixed(2)} mm • Ulko-AF ${currentMesh.outerAF.toFixed(2)} mm • Korkeus ${currentMesh.height.toFixed(1)} mm`;updateMaterial();draw()}catch(e){$("status").textContent="Virhe: "+e.message;$("btnDownload").disabled=$("btnFitTest").disabled=true}}
function saveMesh(m,file,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([stl(m,name)],{type:"model/stl"}));a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("btnGenerate").onclick=generate;
$("btnDownload").onclick=()=>currentMesh&&saveMesh(currentMesh,"piikkimutterinsuojus_33mm_v0.4.1.stl","piikkimutteri_v041");
$("btnFitTest").onclick=()=>currentFitMesh&&saveMesh(currentFitMesh,"piikkimutteri_33mm_sovitustesti_v0.4.1.stl","sovitustesti_v041");
$("btnReset").onclick=()=>{for(const[k,val]of Object.entries(defaults))$(k).value=val;generate()};
$("material").onchange=updateMaterial;
$("btnMeasure").onclick=()=>{measureMode=!measureMode;$("btnMeasure").classList.toggle("active",measureMode);$("btnMeasure").textContent=`MITTANÄKYMÄ: ${measureMode?"PÄÄLLÄ":"POIS"}`;draw()};
$("btnFront").onclick=()=>{yaw=0;pitch=0;draw()};
$("btnIso").onclick=()=>{yaw=-.55;pitch=.32;draw()};
canvas.addEventListener("pointerdown",e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener("pointermove",e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.012;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-lastY)*.01));lastX=e.clientX;lastY=e.clientY;draw()});
canvas.addEventListener("pointerup",()=>drag=false);canvas.addEventListener("pointercancel",()=>drag=false);
updateMaterial();generate();