"use strict";
const $=id=>document.getElementById(id),canvas=$("preview"),ctx=canvas.getContext("2d");
let currentMesh=null,currentFitMesh=null,drag=false,lastX=0,lastY=0,yaw=-.55,pitch=.32,measureMode=true;
const defaults={partType:"spike",nutAf:33,clearance:.25,lockAmount:.2,lockZ:7,wall:2.5,baseHeight:24,totalHeight:75,tipRadius:.8,tubeW:50,tubeH:30,tubeWall:2.5,plugClear:.25,insertDepth:18,capThickness:3,capOverhang:1,sleeveID:20,sleeveWall:3,sleeveLength:30,plateL:100,plateW:50,plateT:4,material:"ASA"};
const profiles={PLA:{label:"PLA",use:"Koekappaleet ja sisäkäyttö",nozzle:"210–220 °C",bed:"55–60 °C",note:"Helpoin ensimmäisiin testeihin."},PETG:{label:"PETG",use:"Käyttöosat",nozzle:"235–250 °C",bed:"70–85 °C",note:"Sitkeä ja helppo yleismateriaali."},ASA:{label:"ASA",use:"Ulkokäyttö, UV ja sää",nozzle:"250–270 °C",bed:"90–105 °C",note:"Hyvä ulko-osiin suljetulla tulostimella."}};
const v=(x,y,z)=>({x,y,z}),tri=(a,b,c)=>[a,b,c];
function normal(t){const[a,b,c]=t,u=v(b.x-a.x,b.y-a.y,b.z-a.z),w=v(c.x-a.x,c.y-a.y,c.z-a.z),n=v(u.y*w.z-u.z*w.y,u.z*w.x-u.x*w.z,u.x*w.y-u.y*w.x),l=Math.hypot(n.x,n.y,n.z)||1;return v(n.x/l,n.y/l,n.z/l)}
function bridge(T,a,b,rev=false){for(let i=0;i<a.length;i++){const j=(i+1)%a.length;if(rev)T.push(tri(a[i],b[j],a[j]),tri(a[i],b[i],b[j]));else T.push(tri(a[i],a[j],b[j]),tri(a[i],b[j],b[i]))}}
function annulus(T,o,i,up=true){for(let n=0;n<o.length;n++){const j=(n+1)%o.length;if(up)T.push(tri(o[n],o[j],i[j]),tri(o[n],i[j],i[n]));else T.push(tri(o[n],i[j],o[j]),tri(o[n],i[n],i[j]))}}
function cap(T,r,z,up=true){const c=v(0,0,z);for(let i=0;i<r.length;i++){const j=(i+1)%r.length;T.push(up?tri(r[i],r[j],c):tri(r[i],c,r[j]))}}
function rectRing(w,d,z){return [v(-w/2,-d/2,z),v(w/2,-d/2,z),v(w/2,d/2,z),v(-w/2,d/2,z)]}
function circleRing(r,z,n=48){return Array.from({length:n},(_,i)=>v(r*Math.cos(i*2*Math.PI/n),r*Math.sin(i*2*Math.PI/n),z))}
function hexVertices(af,z){const r=af/Math.sqrt(3),ph=Math.PI/6;return Array.from({length:6},(_,i)=>v(r*Math.cos(ph+i*Math.PI/3),r*Math.sin(ph+i*Math.PI/3),z))}
function hexRing(af,z,s=4){const a=hexVertices(af,z),out=[];for(let i=0;i<6;i++){const b=a[i],c=a[(i+1)%6];for(let j=0;j<s;j++){const t=j/s;out.push(v(b.x+(c.x-b.x)*t,b.y+(c.y-b.y)*t,z))}}return out}
function boxMesh(w,d,h){const r0=rectRing(w,d,0),r1=rectRing(w,d,h),T=[];bridge(T,r0,r1);cap(T,r0,0,false);cap(T,r1,h,true);return T}
function buildSpike(){const p={nutAf:+$("nutAf").value,clearance:+$("clearance").value,lockAmount:+$("lockAmount").value,lockZ:+$("lockZ").value,wall:+$("wall").value,baseHeight:+$("baseHeight").value,totalHeight:+$("totalHeight").value,tipRadius:+$("tipRadius").value};if(p.wall<1||p.totalHeight<=p.baseHeight+8)throw Error("Tarkista piikkimutterin mitat.");const n=24,innerAF=p.nutAf+2*p.clearance,lockAF=Math.max(p.nutAf-.1,innerAF-2*p.lockAmount),outerAF=innerAF+2*p.wall,innerTop=p.baseHeight-p.wall-1,hexTopZ=Math.max(innerTop+1,p.baseHeight-3),outerR=outerAF/2*1.02,tipBaseZ=p.totalHeight-p.tipRadius,tipR=Math.max(.18,p.tipRadius*.72),o0=hexRing(outerAF,0),o1=hexRing(outerAF,hexTopZ),sh=circleRing(outerR,p.baseHeight,n),i0=hexRing(innerAF,0),il=hexRing(lockAF,p.lockZ),it=hexRing(innerAF,innerTop),tr=circleRing(tipR,tipBaseZ,n),ap=v(0,0,p.totalHeight),T=[];bridge(T,o0,o1);bridge(T,o1,sh);bridge(T,i0,il,true);bridge(T,il,it,true);annulus(T,o0,i0,false);cap(T,it,innerTop,true);bridge(T,sh,tr);for(let i=0;i<n;i++)T.push(tri(tr[i],tr[(i+1)%n],ap));const fitH=Math.max(10,p.lockZ+4),fo0=hexRing(outerAF,0),fo1=hexRing(outerAF,fitH),fi0=hexRing(innerAF,0),fil=hexRing(lockAF,p.lockZ),fi1=hexRing(innerAF,fitH),FT=[];bridge(FT,fo0,fo1);bridge(FT,fi0,fil,true);bridge(FT,fil,fi1,true);annulus(FT,fo0,fi0,false);annulus(FT,fo1,fi1,true);currentFitMesh={triangles:FT,name:"sovitustesti"};return{triangles:T,name:"piikkimutterinsuojus",width:outerAF,depth:outerAF,height:p.totalHeight,measure:[["Korkeus",p.totalHeight],["Ulko-AF",outerAF],["Sisä-AF",innerAF],["Lukitus-AF",lockAF],["Mutteriosa",p.baseHeight]]}}
function buildPlug(){const W=+$("tubeW").value,H=+$("tubeH").value,tw=+$("tubeWall").value,c=+$("plugClear").value,ins=+$("insertDepth").value,ct=+$("capThickness").value,ov=+$("capOverhang").value,sw=W-2*tw-2*c,sh=H-2*tw-2*c;if(sw<=2||sh<=2||ins<=2||ct<=1)throw Error("Päätytulpan mitat eivät ole mahdollisia.");const s0=rectRing(sw,sh,0),s1=rectRing(sw,sh,ins),c0=rectRing(W+2*ov,H+2*ov,ins),c1=rectRing(W+2*ov,H+2*ov,ins+ct),T=[];cap(T,s0,0,false);bridge(T,s0,s1);annulus(T,c0,s1,true);bridge(T,c0,c1);cap(T,c1,ins+ct,true);currentFitMesh=null;return{triangles:T,name:"paatytulppa",width:W+2*ov,depth:H+2*ov,height:ins+ct,measure:[["Putki",`${W.toFixed(1)} × ${H.toFixed(1)} mm`],["Tulpan varsi",`${sw.toFixed(2)} × ${sh.toFixed(2)} mm`],["Upotus",ins],["Päätylevy",ct]]}}
function buildSleeve(){const id=+$("sleeveID").value,w=+$("sleeveWall").value,h=+$("sleeveLength").value;if(id<=0||w<1||h<=2)throw Error("Holkin mitat eivät ole mahdollisia.");const ir=id/2,or=ir+w,o0=circleRing(or,0),o1=circleRing(or,h),i0=circleRing(ir,0),i1=circleRing(ir,h),T=[];bridge(T,o0,o1);bridge(T,i0,i1,true);annulus(T,o0,i0,false);annulus(T,o1,i1,true);currentFitMesh=null;return{triangles:T,name:"holkki",width:2*or,depth:2*or,height:h,measure:[["Sisä Ø",id],["Ulko Ø",2*or],["Seinämä",w],["Pituus",h]]}}
function buildPlate(){const L=+$("plateL").value,W=+$("plateW").value,T=+$("plateT").value;if(L<=2||W<=2||T<1)throw Error("Levyn mitat eivät ole mahdollisia.");currentFitMesh=null;return{triangles:boxMesh(L,W,T),name:"kiinnikeaihio",width:L,depth:W,height:T,measure:[["Pituus",L],["Leveys",W],["Paksuus",T]]}}
function key(q){return`${q.x.toFixed(6)},${q.y.toFixed(6)},${q.z.toFixed(6)}`}function edge(a,b){const A=key(a),B=key(b);return A<B?A+"|"+B:B+"|"+A}
function validate(m){const edges=new Map();let deg=0;for(const t of m.triangles){const[a,b,c]=t,ar=Math.hypot((b.y-a.y)*(c.z-a.z)-(b.z-a.z)*(c.y-a.y),(b.z-a.z)*(c.x-a.x)-(b.x-a.x)*(c.z-a.z),(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));if(ar<1e-8)deg++;for(const[p1,p2]of[[a,b],[b,c],[c,a]]){const k=edge(p1,p2);edges.set(k,(edges.get(k)||0)+1)}}const bad=[...edges.values()].filter(n=>n!==2).length;return deg?{ok:false,message:`${deg} nollakolmiota.`}:bad?{ok:false,message:`Mesh ei ole suljettu: ${bad} reunaa.`}:{ok:true,message:`Suljettu manifold-mesh: ${m.triangles.length} kolmiota.`}}
function stl(m,name){let s=`solid ${name}\n`;for(const t of m.triangles){const n=normal(t);s+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n`;for(const q of t)s+=`   vertex ${q.x} ${q.y} ${q.z}\n`;s+="  endloop\n endfacet\n"}return s+`endsolid ${name}\n`}
function project(q,sc,cx,cy){const x=q.x*Math.cos(yaw)-q.y*Math.sin(yaw),y=q.x*Math.sin(yaw)+q.y*Math.cos(yaw),yy=y*Math.cos(pitch)-q.z*Math.sin(pitch),zz=y*Math.sin(pitch)+q.z*Math.cos(pitch);return{x:cx+x*sc,y:cy-zz*sc,d:yy}}
function updateOverlay(){const o=$("measureOverlay");o.hidden=!measureMode;if(!currentMesh||!measureMode)return;o.innerHTML=currentMesh.measure.map(([k,val])=>`<span>${k} <b>${typeof val==="number"?val.toFixed(2)+" mm":val}</b></span>`).join("")}
function draw(){const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);if(!currentMesh)return;const span=Math.max(currentMesh.width,currentMesh.depth,10),sc=Math.min(W/(span*3.2),H/(Math.max(currentMesh.height,10)*2.0)),cx=W/2,cy=H*.68,faces=currentMesh.triangles.map(t=>{const p=t.map(q=>project(q,sc,cx,cy));return{p,d:p.reduce((a,b)=>a+b.d,0)/3}}).sort((a,b)=>a.d-b.d);for(const f of faces){ctx.beginPath();ctx.moveTo(f.p[0].x,f.p[0].y);ctx.lineTo(f.p[1].x,f.p[1].y);ctx.lineTo(f.p[2].x,f.p[2].y);ctx.closePath();ctx.fillStyle="rgba(20,184,166,.74)";ctx.fill();ctx.strokeStyle="rgba(153,246,228,.22)";ctx.stroke()}updateOverlay()}
function updateMaterial(){const m=profiles[$("material").value];$("materialCard").innerHTML=`<strong>${m.label}: ${m.use}</strong><span>Suutin ${m.nozzle} • Alusta ${m.bed}</span><span>${m.note}</span>`;$("legend").innerHTML=`<span>Valittu materiaali: <strong>${m.label}</strong></span><span>${m.note}</span>`}
function updateFields(){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);const type=$("partType").value;$("fields-"+type).hidden=false;const titles={spike:"Piikkimutterinsuojus",plug:"Suorakaideputken päätytulppa",sleeve:"Holkki / soviterengas",plate:"Levy / kiinnikeaihio"};$("partTitle").textContent=titles[type];$("btnFitTest").style.display=type==="spike"?"":"none"}
function generate(){try{updateFields();const type=$("partType").value;currentMesh=type==="spike"?buildSpike():type==="plug"?buildPlug():type==="sleeve"?buildSleeve():buildPlate();const a=validate(currentMesh),b=currentFitMesh?validate(currentFitMesh):{ok:true,message:"Ei erillistä sovitustestiä."},ok=a.ok&&b.ok;$("validation").innerHTML=`<div class="check ${ok?"ok":"fail"}"><strong>${ok?"✓ Automaattitarkistus OK":"✕ Tarkistus epäonnistui"}</strong><br>${a.message}<br>${b.message}</div>`;$("btnDownload").disabled=!ok;$("btnFitTest").disabled=!ok;$("status").textContent=ok?"Malli luotu ja tarkistettu. Tarkista mitat ennen tulostusta.":"STL-lataus estetty virheen vuoksi.";$("dimensions").textContent=currentMesh.measure.map(([k,v])=>`${k} ${typeof v==="number"?v.toFixed(2)+" mm":v}`).join(" • ");updateMaterial();draw()}catch(e){$("status").textContent="Virhe: "+e.message;$("btnDownload").disabled=true}}
function saveMesh(m,file){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([stl(m,m.name)],{type:"model/stl"}));a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.AI3D={setPart:(type,values={})=>{$("partType").value=type;updateFields();for(const[k,v]of Object.entries(values))if($(k))$(k).value=v;generate()},generate};
$("partType").onchange=generate;$("btnGenerate").onclick=generate;$("btnDownload").onclick=()=>currentMesh&&saveMesh(currentMesh,`${currentMesh.name}_v0.6.stl`);$("btnFitTest").onclick=()=>currentFitMesh&&saveMesh(currentFitMesh,"piikkimutteri_sovitustesti_v0.6.stl");$("btnReset").onclick=()=>{for(const[k,v]of Object.entries(defaults))if($(k))$(k).value=v;$("partType").value="spike";generate()};$("material").onchange=updateMaterial;$("btnMeasure").onclick=()=>{measureMode=!measureMode;$("btnMeasure").textContent=`MITTANÄKYMÄ: ${measureMode?"PÄÄLLÄ":"POIS"}`;draw()};$("btnFront").onclick=()=>{yaw=0;pitch=0;draw()};$("btnIso").onclick=()=>{yaw=-.55;pitch=.32;draw()};canvas.addEventListener("pointerdown",e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.012;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-lastY)*.01));lastX=e.clientX;lastY=e.clientY;draw()});canvas.addEventListener("pointerup",()=>drag=false);updateFields();updateMaterial();generate();