"use strict";
const $=id=>document.getElementById(id),canvas=$("preview"),ctx=canvas.getContext("2d");
let currentMesh=null,currentFitMesh=null,drag=false,lastX=0,lastY=0,yaw=-.55,pitch=.32,measureMode=true;
const defaults={nutAf:33,clearance:.25,lockAmount:.20,lockZ:7,wall:2.5,baseHeight:24,totalHeight:75,tipRadius:.8,material:"ASA"};
const materialProfiles={PLA:{label:"PLA",use:"Koekappaleet ja sisäkäyttö",nozzle:"210–220 °C",bed:"55–60 °C",note:"Helpoin materiaalivalinta ensimmäisiin sovitustesteihin."},PETG:{label:"PETG",use:"Käyttöosat ja kohtalainen ulkokäyttö",nozzle:"235–250 °C",bed:"70–85 °C",note:"Sitkeä ja helppo vaihtoehto ennen ASA:aa."},ASA:{label:"ASA",use:"Ulkokäyttö, UV ja sää",nozzle:"250–270 °C",bed:"90–105 °C",note:"Suositus lopulliseen rekkaosaan suljetulla tulostimella."}};
function params(){const p={};for(const k of ["nutAf","clearance","lockAmount","lockZ","wall","baseHeight","totalHeight","tipRadius"])p[k]=Number($(k).value);p.material=$("material").value;if(!Object.values(p).filter(v=>typeof v==="number").every(Number.isFinite))throw Error("Tarkista mitat.");if(p.nutAf<=0)throw Error("Mutterin avainkoon pitää olla positiivinen.");if(p.clearance<0)throw Error("Välys ei voi olla negatiivinen.");if(p.lockAmount<0||p.lockAmount>p.clearance*2+1)throw Error("Puristuslukituksen arvo on liian suuri.");if(p.wall<1)throw Error("Seinämän pitää olla vähintään 1 mm.");if(p.baseHeight<8)throw Error("Mutteriosan korkeus on liian pieni.");if(p.lockZ<2||p.lockZ>p.baseHeight-4)throw Error("Lukituksen korkeus pitää olla mutteriosan sisällä.");if(p.totalHeight<=p.baseHeight+8)throw Error("Kokonaiskorkeuden pitää olla selvästi mutteriosaa suurempi.");return p}
const v=(x,y,z)=>({x,y,z}),tri=(a,b,c)=>[a,b,c];function normal(t){const[a,b,c]=t,u=v(b.x-a.x,b.y-a.y,b.z-a.z),w=v(c.x-a.x,c.y-a.y,c.z-a.z),n=v(u.y*w.z-u.z*w.y,u.z*w.x-u.x*w.z,u.x*w.y-u.y*w.x),l=Math.hypot(n.x,n.y,n.z)||1;return v(n.x/l,n.y/l,n.z/l)}
function hexVerticesFromAF(af,z){const r=af/Math.sqrt(3),ph=Math.PI/6;return Array.from({length:6},(_,i)=>v(r*Math.cos(ph+i*Math.PI/3),r*Math.sin(ph+i*Math.PI/3),z))}
function sampledHexRing(af,z,s=4){const a=hexVerticesFromAF(af,z),o=[];for(let i=0;i<6;i++){const b=a[i],c=a[(i+1)%6];for(let j=0;j<s;j++){const t=j/s;o.push(v(b.x+(c.x-b.x)*t,b.y+(c.y-b.y)*t,z))}}return o}
function circleRing(r,z,n=24,ph=Math.PI/24){return Array.from({length:n},(_,i)=>v(r*Math.cos(ph+i*2*Math.PI/n),r*Math.sin(ph+i*2*Math.PI/n),z))}
function bridge(T,a,b,rev=false){for(let i=0;i<a.length;i++){const j=(i+1)%a.length;if(!rev)T.push(tri(a[i],a[j],b[j]),tri(a[i],b[j],b[i]));else T.push(tri(a[i],b[j],a[j]),tri(a[i],b[i],b[j]))}}
function annulus(T,o,inn,up=true){for(let i=0;i<o.length;i++){const j=(i+1)%o.length;if(up)T.push(tri(o[i],o[j],inn[j]),tri(o[i],inn[j],inn[i]));else T.push(tri(o[i],inn[j],o[j]),tri(o[i],innerSafe(inn,i),innerSafe(inn,j)]))}}
function innerSafe(a,i){return a[i]}
function capRing(T,r,z,up=true){const c=v(0,0,z);for(let i=0;i<r.length;i++){const j=(i+1)%r.length;T.push(up?tri(r[i],r[j],c):tri(r[i],c,r[j]))}}
function buildMesh(p){const n=24,innerAF=p.nutAf+2*p.clearance,lockAF=Math.max(p.nutAf-.1,innerAF-2*p.lockAmount),outerAF=innerAF+2*p.wall,innerTop=p.baseHeight-p.wall-1,hexTopZ=Math.max(innerTop+1,p.baseHeight-3),outerR=(outerAF/2)*1.02,tipBaseZ=p.totalHeight-p.tipRadius,tipR=Math.max(.18,p.tipRadius*.72),outer0=sampledHexRing(outerAF,0),outerTop=sampledHexRing(outerAF,hexTopZ),shoulder=circleRing(outerR,p.baseHeight,n),inner0=sampledHexRing(innerAF,0),innerLock=sampledHexRing(lockAF,p.lockZ),innerTopRing=sampledHexRing(innerAF,innerTop),tipRing=circleRing(tipR,tipBaseZ,n),apex=v(0,0,p.totalHeight),T=[];bridge(T,outer0,outerTop);bridge(T,outerTop,shoulder);bridge(T,inner0,innerLock,true);bridge(T,innerLock,innerTopRing,true);annulus(T,outer0,inner0,false);capRing(T,innerTopRing,innerTop,true);bridge(T,shoulder,tipRing);for(let i=0;i<n;i++)T.push(tri(tipRing[i],tipRing[(i+1)%n],apex));return{triangles:T,innerAF,lockAF,outerAF,height:p.totalHeight,baseHeight:p.baseHeight,lockZ:p.lockZ}}
function buildFitMesh(p){const innerAF=p.nutAf+2*p.clearance,lockAF=Math.max(p.nutAf-.1,innerAF-2*p.lockAmount),outerAF=innerAF+2*p.wall,h=Math.max(10,p.lockZ+4),o0=sampledHexRing(outerAF,0),o1=sampledHexRing(outerAF,h),i0=sampledHexRing(innerAF,0),il=sampledHexRing(lockAF,p.lockZ),i1=sampledHexRing(innerAF,h),T=[];bridge(T,o0,o1);bridge(T,i0,il,true);bridge(T,il,i1,true);annulus(T,o0,i0,false);annulus(T,o1,i1,true);return{triangles:T,innerAF,lockAF,outerAF,height:h}}
function keyPoint(q){return`${q.x.toFixed(6)},${q.y.toFixed(6)},${q.z.toFixed(6)}`}function edgeKey(a,b){const A=keyPoint(a),B=keyPoint(b);return A<B?`${A}|${B}`:`${B}|${A}`}function validateMesh(m){const edges=new Map();let deg=0;for(const t of m.triangles){const[a,b,c]=t,ar=Math.hypot((b.y-a.y)*(c.z-a.z)-(b.z-a.z)*(c.y-a.y),(b.z-a.z)*(c.x-a.x)-(b.x-a.x)*(c.z-a.z),(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));if(ar<1e-8)deg++;for(const[p1,p2]of[[a,b],[b,c],[c,a]]){const k=edgeKey(p1,p2);edges.set(k,(edges.get(k)||0)+1)}}const bad=[...edges.values()].filter(n=>n!==2).length;if(deg)return{ok:false,message:`Meshissä on ${deg} nollapinta-alaista kolmiota.`};if(bad)return{ok:false,message:`Mesh ei ole suljettu: ${bad} reunaa ei jakaudu täsmälleen kahdelle pinnalle.`};return{ok:true,message:`Suljettu manifold-mesh: ${m.triangles.length} kolmiota, ${edges.size} reunaa.`}}
function stl(m,name){let s=`solid ${name}\n`;for(const t of m.triangles){const n=normal(t);s+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n`;for(const q of t)s+=`   vertex ${q.x} ${q.y} ${q.z}\n`;s+="  endloop\n endfacet\n"}return s+`endsolid ${name}\n`}
function project(q,sc,cx,cy){const x=q.x*Math.cos(yaw)-q.y*Math.sin(yaw),y=q.x*Math.sin(yaw)+q.y*Math.cos(yaw),yy=y*Math.cos(pitch)-q.z*Math.sin(pitch),zz=y*Math.sin(pitch)+q.z*Math.cos(pitch);return{x:cx+x*sc,y:cy-zz*sc,d:yy}}
function arrow(x1,y1,x2,y2){ctx.strokeStyle="#fbbf24";ctx.fillStyle="#fbbf24";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y1,x2-x1);for(const[x,y,ang]of[[x1,y1,a],[x2,y2,a+Math.PI]]){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+10*Math.cos(ang+.45),y+10*Math.sin(ang+.45));ctx.lineTo(x+10*Math.cos(ang-.45),y+10*Math.sin(ang-.45));ctx.closePath();ctx.fill()}}
function label(text,x,y){ctx.font="700 18px system-ui";const w=ctx.measureText(text).width+16;ctx.fillStyle="rgba(8,13,22,.9)";ctx.strokeStyle="#fbbf24";ctx.lineWidth=1.2;ctx.beginPath();ctx.roundRect(x-w/2,y-17,w,28,7);ctx.fill();ctx.stroke();ctx.fillStyle="#fde68a";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,x,y-3)}
function drawMeasures(sc,cx,cy){if(!measureMode||!currentMesh)return;const m=currentMesh,p=params();const left=cx-currentMesh.outerAF*sc*.9,right=cx+currentMesh.outerAF*sc*.9,baseY=cy,topY=cy-currentMesh.height*sc;arrow(right+48,baseY,right+48,topY);label(`${m.height.toFixed(1)} mm`,right+48,(baseY+topY)/2);const y1=baseY+38;arrow(cx-m.outerAF*sc/2,y1,cx+m.outerAF*sc/2,y1);label(`Ulko-AF ${m.outerAF.toFixed(2)} mm`,cx,y1+26);const y2=baseY+88;arrow(cx-m.innerAF*sc/2,y2,cx+m.innerAF*sc/2,y2);label(`Sisä-AF ${m.innerAF.toFixed(2)} mm`,cx,y2+26);const y3=baseY+138;arrow(cx-m.lockAF*sc/2,y3,cx+m.lockAF*sc/2,y3);label(`Lukitus-AF ${m.lockAF.toFixed(2)} mm`,cx,y3+26);const bhY=baseY-m.baseHeight*sc;arrow(left-42,baseY,left-42,bhY);label(`Mutteriosa ${m.baseHeight.toFixed(1)} mm`,left-42,(baseY+bhY)/2)}
function draw(){const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);if(!currentMesh)return;const sc=Math.min(W/(currentMesh.outerAF*4.5),H/(currentMesh.height*1.65)),cx=W/2,cy=H*.72,fs=currentMesh.triangles.map(t=>{const p=t.map(q=>project(q,sc,cx,cy));return{p,d:p.reduce((a,b)=>a+b.d,0)/3}}).sort((a,b)=>a.d-b.d);for(const f of fs){ctx.beginPath();ctx.moveTo(f.p[0].x,f.p[0].y);ctx.lineTo(f.p[1].x,f.p[1].y);ctx.lineTo(f.p[2].x,f.p[2].y);ctx.closePath();ctx.fillStyle="rgba(20,184,166,.74)";ctx.fill();ctx.strokeStyle="rgba(153,246,228,.22)";ctx.stroke()}drawMeasures(sc,cx,cy)}
function updateMaterialCard(){const m=materialProfiles[$("material").value];$("materialCard").innerHTML=`<strong>${m.label}: ${m.use}</strong><span>Suutin ${m.nozzle} • Alusta ${m.bed}</span><span>${m.note}</span>`;$("legend").innerHTML=`<span>Valittu materiaali: <strong>${m.label}</strong></span><span>${m.note}</span>`}
function generate(){try{const p=params();currentMesh=buildMesh(p);currentFitMesh=buildFitMesh(p);const a=validateMesh(currentMesh),b=validateMesh(currentFitMesh),ok=a.ok&&b.ok;$("validation").innerHTML=`<div class="check ${ok?"ok":"fail"}"><strong>${ok?"✓ Automaattitarkistus OK":"✕ Automaattitarkistus epäonnistui"}</strong><br>${a.message}<br>Sovitustesti: ${b.message}</div>`;$("btnDownload").disabled=$("btnFitTest").disabled=!ok;$("status").textContent=ok?`Malli luotu ja tarkistettu. Perusaukko ${currentMesh.innerAF.toFixed(2)} mm, lukituskohdassa ${currentMesh.lockAF.toFixed(2)} mm.`:"Mallia ei anneta ladattavaksi ennen kuin mesh-tarkistus menee läpi.";$("dimensions").textContent=`Sisä-AF ${currentMesh.innerAF.toFixed(2)} mm • Lukitus-AF ${currentMesh.lockAF.toFixed(2)} mm • Ulko-AF ${currentMesh.outerAF.toFixed(2)} mm • Korkeus ${currentMesh.height.toFixed(1)} mm`;updateMaterialCard();draw()}catch(e){$("status").textContent="Virhe: "+e.message;$("btnDownload").disabled=$("btnFitTest").disabled=true}}
function saveMesh(m,file,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([stl(m,name)],{type:"model/stl"}));a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("btnGenerate").onclick=generate;$("btnDownload").onclick=()=>currentMesh&&saveMesh(currentMesh,"piikkimutterinsuojus_33mm_v0.4.stl","piikkimutteri_v04");$("btnFitTest").onclick=()=>currentFitMesh&&saveMesh(currentFitMesh,"piikkimutteri_33mm_sovitustesti_v0.4.stl","sovitustesti_v04");$("btnReset").onclick=()=>{for(const[k,val]of Object.entries(defaults))$(k).value=val;generate()};$("material").onchange=updateMaterialCard;$("btnMeasure").onclick=()=>{measureMode=!measureMode;$("btnMeasure").classList.toggle("active",measureMode);$("btnMeasure").textContent=`MITTANÄKYMÄ: ${measureMode?"PÄÄLLÄ":"POIS"}`;draw()};$("btnFront").onclick=()=>{yaw=0;pitch=0;draw()};$("btnIso").onclick=()=>{yaw=-.55;pitch=.32;draw()};canvas.addEventListener("pointerdown",e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.012;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-lastY)*.01));lastX=e.clientX;lastY=e.clientY;draw()});canvas.addEventListener("pointerup",()=>drag=false);updateMaterialCard();generate();