"use strict";
(()=>{
 const $=id=>document.getElementById(id),V2_TYPES=new Set(["adapter","enclosure"]),MATERIALS=new Set(["PLA","PETG","ASA"]),MAX_MM=5000,MAX_HOLES=200;
 const partType=$("partType"),plateFields=$("fields-plate"),btnGenerate=$("btnGenerate"),DEFAULT_MATERIAL=$("material")?.value||"PETG";
 if(!partType||!plateFields||!btnGenerate||!window.AI3D)return;
 function addOption(value,label){if(partType.querySelector(`option[value="${value}"]`))return;const o=document.createElement("option");o.value=value;o.textContent=label;partType.appendChild(o)}
 addOption("adapter","Pyöreä adapteri / sovite");
 addOption("enclosure","Kotelo / rasia");
 if(!$("fields-adapter"))plateFields.insertAdjacentHTML("afterend",`<div id="fields-adapter" class="part-fields" hidden><div class="section-title">Pyöreä adapteri / sovite</div><div class="grid"><label>Pituus (mm)<input id="adapterLength" type="number" value="30" min="2" max="2000" step="0.5"></label><label>Sisä Ø alku (mm)<input id="adapterID1" type="number" value="20" min="1" max="1000" step="0.1"></label><label>Sisä Ø loppu (mm)<input id="adapterID2" type="number" value="20" min="1" max="1000" step="0.1"></label><label>Ulko Ø alku (mm)<input id="adapterOD1" type="number" value="26" min="1" max="1500" step="0.1"></label><label>Ulko Ø loppu (mm)<input id="adapterOD2" type="number" value="26" min="1" max="1500" step="0.1"></label></div></div><div id="fields-enclosure" class="part-fields" hidden><div class="section-title">Kotelo / rasia</div><div class="grid"><label>Leveys (mm)<input id="enclosureW" type="number" value="80" min="5" max="2000" step="0.5"></label><label>Pituus (mm)<input id="enclosureD" type="number" value="60" min="5" max="2000" step="0.5"></label><label>Korkeus (mm)<input id="enclosureH" type="number" value="30" min="5" max="2000" step="0.5"></label><label>Seinämä (mm)<input id="enclosureWall" type="number" value="2.4" min="0.8" max="200" step="0.1"></label><label>Pohja (mm)<input id="enclosureFloor" type="number" value="2.4" min="0.8" max="200" step="0.1"></label></div></div>`);
 const oldSetPart=window.AI3D.setPart.bind(window.AI3D),oldChange=partType.onchange,oldGenerate=btnGenerate.onclick;
 const readNum=id=>{const e=$(id),n=e?.valueAsNumber;if(!Number.isFinite(n))throw Error(`${id}: anna kelvollinen numero.`);const min=e?.min!==""?Number(e.min):NaN,max=e?.max!==""?Number(e.max):NaN;if(Number.isFinite(min)&&n<min)throw Error(`${id}: arvon pitää olla vähintään ${min} mm.`);if(Number.isFinite(max)&&n>max)throw Error(`${id}: arvo saa olla enintään ${max} mm.`);if(Math.abs(n)>MAX_MM)throw Error(`${id}: arvo saa olla enintään ${MAX_MM} mm.`);return n};
 function show(type){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);const f=$("fields-"+type);if(!f)throw Error("Osatyypin editoria ei löytynyt.");f.hidden=false;const titles={adapter:"Pyöreä adapteri / sovite",enclosure:"Kotelo / rasia"};if($("partTitle"))$("partTitle").textContent=titles[type]||type;if($("btnFitTest"))$("btnFitTest").style.display="none"}
 function showPlate(){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);plateFields.hidden=false;if($("partTitle"))$("partTitle").textContent="Kiinnikelevy";restoreStandardUi()}
 function restoreStandardUi(){const b=$("btnFitTest");if(b)b.style.display=""}
 function validateGeometry(type,p){if(type==="adapter"&&(p.outsideDiameter1<=p.insideDiameter1+.8||p.outsideDiameter2<=p.insideDiameter2+.8))throw Error("Adapterin ulkohalkaisijan pitää jättää vähintään 0,4 mm seinämä molempiin päihin.");if(type==="enclosure"&&(p.width<=2*p.wall+2||p.length<=2*p.wall+2||p.height<=p.floorThickness+2))throw Error("Kotelon sisätila ei mahdu annettuihin ulkomittoihin.");return p}
 function parameters(type){if(type==="adapter")return validateGeometry(type,{length:readNum("adapterLength"),insideDiameter1:readNum("adapterID1"),insideDiameter2:readNum("adapterID2"),outsideDiameter1:readNum("adapterOD1"),outsideDiameter2:readNum("adapterOD2")});return validateGeometry(type,{width:readNum("enclosureW"),length:readNum("enclosureD"),height:readNum("enclosureH"),wall:readNum("enclosureWall"),floorThickness:readNum("enclosureFloor")})}
 function resetMissingValues(type,values){const root=$("fields-"+type);if(!root)return;root.querySelectorAll("input[id],select[id]").forEach(e=>{const v=values?.[e.id];e.value=v!=null?v:e.defaultValue})}
 function resetMaterial(values){const e=$("material");if(!e)return;const v=values?.material??DEFAULT_MATERIAL;if(!MATERIALS.has(v))throw Error("Projektin tulostusmateriaalia ei tueta tässä versiossa.");e.value=v}
 function plateHoleLines(plan){const p=plan?.parameters||{},out=[],seen=new Set(),add=h=>{if(out.length>=MAX_HOLES||!h)return;const x=h.x??0,y=h.y??0,d=h.diameter??h.d??p.holeDiameter,key=`${x}|${y}|${d}`;if(!seen.has(key)){seen.add(key);out.push(`${x};${y};${d}`)}};(Array.isArray(p.holes)?p.holes:[]).forEach(add);if(p.centerHole!=null)add(typeof p.centerHole==="number"?{x:0,y:0,diameter:p.centerHole}:{x:0,y:0,diameter:p.centerHole.diameter??p.holeDiameter});for(const op of (Array.isArray(plan?.operations)?plan.operations:[])){if(op?.type==="hole")add(op);else if(op?.type==="holes"&&Array.isArray(op.holes))op.holes.forEach(add);if(out.length>=MAX_HOLES)break}return out.join("\n")}
 function planEditorValues(type,p={},plan){if(type==="adapter"){const id1=p.insideDiameter1??p.insideDiameter,id2=p.insideDiameter2??id1,wall=p.wall,baseOD=p.outsideDiameter,od1=p.outsideDiameter1??baseOD??(typeof id1==="number"&&typeof wall==="number"?id1+2*wall:undefined),od2=p.outsideDiameter2??baseOD??(typeof id2==="number"&&typeof wall==="number"?id2+2*wall:undefined);return{adapterLength:p.length,adapterID1:id1,adapterID2:id2,adapterOD1:od1,adapterOD2:od2}}if(type==="enclosure"){const wall=p.wall??p.thickness,floor=p.floorThickness??p.thickness??wall;return{enclosureW:p.width,enclosureD:p.length??p.depth,enclosureH:p.height,enclosureWall:wall,enclosureFloor:floor}}if(type==="plate"){const holes=plateHoleLines(plan),cr=p.cornerRadius??0,ch=p.chamfer??0;return{plateL:p.length,plateW:p.width,plateT:p.thickness,plateHolePattern:holes?"custom":"none",plateHoleD:0,plateHoleEdge:10,plateCornerStyle:cr>0?"round":ch>0?"chamfer":"square",plateCornerSize:cr||ch||0,plateCustomHoles:holes}}return null}
 function syncPlanToEditor(plan){if(!plan||plan.schemaVersion!==2)return;const type=({mountingPlate:"plate",box:"enclosure",case:"enclosure"})[plan.partType]||plan.partType;if(!(V2_TYPES.has(type)||type==="plate")||!plan.parameters||typeof plan.parameters!=="object"||Array.isArray(plan.parameters))return;const values=planEditorValues(type,plan.parameters,plan);if(!values)return;partType.value=type;if(type==="plate")showPlate();else show(type);resetMissingValues(type,values);if(type==="plate"&&$("plateCustomHoles"))$("plateCustomHoles").value=values.plateCustomHoles||"";const material=$("material");if(material&&MATERIALS.has(plan.material))material.value=plan.material}
 function ensurePlanSyncHook(){const v2=window.AI3DPlanV2CAD;if(!v2||typeof v2.apply!=="function")return false;if(v2.apply.__ai3dEditorSync===true)return true;const rawPlanApply=v2.apply.bind(v2),wrapped=plan=>{const result=rawPlanApply(plan);if(result&&typeof result.then==="function")return result.then(value=>{if(value!==false)syncPlanToEditor(plan);return value});if(result!==false)syncPlanToEditor(plan);return result};try{Object.defineProperty(wrapped,"__ai3dEditorSync",{value:true,configurable:false,enumerable:false,writable:false})}catch{wrapped.__ai3dEditorSync=true}v2.apply=wrapped;return true}
 ensurePlanSyncHook();
 function clearFailure(message){try{currentMesh=null;currentFitMesh=null}catch{}if($("status"))$("status").textContent="Virhe: "+message;if($("validation"))$("validation").innerHTML='<div class="check fail"><strong>✕ Tarkistus epäonnistui</strong><br>'+String(message).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))+'</div>';if($("btnDownload"))$("btnDownload").disabled=true;if($("btnFitTest"))$("btnFitTest").disabled=true;if($("btnCentauriStl"))$("btnCentauriStl").disabled=true;if($("dimensions"))$("dimensions").textContent="–";try{draw()}catch{}}
 function apply(type){try{if(!V2_TYPES.has(type))throw Error("CAD v2 -editori ei tunnista osatyyppiä.");show(type);if(!ensurePlanSyncHook())throw Error("CAD Plan v2 -generaattori ei latautunut.");window.AI3DPlanV2CAD.apply({schemaVersion:2,partType:type,material:$("material")?.value||DEFAULT_MATERIAL,parameters:parameters(type)});return true}catch(e){clearFailure(e?.message||"CAD-mallin generointi epäonnistui.");return false}}
 partType.onchange=()=>{if(V2_TYPES.has(partType.value))return apply(partType.value);restoreStandardUi();return oldChange?.call(partType)};
 btnGenerate.onclick=()=>V2_TYPES.has(partType.value)?apply(partType.value):oldGenerate?.call(btnGenerate);
 window.AI3D.setPart=(type,values={})=>{if(!V2_TYPES.has(type)){restoreStandardUi();return oldSetPart(type,values)}try{resetMaterial(values);partType.value=type;show(type);resetMissingValues(type,values);if(!apply(type))throw Error($("status")?.textContent||"CAD-mallin generointi epäonnistui.")}catch(e){const message=e?.message||"CAD-mallin generointi epäonnistui.";clearFailure(message);throw e}};
 window.AI3DV2Editor={types:[...V2_TYPES],apply,syncPlanToEditor,ensurePlanSyncHook};
})();
