"use strict";
(()=>{
 const el=id=>document.getElementById(id),N=64,HN=32;
 const num=(v,d=0)=>Number.isFinite(+v)?+v:d;
 const ring=(r,z,n=N)=>Array.from({length:n},(_,i)=>v(r*Math.cos(i*2*Math.PI/n),r*Math.sin(i*2*Math.PI/n),z));
 const rect=(w,d,z)=>[v(-w/2,-d/2,z),v(w/2,-d/2,z),v(w/2,d/2,z),v(-w/2,d/2,z)];
 function roundedRect(w,d,z,r,n=N){r=Math.max(0,Math.min(r,w/2-.1,d/2-.1));if(r<.001){const pts=rect(w,d,z),out=[];for(let s=0;s<4;s++){const a=pts[s],b=pts[(s+1)%4];for(let i=0;i<n/4;i++){const t=i/(n/4);out.push(v(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,z))}}return out}const out=[],per=n/4,c=[[w/2-r,-d/2+r,-Math.PI/2,0],[w/2-r,d/2-r,0,Math.PI/2],[-w/2+r,d/2-r,Math.PI/2,Math.PI],[-w/2+r,-d/2+r,Math.PI,1.5*Math.PI]];for(const[cx,cy,a0,a1]of c)for(let i=0;i<per;i++){const a=a0+(a1-a0)*i/per;out.push(v(cx+r*Math.cos(a),cy+r*Math.sin(a),z))}return out}
 function chamferRect(w,d,z,c,n=N){c=Math.max(0,Math.min(c,w/2-.1,d/2-.1));if(c<.001)return roundedRect(w,d,z,0,n);const p=[[-w/2+c,-d/2],[w/2-c,-d/2],[w/2,-d/2+c],[w/2,d/2-c],[w/2-c,d/2],[-w/2+c,d/2],[-w/2,d/2-c],[-w/2,-d/2+c]].map(([x,y])=>v(x,y,z)),out=[];let lengths=[],total=0;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],l=Math.hypot(b.x-a.x,b.y-a.y);lengths.push(l);total+=l}for(let k=0;k<n;k++){let target=total*k/n,idx=0;while(target>lengths[idx]&&idx<lengths.length-1){target-=lengths[idx++]}const a=p[idx],b=p[(idx+1)%p.length],t=lengths[idx]?target/lengths[idx]:0;out.push(v(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,z))}return out}
 function faceWithHoles(T,outer,holes,z,up){if(typeof earcut!=="function")throw Error("CAD-triangulointikirjasto ei latautunut.");const rings=[outer,...holes],flat=[],idx=[];let count=0;rings.forEach((r,i)=>{if(i)idx.push(count);for(const p of r){flat.push(p.x,p.y);count++}});const ids=earcut(flat,idx,2),all=rings.flat().map(p=>v(p.x,p.y,z));for(let i=0;i<ids.length;i+=3){const a=all[ids[i]],b=all[ids[i+1]],c=all[ids[i+2]];T.push(up?tri(a,b,c):tri(a,c,b))}}
 function finish(mesh){currentFitMesh=null;currentMesh=mesh;const a=validate(mesh);const ok=a.ok;el("validation").innerHTML=`<div class="check ${ok?"ok":"fail"}"><strong>${ok?"✓ Automaattitarkistus OK":"✕ Tarkistus epäonnistui"}</strong><br>${a.message}<br>Ei erillistä sovitustestiä.</div>`;el("btnDownload").disabled=!ok;el("btnFitTest").disabled=true;el("status").textContent=ok?"Malli luotu ja tarkistettu. Tarkista mitat ja näkymät ennen tulostusta.":"STL-lataus estetty virheen vuoksi.";el("dimensions").textContent=mesh.measure.map(([k,x])=>`${k} ${typeof x==="number"?x.toFixed(2)+" mm":x}`).join(" • ");updateMaterial();draw()}
 function buildAdapter(p){const L=num(p.length),id1=num(p.insideDiameter1,p.insideDiameter),id2=num(p.insideDiameter2,id1),wall=num(p.wall,0),od1=num(p.outsideDiameter1,p.outsideDiameter||id1+2*wall),od2=num(p.outsideDiameter2,p.outsideDiameter||id2+2*wall);if(L<=1||id1<=0||id2<=0||od1<=id1||od2<=id2)throw Error("Adapterin mitat eivät ole mahdollisia.");const o0=ring(od1/2,0),o1=ring(od2/2,L),i0=ring(id1/2,0),i1=ring(id2/2,L),T=[];bridge(T,o0,o1);bridge(T,i0,i1,true);annulus(T,o0,i0,false);annulus(T,o1,i1,true);return{triangles:T,name:"adapteri",width:Math.max(od1,od2),depth:Math.max(od1,od2),height:L,measure:[["Pituus",L],["Sisä Ø alku",id1],["Sisä Ø loppu",id2],["Ulko Ø alku",od1],["Ulko Ø loppu",od2]]}}
 function buildEnclosure(p){const W=num(p.width),D=num(p.length,p.depth),H=num(p.height),wall=num(p.wall,p.thickness),floor=num(p.floorThickness,p.thickness||wall);if(W<=4||D<=4||H<=4||wall<.6||floor<.6||W<=2*wall||D<=2*wall||H<=floor)throw Error("Kotelon mitat eivät ole mahdollisia.");const o0=rect(W,D,0),o1=rect(W,D,H),i0=rect(W-2*wall,D-2*wall,floor),i1=rect(W-2*wall,D-2*wall,H),T=[];bridge(T,o0,o1);bridge(T,i0,i1,true);cap(T,o0,0,false);cap(T,i0,floor,true);annulus(T,o1,i1,true);return{triangles:T,name:"kotelo",width:W,depth:D,height:H,measure:[["Leveys",W],["Pituus",D],["Korkeus",H],["Seinämä",wall],["Pohja",floor]]}}
 function buildPlateV2(p){const L=num(p.length),W=num(p.width),Th=num(p.thickness),cr=num(p.cornerRadius),ch=num(p.chamfer),style=cr>0?"round":ch>0?"chamfer":"square",size=cr||ch,outer0=style==="round"?roundedRect(L,W,0,size):style==="chamfer"?chamferRect(L,W,0,size):roundedRect(L,W,0,0);if(L<=2||W<=2||Th<.5)throw Error("Kiinnikelevyn mitat eivät ole mahdollisia.");let holes=[];if(p.centerHole){const d=typeof p.centerHole==="number"?p.centerHole:num(p.centerHole.diameter,p.holeDiameter);if(d>0)holes.push({x:0,y:0,diameter:d})}if(Array.isArray(p.holes))for(const h of p.holes)holes.push({x:num(h.x),y:num(h.y),diameter:num(h.diameter,p.holeDiameter)});const holeRings=[];for(const h of holes){if(h.diameter<=0)throw Error("Reiän halkaisija puuttuu.");if(Math.abs(h.x)+h.diameter/2>L/2+.0001||Math.abs(h.y)+h.diameter/2>W/2+.0001)throw Error("Reikä osuu levyn ulkopuolelle.");holeRings.push(ring(h.diameter/2,0,HN).map(q=>v(q.x+h.x,q.y+h.y,0)))}for(let i=0;i<holes.length;i++)for(let j=i+1;j<holes.length;j++)if(Math.hypot(holes[i].x-holes[j].x,holes[i].y-holes[j].y)<(holes[i].diameter+holes[j].diameter)/2+.4)throw Error("Levyn reiät menevät päällekkäin.");const outer1=outer0.map(q=>v(q.x,q.y,Th)),holes1=holeRings.map(r=>r.map(q=>v(q.x,q.y,Th))),T=[];faceWithHoles(T,outer0,holeRings,0,false);faceWithHoles(T,outer1,holes1,Th,true);bridge(T,outer0,outer1);for(let i=0;i<holeRings.length;i++)bridge(T,holeRings[i],holes1[i],true);const m=[["Pituus",L],["Leveys",W],["Paksuus",Th]];if(holes.length)m.push([`${holes.length} × reikä`,holes.map(h=>`Ø${h.diameter} @ ${h.x},${h.y}`).join("; ")]);if(cr)m.push(["Kulmapyöristys",cr]);if(ch)m.push(["Viiste",ch]);return{triangles:T,name:"kiinnikelevy",width:L,depth:W,height:Th,measure:m}}
 function apply(plan){const p=plan.parameters||{};if(plan.partType==="adapter")return finish(buildAdapter(p));if(plan.partType==="enclosure")return finish(buildEnclosure(p));if(plan.partType==="mountingPlate")return finish(buildPlateV2(p));throw Error("CAD Plan v2 -osatyyppiä ei tunnistettu.")}
 window.AI3DPlanV2CAD={apply};
})();