"use strict";
(()=>{
 const $=id=>document.getElementById(id),V2_TYPES=new Set(["adapter","enclosure"]),MAX_MM=5000;
 const partType=$("partType"),plateFields=$("fields-plate"),btnGenerate=$("btnGenerate");
 if(!partType||!plateFields||!btnGenerate||!window.AI3D)return;
 function addOption(value,label){if(partType.querySelector(`option[value="${value}"]`))return;const o=document.createElement("option");o.value=value;o.textContent=label;partType.appendChild(o)}
 addOption("adapter","Pyöreä adapteri / sovite");
 addOption("enclosure","Kotelo / rasia");
 if(!$("fields-adapter"))plateFields.insertAdjacentHTML("afterend",`<div id="fields-adapter" class="part-fields" hidden><div class="section-title">Pyöreä adapteri / sovite</div><div class="grid"><label>Pituus (mm)<input id="adapterLength" type="number" value="30" min="2" max="5000" step="0.5"></label><label>Sisä Ø alku (mm)<input id="adapterID1" type="number" value="20" min="0.1" max="5000" step="0.1"></label><label>Sisä Ø loppu (mm)<input id="adapterID2" type="number" value="20" min="0.1" max="5000" step="0.1"></label><label>Ulko Ø alku (mm)<input id="adapterOD1" type="number" value="26" min="0.1" max="5000" step="0.1"></label><label>Ulko Ø loppu (mm)<input id="adapterOD2" type="number" value="26" min="0.1" max="5000" step="0.1"></label></div></div><div id="fields-enclosure" class="part-fields" hidden><div class="section-title">Kotelo / rasia</div><div class="grid"><label>Leveys (mm)<input id="enclosureW" type="number" value="80" min="3" max="5000" step="0.5"></label><label>Pituus (mm)<input id="enclosureD" type="number" value="60" min="3" max="5000" step="0.5"></label><label>Korkeus (mm)<input id="enclosureH" type="number" value="30" min="3" max="5000" step="0.5"></label><label>Seinämä (mm)<input id="enclosureWall" type="number" value="2.4" min="0.8" max="5000" step="0.1"></label><label>Pohja (mm)<input id="enclosureFloor" type="number" value="2.4" min="0.8" max="5000" step="0.1"></label></div></div>`);
 const oldSetPart=window.AI3D.setPart.bind(window.AI3D),oldChange=partType.onchange,oldGenerate=btnGenerate.onclick;
 const readNum=id=>{const e=$(id),n=e?.valueAsNumber;if(!Number.isFinite(n))throw Error(`${id}: anna kelvollinen numero.`);const min=e?.min!==""?Number(e.min):NaN,max=e?.max!==""?Number(e.max):NaN;if(Number.isFinite(min)&&n<min)throw Error(`${id}: arvon pitää olla vähintään ${min} mm.`);if(Number.isFinite(max)&&n>max)throw Error(`${id}: arvo saa olla enintään ${max} mm.`);if(Math.abs(n)>MAX_MM)throw Error(`${id}: arvo saa olla enintään ${MAX_MM} mm.`);return n};
 function show(type){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);const f=$("fields-"+type);if(!f)throw Error("Osatyypin editoria ei löytynyt.");f.hidden=false;const titles={adapter:"Pyöreä adapteri / sovite",enclosure:"Kotelo / rasia"};if($("partTitle"))$("partTitle").textContent=titles[type]||type;if($("btnFitTest"))$("btnFitTest").style.display="none"}
 function restoreStandardUi(){const b=$("btnFitTest");if(b)b.style.display=""}
 function parameters(type){if(type==="adapter")return{length:readNum("adapterLength"),insideDiameter1:readNum("adapterID1"),insideDiameter2:readNum("adapterID2"),outsideDiameter1:readNum("adapterOD1"),outsideDiameter2:readNum("adapterOD2")};return{width:readNum("enclosureW"),length:readNum("enclosureD"),height:readNum("enclosureH"),wall:readNum("enclosureWall"),floorThickness:readNum("enclosureFloor")}}
 function resetMissingValues(type,values){const root=$("fields-"+type);if(!root)return;root.querySelectorAll("input[id],select[id]").forEach(e=>{const v=values?.[e.id];e.value=v!=null?v:e.defaultValue})}
 function clearFailure(message){try{currentMesh=null;currentFitMesh=null}catch{}if($("status"))$("status").textContent="Virhe: "+message;if($("validation"))$("validation").innerHTML='<div class="check fail"><strong>✕ Tarkistus epäonnistui</strong><br>'+String(message).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))+'</div>';if($("btnDownload"))$("btnDownload").disabled=true;if($("btnFitTest"))$("btnFitTest").disabled=true;if($("dimensions"))$("dimensions").textContent="–";try{draw()}catch{}}
 function apply(type){try{if(!V2_TYPES.has(type))throw Error("CAD v2 -editori ei tunnista osatyyppiä.");show(type);if(typeof window.AI3DPlanV2CAD?.apply!=="function")throw Error("CAD Plan v2 -generaattori ei latautunut.");window.AI3DPlanV2CAD.apply({schemaVersion:2,partType:type,material:$("material")?.value||"PETG",parameters:parameters(type)});return true}catch(e){clearFailure(e?.message||"CAD-mallin generointi epäonnistui.");return false}}
 partType.onchange=()=>{if(V2_TYPES.has(partType.value))return apply(partType.value);restoreStandardUi();return oldChange?.call(partType)};
 btnGenerate.onclick=()=>V2_TYPES.has(partType.value)?apply(partType.value):oldGenerate?.call(btnGenerate);
 window.AI3D.setPart=(type,values={})=>{if(!V2_TYPES.has(type)){restoreStandardUi();return oldSetPart(type,values)}partType.value=type;show(type);resetMissingValues(type,values);if(!apply(type))throw Error($("status")?.textContent||"CAD-mallin generointi epäonnistui.")};
 window.AI3DV2Editor={types:[...V2_TYPES],apply};
})();
