"use strict";
(()=>{
 const $=id=>document.getElementById(id);
 const PROFILE={name:"Elegoo Centauri Carbon 2 Combo",build:[256,256,256],comfortable:[250,250,250],nozzle:0.4,filament:1.75,recommendedLayer:0.2,formats:["STL","OBJ","3MF","STEP"],slicers:["ElegooSlicer","Orca","Cura"]};
 const materialTips={PLA:{layer:"0.20 mm",walls:"3",infill:"15–20 %",note:"Hyvä prototyyppeihin ja ensimmäisiin mittatesteihin."},PETG:{layer:"0.20 mm",walls:"4",infill:"25–35 %",note:"Hyvä mekaanisiin käyttöosiin. Tarkista sillat ja jäähdytys slicerin esikatselusta."},ASA:{layer:"0.20 mm",walls:"4–5",infill:"30–40 %",note:"Centauri Carbon 2 Combo tukee ASA:aa. Käytä suljettua rakennetta ja valmistajan/slicerin materiaaliprofiilia."}};
 function inject(){if($("centauriPanel"))return;const actions=document.querySelector(".actions");if(!actions)return;const box=document.createElement("div");box.id="centauriPanel";box.className="centauri-panel";box.innerHTML=`<div class="section-title">Centauri Carbon 2 Combo</div><div id="centauriStatus" class="printer-status"><b>Ei vielä mallia.</b><span>Luo 3D-malli ensin.</span></div><div class="centauri-actions"><button id="btnCentauriStl" class="primary" disabled>LATAA STL CENTAURIIN</button><button id="btnCentauriGuide" class="tool">LATAA ASETUSOHJE</button></div><small class="centauri-note">3D Studio tarkistaa koon ja mesh-validoinnin. Avaa STL slicerissa ja tarkista vielä orientaatio, tuet sekä ensimmäinen kerros ennen tulostusta.</small>`;actions.after(box)}
 function mesh(){try{return currentMesh||null}catch{return null}}
 function meshOk(){return !$("btnDownload")?.disabled}
 function status(){const root=$("centauriStatus");if(!root)return;const m=mesh();if(!m){root.className="printer-status";root.innerHTML='<b>Ei vielä mallia.</b><span>Luo 3D-malli ensin.</span>';if($("btnCentauriStl"))$("btnCentauriStl").disabled=true;return}const dims=[+m.width||0,+m.depth||0,+m.height||0],finite=dims.every(Number.isFinite),positive=dims.every(x=>x>0),fits=finite&&positive&&dims.every((x,i)=>x<=PROFILE.build[i]),comfortable=fits&&dims.every((x,i)=>x<=PROFILE.comfortable[i]),mat=$("material")?.value||"PETG",tip=materialTips[mat]||materialTips.PETG,valid=meshOk();root.className="printer-status "+(fits&&valid?"ok":"fail");let title,extra="";if(!finite||!positive)title="✕ Mallin mittoja ei voitu tarkistaa";else if(!fits)title="✕ Malli ylittää Centaurin tulostusalueen";else if(!valid)title="✕ Mesh-tarkistus ei ole vielä hyväksytty";else if(!comfortable){title="✓ Mahtuu tulostusalueelle";extra="<span>⚠ Malli on lähellä 256 mm rajaa. Tarkista slicerissa skirt/brim ja todellinen sijoittelu erityisen huolellisesti.</span>"}else title="✓ Sopii Centauri Carbon 2 -tulostusalueelle";root.innerHTML=`<b>${title}</b><span>Malli ${dims.map(x=>x.toFixed(1)).join(" × ")} mm • alue ${PROFILE.build.join(" × ")} mm</span>${extra}<span>${mat}: kerros ${tip.layer}, seinät ${tip.walls}, täyttö ${tip.infill}. ${tip.note}</span><span>0,4 mm suutin • 1,75 mm filamentti • suosituskerros 0,20 mm.</span>`;if($("btnCentauriStl"))$("btnCentauriStl").disabled=!(fits&&valid)}
 function downloadGuide(){const m=mesh(),mat=$("material")?.value||"PETG",tip=materialTips[mat]||materialTips.PETG,p=window.AI3DProjects?.active?.(),dims=m?[+m.width||0,+m.depth||0,+m.height||0].map(x=>x.toFixed(1)).join(" x "):"ei mallia";const text=["3D Studio – Elegoo Centauri Carbon 2 Combo",`Projekti: ${p?.name||m?.name||"3D-malli"}`,`Mallin mitat: ${dims} mm`,`Tulostusalue: ${PROFILE.build.join(" x ")} mm`,`Suutin: ${PROFILE.nozzle} mm`,`Filamentti: ${PROFILE.filament} mm`,`Yhteensopiva vienti tästä sovelluksesta: STL`,`Slicer: ElegooSlicer, Orca tai Cura`,`Materiaali: ${mat}`,`Kerros: ${tip.layer}`,`Seinät: ${tip.walls}`,`Täyttö: ${tip.infill}`,tip.note,"","TARKISTUS ENNEN TULOSTUSTA","1. Avaa STL slicerissa.","2. Tarkista orientaatio ja mahdolliset tuet.","3. Tarkista ensimmäisen kerroksen esikatselu.","4. Tarkista että brim/skirt ja koko kappale ovat tulostusalueella.","5. Käytä materiaalille sopivaa Centauri Carbon 2 -profiilia."].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download="centauri-carbon-2-tulostusohje.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function init(){inject();$("btnCentauriStl")?.addEventListener("click",()=>$("btnDownload")?.click());$("btnCentauriGuide")?.addEventListener("click",downloadGuide);$("btnGenerate")?.addEventListener("click",()=>setTimeout(status,50));$("material")?.addEventListener("change",status);const obs=new MutationObserver(status);if($("dimensions"))obs.observe($("dimensions"),{childList:true,subtree:true,characterData:true});if($("validation"))obs.observe($("validation"),{childList:true,subtree:true,characterData:true});setTimeout(status,250)}
 window.CentauriProfile={...PROFILE,check:status};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();