"use strict";
(()=>{
 if(!document.querySelector('script[data-ai3d-plan-preflight],script[src^="plan_preflight.js"]')){const s=document.createElement("script");s.src="plan_preflight.js?v=1.3";s.dataset.ai3dPlanPreflight="1";document.head.appendChild(s)}
 if(!document.querySelector('script[data-ai3d-operation-guard],script[src^="plan_operation_guard.js"]')){const s=document.createElement("script");s.src="plan_operation_guard.js?v=1.3";s.dataset.ai3dOperationGuard="1";document.head.appendChild(s)}
 if(!document.querySelector('script[data-ai3d-preview-guard],script[src^="preview_guard.js"]')){const s=document.createElement("script");s.src="preview_guard.js?v=1.0";s.dataset.ai3dPreviewGuard="1";document.head.appendChild(s)}
 const $=id=>document.getElementById(id);
 const views=[
  {id:"current",name:"Nykyinen asento",rot:p=>({x:p.x,y:p.y,z:p.z})},
  {id:"x90",name:"Kyljelleen X +90°",rot:p=>({x:p.x,y:-p.z,z:p.y})},
  {id:"x-90",name:"Kyljelleen X −90°",rot:p=>({x:p.x,y:p.z,z:-p.y})},
  {id:"y90",name:"Kyljelleen Y +90°",rot:p=>({x:p.z,y:p.y,z:-p.x})},
  {id:"y-90",name:"Kyljelleen Y −90°",rot:p=>({x:-p.z,y:p.y,z:p.x})},
  {id:"flip",name:"Ylösalaisin 180°",rot:p=>({x:p.x,y:-p.y,z:-p.z})}
 ];
 function mesh(){try{if($("btnDownload")?.disabled)return null;return currentMesh||null}catch{return null}}
 function transformed(m,rot){const tris=(m?.triangles||[]).map(t=>t.map(q=>rot(q)));if(!tris.length)return null;let minZ=Infinity;for(const t of tris)for(const q of t)minZ=Math.min(minZ,q.z);if(!Number.isFinite(minZ))return null;for(const t of tris)for(const q of t)q.z-=minZ;return{...m,triangles:tris}}
 function stability(dims,pa){const w=+dims?.[0]||0,d=+dims?.[1]||0,h=+dims?.[2]||0,short=Math.min(w,d),ratio=short>0?h/short:Infinity,bedPct=Number.isFinite(pa?.bedFootprintPct)?pa.bedFootprintPct:0;let level="ok",penalty=0,note="vakaa lähtökohta";if(!Number.isFinite(ratio)){level="high";penalty=40;note="vakautta ei voitu arvioida"}else if((ratio>5&&bedPct<8)||(ratio>8&&bedPct<15)){level="high";penalty=30+Math.min(25,ratio*2);note="korkea/hoikka ja pieni pohjakosketus"}else if((ratio>3&&bedPct<15)||ratio>6){level="medium";penalty=14+Math.min(15,ratio);note="melko hoikka tulostusasento"}else if(bedPct<2&&h>20){level="medium";penalty=16;note="pieni pohjakosketus"}return{level,penalty,ratio,bedPct,note}}
 function scoreResult(r){if(!r?.fits)return 1e9;const pa=r.printability||{},st=r.stability||{},over=Number.isFinite(pa.overhangPct)?pa.overhangPct:50,bed=Number.isFinite(pa.bedArea)?pa.bedArea:0,height=r.dims?.[2]||0,foot=(r.dims?.[0]||0)*(r.dims?.[1]||0),bedRatio=foot>0?Math.min(1,bed/foot):0,marginPenalty=r.comfortable?0:18;return over*2.2+(1-bedRatio)*24+Math.max(0,height-180)*.06+(st.penalty||0)+marginPenalty}
 function analyse(){const m=mesh(),api=window.CentauriProfile;if(!m||!api?.bounds||!api?.printability)return[];const build=Array.isArray(api.build)&&api.build.length===3?api.build:[256,256,256],comfortable=Array.isArray(api.comfortable)&&api.comfortable.length===3?api.comfortable:build.map(x=>Math.max(0,x-6));return views.map(v=>{const tm=transformed(m,v.rot),b=api.bounds(tm),dims=b?.dims||[0,0,0],fits=dims.every((x,i)=>Number.isFinite(x)&&x>0&&x<=build[i]+1e-6),comfort=fits&&dims.every((x,i)=>x<=comfortable[i]+1e-6),pa=b?api.printability(tm,b):null,st=stability(dims,pa),r={...v,dims,fits,comfortable:comfort,printability:pa,stability:st,build,comfortableBuild:comfortable};r.score=scoreResult(r);return r}).sort((a,b)=>a.score-b.score)}
 function inject(){if($("centauriOrientation"))return;const panel=$("centauriPanel");if(!panel)return;const box=document.createElement("div");box.id="centauriOrientation";box.style.marginTop="10px";box.innerHTML='<button id="btnCompareOrientation" class="tool" type="button">VERTAA TULOSTUSASENTOJA</button><div id="orientationResult" class="printer-status" style="margin-top:8px"><span>Asentojen vertailu ei muuta STL-tiedostoa. Se antaa vain suosituksen sliceriin.</span></div>';panel.appendChild(box);$("btnCompareOrientation").onclick=render}
 function render(){inject();const root=$("orientationResult");if(!root)return;const rows=analyse();if(!rows.length){root.innerHTML=$("btnDownload")?.disabled?"<span>Luo hyväksytty 3D-malli ensin. Virheellistä tai vanhaa mesh-tulosta ei käytetä asentojen vertailussa.</span>":"<span>Luo ja hyväksy 3D-malli ensin.</span>";return}const best=rows[0],current=rows.find(x=>x.id==="current"),improvement=current&&best.id!=="current"?current.score-best.score:0,build=best.build||[256,256,256];let title;if(!best.fits)title=`✕ Yksikään tarkastettu asento ei mahdu ${build.join(" × ")} mm tulostusalueelle`;else if(best.id==="current"||improvement<3)title="✓ Nykyinen asento on vertailussa hyvä lähtökohta";else title=`ℹ Slicerissa kannattaa kokeilla: ${best.name}`;const detail=rows.slice(0,3).map((r,i)=>{const pa=r.printability,st=r.stability,margin=r.fits&&!r.comfortable?" • lähellä tulostusalueen rajaa":"",stab=st?.level==="high"?` • ⚠ ${st.note}`:st?.level==="medium"?` • huomio: ${st.note}`:"";return `<span>${i+1}. ${r.name} • ${r.fits?"mahtuu":"ei mahdu"} • ${r.dims.map(x=>x.toFixed(1)).join(" × ")} mm${pa?` • jyrkät pinnat ${pa.overhangPct.toFixed(1)} % • pohja ${pa.bedArea.toFixed(1)} mm²`:""}${margin}${stab}</span>`}).join("");const bestWarn=best.stability?.level==="high"?"<span>⚠ Paras geometrinen asento näyttää silti hoikalta tai heikosti alustaan tukeutuvalta. Harkitse brim:iä, tukia tai hitaampia liikkeitä korkeissa kerroksissa slicerissa.</span>":"";root.className="printer-status "+(best.fits?"ok":"fail");root.innerHTML=`<b>${title}</b>${detail}${bestWarn}<span>Vertailu huomioi 250 mm mukavuusrajan sekä suuntaa-antavan hoikkuus- ja pohjakosketusriskin. Vertailuun pääsee vain nykyinen mesh, jonka 3D Studion mesh-tarkistus on hyväksynyt. Tämä on geometrinen arvio: 3D Studio ei kierrä ladattavaa STL:ää automaattisesti; tee mahdollinen kääntö ElegooSlicerissa, Orcassa tai Curassa ja tarkista tuet sekä ensimmäinen kerros.</span>`}
 function refresh(){inject();const root=$("orientationResult");if(root)root.innerHTML="<span>Asentojen vertailu ei muuta STL-tiedostoa. Paina VERTAA TULOSTUSASENTOJA uuden hyväksytyn mallin luonnin jälkeen.</span>"}
 function init(){let tries=0;const t=setInterval(()=>{tries++;inject();if($("centauriPanel")||tries>40)clearInterval(t)},100);$("btnGenerate")?.addEventListener("click",()=>setTimeout(refresh,120));document.addEventListener("change",e=>{if(e.target?.id==="material")refresh()})}
 window.CentauriOrientation={analyse,render,stability};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();