"use strict";
(()=>{
 const el=id=>document.getElementById(id), num=(id,d)=>Number.isFinite(+el(id)?.value)?+el(id).value:d;
 const oldSetPart=window.AI3D?.setPart, oldPartChange=el("partType")?.onchange, oldGenerate=el("btnGenerate")?.onclick, oldDownload=el("btnDownload")?.onclick;
 const polyCircle=(r,n=64,a0=0,a1=Math.PI*2)=>Array.from({length:n+1},(_,i)=>{const a=a0+(a1-a0)*i/n;return[r*Math.cos(a),r*Math.sin(a)]});
 function extrudePoly(poly,h,z0=0){const flat=[];poly.forEach(p=>flat.push(p[0],p[1]));const ids=earcut(flat,null,2),bot=poly.map(p=>v(p[0],p[1],z0)),top=poly.map(p=>v(p[0],p[1],z0+h)),T=[];for(let i=0;i<ids.length;i+=3){const a=ids[i],b=ids[i+1],c=ids[i+2];T.push(tri(top[a],top[b],top[c]));T.push(tri(bot[c],bot[b],bot[a]))}for(let i=0;i<poly.length;i++){const j=(i+1)%poly.length;T.push(tri(bot[i],bot[j],top[j]),tri(bot[i],top[j],top[i]))}return T}
 function sector(r0,r1,a0,a1,h,z0=0,n=28){const out=polyCircle(r1,n,a0,a1),inn=polyCircle(r0,n,a0,a1).reverse();return extrudePoly(out.concat(inn),h,z0)}
 function diskSector(r,a0,a1,h,z0=0,n=28){const p=[[0,0],...polyCircle(r,n,a0,a1)];return extrudePoly(p,h,z0)}
 function move(T,dx=0,dy=0,dz=0){return T.map(t=>t.map(q=>v(q.x+dx,q.y+dy,q.z+dz)))}
 function rot(T,a){const c=Math.cos(a),s=Math.sin(a);return T.map(t=>t.map(q=>v(q.x*c-q.y*s,q.x*s+q.y*c,q.z)))}
 function part(name,triangles,w,d,h,measure=[]){return{triangles,name,width:w,depth:d,height:h,measure}}
 function params(){const D=num("signDiameter",400), ring=num("signRingWidth",28), depth=num("signDepth",24), wall=num("signWall",2.4), diff=num("diffuserThickness",1.2), starW=num("starWidth",28), starT=num("starThickness",4), ledW=num("ledWidth",10);if(D<120||ring<12||ring>=D/3||depth<12||wall<1.6||diff<.8)throw Error("Valokyltin mitat eivät ole mahdollisia.");return{D,R:D/2,ring,inner:D/2-ring,depth,wall,diff,starW,starT,ledW}}
 function housingQuarter(p,q){const a0=q*Math.PI/2,a1=(q+1)*Math.PI/2,T=[];T.push(...sector(p.inner,p.R,a0,a1,p.wall,0));T.push(...sector(p.R-p.wall,p.R,a0,a1,p.depth-p.wall,p.wall*.72));T.push(...sector(p.inner,p.inner+p.wall,a0,a1,p.depth-p.wall,p.wall*.72));return part(`runko_q${q+1}`,T,p.R,p.R,p.depth)}
 function bezelQuarter(p,q){const a0=q*Math.PI/2,a1=(q+1)*Math.PI/2;return part(`etukehys_q${q+1}`,sector(p.inner,p.R,a0,a1,3,0),p.R,p.R,3)}
 function diffuserQuarter(p,q){const a0=q*Math.PI/2,a1=(q+1)*Math.PI/2;return part(`diffuusori_q${q+1}`,diskSector(p.inner-2,a0,a1,p.diff,0),p.inner,p.inner,p.diff)}
 function starArm(p){const L=p.inner-12,hub=18,w0=p.starW/2,w1=Math.max(7,p.starW*.22),poly=[[hub,-w0],[L,-w1],[L,w1],[hub,w0]];return part("tahti_sakara",extrudePoly(poly,p.starT,0),L,p.starW,p.starT)}
 function hub(p){const poly=polyCircle(20,48,0,Math.PI*2).slice(0,-1);return part("tahti_keskio",extrudePoly(poly,p.starT,0),40,40,p.starT)}
 function joiner(){return part("liitoslevy",boxMesh(46,18,3),46,18,3)}
 function printableParts(p){const out=[];for(let q=0;q<4;q++){out.push(housingQuarter(p,q),bezelQuarter(p,q),diffuserQuarter(p,q))}out.push(starArm(p),hub(p),joiner());return out}
 function buildPreview(p){let T=[];for(let q=0;q<4;q++)T.push(...housingQuarter(p,q).triangles);for(let q=0;q<4;q++)T.push(...move(diffuserQuarter(p,q).triangles,0,0,p.depth));for(let q=0;q<4;q++)T.push(...move(bezelQuarter(p,q).triangles,0,0,p.depth+p.diff));const arm=starArm(p).triangles;for(const a of[-Math.PI/2,Math.PI/6,5*Math.PI/6])T.push(...move(rot(arm,a),0,0,p.depth+p.diff+3));T.push(...move(hub(p).triangles,0,0,p.depth+p.diff+3));return part("valokyltti_400_esikatselu",T,p.D,p.D,p.depth+p.diff+3+p.starT,[["Halkaisija",p.D],["Kehä",p.ring],["Syvyys",p.depth],["Diffuusori",p.diff],["LED-nauha",(2*Math.PI*(p.inner-5)/1000).toFixed(2)+" m"]])}
 function estimate(p){const rho=1.27, back=Math.PI*(p.R*p.R-p.inner*p.inner)*p.wall, outer=2*Math.PI*(p.R-p.wall/2)*p.wall*(p.depth-p.wall), inner=2*Math.PI*(p.inner+p.wall/2)*p.wall*(p.depth-p.wall), bezel=Math.PI*(p.R*p.R-p.inner*p.inner)*3, diffuser=Math.PI*(p.inner-2)*(p.inner-2)*p.diff, armArea=((p.starW+Math.max(14,p.starW*.44))/2)*(p.inner-30), stars=armArea*p.starT*3, hubV=Math.PI*20*20*p.starT, joins=46*18*3*4, volume=(back+outer+inner+bezel+diffuser+stars+hubV+joins)/1000, grams=volume*rho, filament=grams/1000*num("filamentPriceKg",20), total=filament+num("ledCost",25.5)+num("powerCost",12)+num("miscCost",5);return{grams,filament,total,ledLen:2*Math.PI*(p.inner-5)/1000}}
 function showFields(){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);el("fields-lightSign").hidden=false;el("partTitle").textContent="Valokyltti 400 mm";el("btnFitTest").style.display="none";el("btnDownload").textContent="LATAA KAIKKI STL-OSAT"}
 function customGenerate(){try{const p=params();showFields();currentFitMesh=null;currentMesh=buildPreview(p);const parts=printableParts(p),bad=parts.filter(x=>!validate(x).ok);const e=estimate(p);el("validation").innerHTML=`<div class="check ${bad.length?"fail":"ok"}"><strong>${bad.length?"✕ Osatarkistus epäonnistui":"✓ Kaikki tulostusosat tarkistettu"}</strong><br>${parts.length} STL-tiedostotyyppiä. Rungon, etukehyksen ja diffuusorin neljännekset mahtuvat 256 × 256 mm pedille.</div>`;el("btnDownload").disabled=!!bad.length;el("status").textContent=bad.length?"Korjaa mitat ennen vientiä.":"Valokyltti valmis STL-vientiin. Tulosta sakara 3 kpl ja liitoslevy 4 kpl.";el("dimensions").textContent=currentMesh.measure.map(([k,x])=>`${k} ${typeof x==="number"?x.toFixed(2)+" mm":x}`).join(" • ");el("costEstimate").innerHTML=`Arvioitu filamentti <b>${Math.round(e.grams)} g</b> (noin ${e.filament.toFixed(2)} €) • LED-nauhaa noin <b>${e.ledLen.toFixed(2)} m</b> • koko projektin tarvikearvio noin <b>${e.total.toFixed(2)} €</b>.`;updateMaterial();draw()}catch(err){el("status").textContent="Virhe: "+err.message;el("btnDownload").disabled=true}}
 function downloadParts(){const p=params(),parts=printableParts(p);parts.forEach((m,i)=>{let file=`${m.name}.stl`;if(m.name==="tahti_sakara")file="tahti_sakara_TULOSTA_3_KPL.stl";if(m.name==="liitoslevy")file="liitoslevy_TULOSTA_4_KPL.stl";setTimeout(()=>saveMesh(m,file),i*300)})}
 if(!oldSetPart)return;
 window.AI3D.setPart=(type,values={})=>{if(type!=="lightSign")return oldSetPart(type,values);el("partType").value="lightSign";for(const[k,x]of Object.entries(values))if(el(k))el(k).value=x;customGenerate()};
 window.AI3D.generate=()=>el("partType").value==="lightSign"?customGenerate():oldGenerate?.();
 el("partType").onchange=()=>{if(el("partType").value==="lightSign")customGenerate();else{el("btnDownload").textContent="LATAA STL";oldPartChange?.()}};
 el("btnGenerate").onclick=()=>el("partType").value==="lightSign"?customGenerate():oldGenerate?.();
 el("btnDownload").onclick=()=>el("partType").value==="lightSign"?downloadParts():oldDownload?.();
 customGenerate();
})();
