"use strict";
(()=>{
 const $=id=>document.getElementById(id), KEY="ai3d:projects:v3";
 let selected="assembly", lastSnapshot=null, centauriWrapped=false;
 const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const fmt=x=>Number.isFinite(+x)?(+x).toFixed(1):"–";
 function isLightSign(){return $("partType")?.value==="lightSign"&&!!window.AI3DLightSign}
 function getSnapshot(){try{return isLightSign()?window.AI3DLightSign.snapshot():null}catch{return null}}
 function partFits(m){const b=window.CentauriProfile?.bounds?.(m);const dims=b?.dims||[+m.width||0,+m.depth||0,+m.height||0];return dims.every((x,i)=>Number.isFinite(x)&&x>0&&x<=256+1e-6)}
 function partValid(m){try{return typeof validate==="function"&&validate(m).ok&&partFits(m)}catch{return false}}
 function metaParts(s){return s.parts.map((m,i)=>({id:`part-${i}`,name:m.name,quantity:m.quantity||1,material:m.material||s.material||"PETG",dimensions:[+m.width||0,+m.depth||0,+m.height||0],printable:partValid(m)}))}
 function persistMetadata(s){const active=window.AI3DProjects?.active?.();if(!active||active.type!=="lightSign")return;const parts=metaParts(s);active.multipart=true;active.parts=parts;active.assembly={name:s.assembly.name,dimensions:[s.assembly.width,s.assembly.depth,s.assembly.height],previewOnly:true};try{const raw=localStorage.getItem(KEY),arr=JSON.parse(raw||"[]");if(!Array.isArray(arr))return;const i=arr.findIndex(p=>p?.id===active.id);if(i<0)return;localStorage.setItem(KEY+":backup",raw||"[]");arr[i]={...arr[i],multipart:true,parts,assembly:active.assembly,updated:Date.now()};localStorage.setItem(KEY,JSON.stringify(arr))}catch{}}
 function inject(){if($("multipartPanel"))return;const preview=document.querySelector(".preview-panel");if(!preview)return;const box=document.createElement("section");box.id="multipartPanel";box.className="multipart-panel";box.hidden=true;box.innerHTML=`<div class="multipart-head"><div><div class="section-title">Tulostettavat osat</div><small>Kokoonpano on vain esikatselu. Centauri-tarkistus tehdään jokaiselle osalle erikseen.</small></div><button id="btnMultipartAll" class="primary">LATAA KAIKKI OSAT</button></div><div id="multipartSummary" class="multipart-summary"></div><div id="multipartList" class="multipart-list"></div>`;preview.appendChild(box);$("btnMultipartAll").onclick=()=>window.AI3DLightSign?.downloadAll?.()}
 function assemblyStatus(s){const good=s.parts.filter(partValid).length,all=s.parts.length,root=$("centauriStatus");if(!root)return;root.className="printer-status "+(good===all?"ok":"fail");root.innerHTML=`<b>${good===all?"✓ Kokoonpanon kaikki tulostusosat mahtuvat Centauriin":"✕ Yksi tai useampi tulostusosa ei läpäise tarkistusta"}</b><span>Kokoonpanon kokonaiskoko ${fmt(s.assembly.width)} × ${fmt(s.assembly.depth)} × ${fmt(s.assembly.height)} mm on vain esikatselutieto eikä sitä verrata 256 mm tulostusalueeseen.</span><span>Osakohtainen tulos: ${good}/${all} STL-osatyyppiä hyväksytty.</span>`;if($("btnCentauriStl"))$("btnCentauriStl").disabled=true}
 function wrapCentauri(){if(centauriWrapped||!window.CentauriProfile?.check)return;const old=window.CentauriProfile.check;window.CentauriProfile.check=()=>{if(isLightSign()&&selected==="assembly"&&lastSnapshot)return assemblyStatus(lastSnapshot);return old()};centauriWrapped=true}
 function selectAssembly(){const s=getSnapshot();if(!s)return;selected="assembly";lastSnapshot=s;currentMesh=s.assembly;$("dimensions").textContent=s.assembly.measure.map(([k,x])=>`${k} ${typeof x==="number"?x.toFixed(2)+" mm":x}`).join(" • ");draw();render();setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 function selectPart(i){const s=getSnapshot(),m=s?.parts?.[i];if(!m)return;selected=`part-${i}`;lastSnapshot=s;currentMesh=m;$("dimensions").textContent=`${m.name} • ${fmt(m.width)} × ${fmt(m.depth)} × ${fmt(m.height)} mm • ${m.material} • määrä ${m.quantity||1}`;draw();render();setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 function downloadPart(i){const s=getSnapshot(),m=s?.parts?.[i];if(!m||!partValid(m))return;const q=m.quantity||1,file=q>1?`${m.name}_TULOSTA_${q}_KPL.stl`:`${m.name}.stl`;saveMesh(m,file)}
 function render(){inject();wrapCentauri();const panel=$("multipartPanel");if(!panel)return;if(!isLightSign()){panel.hidden=true;selected="assembly";lastSnapshot=null;return}const s=getSnapshot();if(!s){panel.hidden=true;return}lastSnapshot=s;panel.hidden=false;persistMetadata(s);const rows=s.parts.map((m,i)=>{const ok=partValid(m);return`<div class="multipart-row ${selected===`part-${i}`?"active":""}"><button class="multipart-select" data-part="${i}"><b>${esc(m.name)}</b><span>${m.quantity||1} kpl • ${esc(m.material||s.material)} • ${fmt(m.width)} × ${fmt(m.depth)} × ${fmt(m.height)} mm</span></button><span class="multipart-fit ${ok?"ok":"fail"}">${ok?"✓ Tulostuskelpoinen":"✕ Tarkista"}</span><button class="multipart-download" data-download="${i}" ${ok?"":"disabled"}>STL</button></div>`}).join("");$("multipartSummary").innerHTML=`<button id="btnAssemblyPreview" class="multipart-assembly ${selected==="assembly"?"active":""}"><b>KOKOONPANOESIKATSELU</b><span>${fmt(s.assembly.width)} × ${fmt(s.assembly.depth)} × ${fmt(s.assembly.height)} mm • ei tulosteta yhtenä kappaleena</span></button>`;$("multipartList").innerHTML=rows;$("btnAssemblyPreview").onclick=selectAssembly;$("multipartList").querySelectorAll("[data-part]").forEach(b=>b.onclick=()=>selectPart(+b.dataset.part));$("multipartList").querySelectorAll("[data-download]").forEach(b=>b.onclick=e=>{e.stopPropagation();downloadPart(+b.dataset.download)});if(selected==="assembly")setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 window.AI3DMultiPart={render,selectAssembly,selectPart,isAssemblySelected:()=>selected==="assembly",snapshot:()=>lastSnapshot};
 window.addEventListener("ai3d:multipart-updated",()=>setTimeout(()=>{selected="assembly";render()},30));
 document.addEventListener("DOMContentLoaded",()=>setTimeout(render,350));
})();
