"use strict";
(()=>{
 const $=id=>document.getElementById(id), KEY="ai3d:projects:v3";
 let selected="assembly", lastSnapshot=null, centauriWrapped=false, centauriDownloadBound=false;
 const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const fmt=x=>Number.isFinite(+x)?(+x).toFixed(1):"–";
 function isLightSign(){return $("partType")?.value==="lightSign"&&!!window.AI3DLightSign}
 function getSnapshot(){try{return isLightSign()?window.AI3DLightSign.snapshot():null}catch{return null}}
 function partFits(m){const b=window.CentauriProfile?.bounds?.(m);const dims=b?.dims||[+m.width||0,+m.depth||0,+m.height||0];return dims.every((x,i)=>Number.isFinite(x)&&x>0&&x<=256+1e-6)}
 function partValid(m){try{if(typeof window.AI3DLightSign?.isPrintable==="function")return window.AI3DLightSign.isPrintable(m);const meshIssue=window.AI3DMeshIntegrity?.inspect?.(m)||"";return !meshIssue&&typeof validate==="function"&&validate(m).ok&&partFits(m)}catch{return false}}
 function metaParts(s){return s.parts.map((m,i)=>({id:`part-${i}`,name:m.name,quantity:m.quantity||1,material:m.material||s.material||"PETG",dimensions:[+m.width||0,+m.depth||0,+m.height||0],printable:partValid(m)}))}
 function persistMetadata(s){const active=window.AI3DProjects?.active?.();if(!active||active.type!=="lightSign")return;const parts=metaParts(s),assembly={name:s.assembly.name,dimensions:[s.assembly.width,s.assembly.depth,s.assembly.height],previewOnly:true};active.multipart=true;active.parts=parts;active.assembly=assembly;try{const raw=localStorage.getItem(KEY),arr=JSON.parse(raw||"[]");if(!Array.isArray(arr))return;const i=arr.findIndex(p=>p?.id===active.id);if(i<0)return;const old=arr[i],same=old?.multipart===true&&JSON.stringify(old.parts||[])===JSON.stringify(parts)&&JSON.stringify(old.assembly||{})===JSON.stringify(assembly);if(same)return;arr[i]={...old,multipart:true,parts,assembly};localStorage.setItem(KEY,JSON.stringify(arr))}catch{}}
 function injectStyles(){if($("multipartStyles"))return;const s=document.createElement("style");s.id="multipartStyles";s.textContent=`.multipart-panel{margin-top:16px;padding:14px;border:1px solid #334155;border-radius:14px;background:#0b1220}.multipart-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.multipart-head .section-title{margin:0 0 4px}.multipart-head small{color:#94a3b8}.multipart-summary{margin-top:12px}.multipart-assembly{width:100%;display:flex;flex-direction:column;align-items:flex-start;gap:4px;text-align:left;background:#111827;border:1px solid #334155}.multipart-assembly.active,.multipart-row.active{border-color:#14b8a6;background:#052e2b}.multipart-assembly span,.multipart-select span{font-size:12px;color:#94a3b8}.multipart-list{display:grid;gap:7px;margin-top:9px}.multipart-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center;padding:8px;border:1px solid #263244;border-radius:10px;background:#111827}.multipart-select{display:flex;flex-direction:column;align-items:flex-start;gap:3px;min-width:0;padding:4px;background:transparent;text-align:left}.multipart-fit{font-size:11px;font-weight:800;white-space:nowrap}.multipart-fit.ok{color:#5eead4}.multipart-fit.fail{color:#fca5a5}.multipart-download{padding:8px 10px}.multipart-panel[hidden]{display:none!important}@media(max-width:650px){.multipart-head{display:grid}.multipart-row{grid-template-columns:1fr auto}.multipart-fit{grid-column:1}.multipart-download{grid-column:2;grid-row:1 / span 2}}`;document.head.appendChild(s)}
 function downloadAll(){const s=getSnapshot();if(!s||s.parts.some(m=>!partValid(m)))return;window.AI3DLightSign?.downloadAll?.()}
 function inject(){injectStyles();if($("multipartPanel"))return;const preview=document.querySelector(".preview-panel");if(!preview)return;const box=document.createElement("section");box.id="multipartPanel";box.className="multipart-panel";box.hidden=true;box.innerHTML=`<div class="multipart-head"><div><div class="section-title">Tulostettavat osat</div><small>Kokoonpano on vain esikatselu. Centauri-tarkistus tehdään jokaiselle osalle erikseen.</small></div><button id="btnMultipartAll" class="primary">LATAA KAIKKI OSAT</button></div><div id="multipartSummary" class="multipart-summary"></div><div id="multipartList" class="multipart-list"></div>`;preview.appendChild(box);$("btnMultipartAll").onclick=downloadAll}
 function setOrientationMode(){const b=$("btnCompareOrientation"),r=$("orientationResult");if(!b)return;if(isLightSign()&&selected==="assembly"){b.disabled=true;b.title="Valitse tulostettava osa ennen asentovertailua.";if(r)r.innerHTML="<span>Kokoonpanoa ei tulosteta yhtenä kappaleena. Valitse osalistasta tulostettava osa, niin asentovertailu tehdään sille erikseen.</span>"}else{b.disabled=false;b.title=""}}
 function assemblyStatus(s){const good=s.parts.filter(partValid).length,all=s.parts.length,root=$("centauriStatus");if(!root)return;root.className="printer-status "+(good===all?"ok":"fail");root.innerHTML=`<b>${good===all?"✓ Kokoonpanon kaikki tulostusosat mahtuvat Centauriin":"✕ Yksi tai useampi tulostusosa ei läpäise tarkistusta"}</b><span>Kokoonpanon kokonaiskoko ${fmt(s.assembly.width)} × ${fmt(s.assembly.depth)} × ${fmt(s.assembly.height)} mm on vain esikatselutieto eikä sitä verrata 256 mm tulostusalueeseen.</span><span>Osakohtainen tulos: ${good}/${all} STL-osatyyppiä hyväksytty.</span>`;if($("btnCentauriStl"))$("btnCentauriStl").disabled=true;setOrientationMode()}
 function wrapCentauri(){if(centauriWrapped||!window.CentauriProfile?.check)return;const old=window.CentauriProfile.check;window.CentauriProfile.check=()=>{if(isLightSign()&&selected==="assembly"&&lastSnapshot)return assemblyStatus(lastSnapshot);const x=old();setOrientationMode();return x};centauriWrapped=true}
 function selectAssembly(){const s=getSnapshot();if(!s)return;selected="assembly";lastSnapshot=s;currentMesh=s.assembly;$("dimensions").textContent=s.assembly.measure.map(([k,x])=>`${k} ${typeof x==="number"?x.toFixed(2)+" mm":x}`).join(" • ");draw();render();setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 function selectPart(i){const s=getSnapshot(),m=s?.parts?.[i];if(!m)return;selected=`part-${i}`;lastSnapshot=s;currentMesh=m;$("dimensions").textContent=`${m.name} • ${fmt(m.width)} × ${fmt(m.depth)} × ${fmt(m.height)} mm • ${m.material} • määrä ${m.quantity||1}`;draw();render();setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 function downloadPart(i){const s=getSnapshot(),m=s?.parts?.[i];if(!m||!partValid(m))return false;const q=m.quantity||1,file=q>1?`${m.name}_TULOSTA_${q}_KPL.stl`:`${m.name}.stl`;saveMesh(m,file);return true}
 function bindCentauriDownload(){const b=$("btnCentauriStl");if(!b||centauriDownloadBound)return;b.addEventListener("click",e=>{if(!isLightSign()||selected==="assembly"||!selected.startsWith("part-"))return;const i=+selected.slice(5);e.preventDefault();e.stopImmediatePropagation();downloadPart(i)},true);centauriDownloadBound=true}
 function ensureCentauriIntegration(){let tries=0;const tick=()=>{tries++;wrapCentauri();bindCentauriDownload();if(centauriWrapped&&centauriDownloadBound){setTimeout(()=>window.CentauriProfile?.check?.(),0);return}if(tries<50)setTimeout(tick,100)};tick()}
 function render(){inject();wrapCentauri();bindCentauriDownload();const panel=$("multipartPanel");if(!panel)return;if(!isLightSign()){panel.hidden=true;selected="assembly";lastSnapshot=null;setOrientationMode();return}const s=getSnapshot();if(!s){panel.hidden=true;return}lastSnapshot=s;panel.hidden=false;persistMetadata(s);const valid=s.parts.map(partValid),rows=s.parts.map((m,i)=>{const ok=valid[i];return`<div class="multipart-row ${selected===`part-${i}`?"active":""}"><button class="multipart-select" data-part="${i}"><b>${esc(m.name)}</b><span>${m.quantity||1} kpl • ${esc(m.material||s.material)} • ${fmt(m.width)} × ${fmt(m.depth)} × ${fmt(m.height)} mm</span></button><span class="multipart-fit ${ok?"ok":"fail"}">${ok?"✓ Tulostuskelpoinen":"✕ Tarkista"}</span><button class="multipart-download" data-download="${i}" ${ok?"":"disabled"}>STL</button></div>`}).join("");$("multipartSummary").innerHTML=`<button id="btnAssemblyPreview" class="multipart-assembly ${selected==="assembly"?"active":""}"><b>KOKOONPANOESIKATSELU</b><span>${fmt(s.assembly.width)} × ${fmt(s.assembly.depth)} × ${fmt(s.assembly.height)} mm • ei tulosteta yhtenä kappaleena</span></button>`;$("multipartList").innerHTML=rows;$("btnAssemblyPreview").onclick=selectAssembly;$("multipartList").querySelectorAll("[data-part]").forEach(b=>b.onclick=()=>selectPart(+b.dataset.part));$("multipartList").querySelectorAll("[data-download]").forEach(b=>b.onclick=e=>{e.stopPropagation();downloadPart(+b.dataset.download)});const all=$("btnMultipartAll");if(all)all.disabled=valid.some(ok=>!ok);setOrientationMode();if(selected==="assembly")setTimeout(()=>window.CentauriProfile?.check?.(),20)}
 window.AI3DMultiPart={render,selectAssembly,selectPart,isAssemblySelected:()=>selected==="assembly",snapshot:()=>lastSnapshot};
 window.addEventListener("ai3d:multipart-updated",()=>setTimeout(()=>{selected="assembly";render()},30));
 ensureCentauriIntegration();
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(render,350));else setTimeout(render,100);
})();
