"use strict";
(()=>{
 const $=id=>document.getElementById(id),num=(x,d=0)=>Number.isFinite(+x)?+x:d,N=64;
 const isExtra=()=>["adapter","enclosure"].includes($("partType")?.value);
 function ring(r,z){return Array.from({length:N},(_,i)=>v(r*Math.cos(i*2*Math.PI/N),r*Math.sin(i*2*Math.PI/N),z))}
 function rect(w,d,z){return [v(-w/2,-d/2,z),v(w/2,-d/2,z),v(w/2,d/2,z),v(-w/2,d/2,z)]}
 function inject(){
  const sel=$("partType");if(!sel)return;
  if(!sel.querySelector('option[value="adapter"]')){const o=document.createElement("option");o.value="adapter";o.textContent="Pyöreä adapteri / supistus";sel.appendChild(o)}
  if(!sel.querySelector('option[value="enclosure"]')){const o=document.createElement("option");o.value="enclosure";o.textContent="Avoin kotelo";sel.appendChild(o)}
  const anchor=$("fields-plate")?.parentElement;if(!anchor)return;
  if(!$("fields-adapter")){const s=document.createElement("div");s.id="fields-adapter";s.className="part-fields";s.hidden=true;s.innerHTML='<div class="section-title">Adapteri / supistus</div><div class="grid"><label>Pituus (mm)<input id="adapterLength" type="number" value="40" min="2" step="0.5"></label><label>Sisä Ø alku (mm)<input id="adapterID1" type="number" value="20" min="1" step="0.1"></label><label>Sisä Ø loppu (mm)<input id="adapterID2" type="number" value="30" min="1" step="0.1"></label><label>Ulko Ø alku (mm)<input id="adapterOD1" type="number" value="26" min="2" step="0.1"></label><label>Ulko Ø loppu (mm)<input id="adapterOD2" type="number" value="36" min="2" step="0.1"></label></div><p class="hint">Sisä- ja ulkohalkaisijat voivat muuttua eri tahtiin. Malli muodostaa suljetun kartiomaisen holkin.</p>';anchor.insertBefore(s,$("fields-plate").nextSibling)}
  if(!$("fields-enclosure")){const s=document.createElement("div");s.id="fields-enclosure";s.className="part-fields";s.hidden=true;s.innerHTML='<div class="section-title">Avoin kotelo</div><div class="grid"><label>Leveys (mm)<input id="enclosureW" type="number" value="80" min="6" step="0.5"></label><label>Pituus (mm)<input id="enclosureD" type="number" value="120" min="6" step="0.5"></label><label>Korkeus (mm)<input id="enclosureH" type="number" value="40" min="6" step="0.5"></label><label>Seinämä (mm)<input id="enclosureWall" type="number" value="2.4" min="0.8" step="0.1"></label><label>Pohjan paksuus (mm)<input id="enclosureFloor" type="number" value="2.4" min="0.8" step="0.1"></label></div><p class="hint">Avoin suorakulmainen kotelo. Pohja ja neljä seinää muodostetaan yhdeksi suljetuksi STL-meshiksi.</p>';anchor.insertBefore(s,$("fields-plate").nextSibling)}
 }
 function showFields(type){document.querySelectorAll(".part-fields").forEach(x=>x.hidden=true);const panel=$("fields-"+type);if(!panel)throw Error("Osatyypin muokkauskenttiä ei löytynyt.");panel.hidden=false;$("partTitle").textContent=type==="adapter"?"Pyöreä adapteri / supistus":"Avoin kotelo";$("btnFitTest").style.display="none"}
 function finish(mesh){currentFitMesh=null;currentMesh=mesh;const a=validate(mesh),ok=a.ok;$("validation").innerHTML=`<div class="check ${ok?"ok":"fail"}"><strong>${ok?"✓ Automaattitarkistus OK":"✕ Tarkistus epäonnistui"}</strong><br>${a.message}<br>Ei erillistä sovitustestiä.</div>`;$("btnDownload").disabled=!ok;$("btnFitTest").disabled=true;$("status").textContent=ok?"Parametrinen malli luotu ja tarkistettu.":"STL-lataus estetty virheen vuoksi.";$("dimensions").textContent=mesh.measure.map(([k,x])=>`${k} ${typeof x==="number"?x.toFixed(2)+" mm":x}`).join(" • ");updateMaterial();draw();setTimeout(()=>window.CentauriProfile?.check?.(),30)}
 function buildAdapter(){const L=num($("adapterLength").value),id1=num($("adapterID1").value),id2=num($("adapterID2").value),od1=num($("adapterOD1").value),od2=num($("adapterOD2").value);if(L<2||id1<=0||id2<=0||od1<=id1+.8||od2<=id2+.8)throw Error("Adapterin mitat eivät ole mahdollisia. Ulkohalkaisijan pitää olla sisähalkaisijaa suurempi.");const o0=ring(od1/2,0),o1=ring(od2/2,L),i0=ring(id1/2,0),i1=ring(id2/2,L),T=[];bridge(T,o0,o1);bridge(T,i0,i1,true);annulus(T,o0,i0,false);annulus(T,o1,i1,true);return{triangles:T,name:"adapteri",width:Math.max(od1,od2),depth:Math.max(od1,od2),height:L,measure:[["Pituus",L],["Sisä Ø alku",id1],["Sisä Ø loppu",id2],["Ulko Ø alku",od1],["Ulko Ø loppu",od2]]}}
 function buildEnclosure(){const W=num($("enclosureW").value),D=num($("enclosureD").value),H=num($("enclosureH").value),wall=num($("enclosureWall").value),floor=num($("enclosureFloor").value);if(W<=2*wall+2||D<=2*wall+2||H<=floor+2||wall<.8||floor<.8)throw Error("Kotelon mitat eivät ole mahdollisia.");const o0=rect(W,D,0),o1=rect(W,D,H),i0=rect(W-2*wall,D-2*wall,floor),i1=rect(W-2*wall,D-2*wall,H),T=[];bridge(T,o0,o1);bridge(T,i0,i1,true);cap(T,o0,0,false);cap(T,i0,floor,true);annulus(T,o1,i1,true);return{triangles:T,name:"avoin_kotelo",width:W,depth:D,height:H,measure:[["Leveys",W],["Pituus",D],["Korkeus",H],["Seinämä",wall],["Pohja",floor]]}}
 function generateExtra(){try{const type=$("partType").value;if(type!=="adapter"&&type!=="enclosure")return;showFields(type);finish(type==="adapter"?buildAdapter():buildEnclosure())}catch(e){$("status").textContent="Virhe: "+e.message;$("btnDownload").disabled=true;$("validation").innerHTML='<div class="check fail"><strong>✕ Tarkistus epäonnistui</strong><br>'+String(e.message||e)+'</div>'}}
 function setExtra(type,values={}){showFields(type);const keys=type==="adapter"?["adapterLength","adapterID1","adapterID2","adapterOD1","adapterOD2"]:["enclosureW","enclosureD","enclosureH","enclosureWall","enclosureFloor"];for(const k of keys)if($(k)&&values[k]!=null)$(k).value=values[k];if(values.material&&$("material"))$("material").value=values.material;generateExtra()}
 function init(){inject();const oldSet=window.AI3D?.setPart;if(oldSet)window.AI3D.setPart=(type,values={})=>{if(type!=="adapter"&&type!=="enclosure")return oldSet(type,values);$("partType").value=type;setExtra(type,values)};const typeEl=$("partType"),oldChange=typeEl?.onchange;if(typeEl)typeEl.onchange=()=>{if(isExtra())generateExtra();else oldChange?.()};$("btnGenerate")?.addEventListener("click",e=>{if(!isExtra())return;e.preventDefault();e.stopImmediatePropagation();generateExtra()},true)}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
 window.AI3DParametric={generate:generateExtra};
})();