"use strict";
(()=>{
 const $=id=>document.getElementById(id),MAX_OPS=200,MAX_HOLES=200;
 const supportedV2=new Set(["sleeve","spike","endPlug","mountingPlate","adapter","enclosure"]);
 const supportedV1=new Set(["sleeve","spike","plug","plate"]);
 const materials=new Set(["PLA","PETG","ASA"]);
 const positive=v=>Number.isFinite(Number(v))&&Number(v)>0;
 const finite=v=>Number.isFinite(Number(v));
 const nonNegative=v=>Number.isFinite(Number(v))&&Number(v)>=0;
 const safeScalar=v=>v===null||["string","number","boolean"].includes(typeof v);
 let lastResult=null,running=true;
 function fingerprint(raw){try{return JSON.stringify(raw)}catch{return null}}
 function checkMagnitude(obj,warnings){for(const[k,x]of Object.entries(obj||{}))if(typeof x==="number"&&Math.abs(x)>1000)warnings.push(k+" on poikkeuksellisen suuri.")}
 function checkFlatValues(v,errors){if(!v||typeof v!=="object"||Array.isArray(v))return;const entries=Object.entries(v);if(entries.length>100)errors.push("values sisältää liian monta arvoa.");for(const[k,x]of entries){if(["__proto__","prototype","constructor"].includes(k)){errors.push("values sisältää kielletyn avaimen: "+k+".");continue}if(!safeScalar(x))errors.push("values."+k+" sisältää tukemattoman rakenteen.");else if(typeof x==="number"&&!Number.isFinite(x))errors.push("values."+k+" ei ole kelvollinen luku.");else if(typeof x==="string"&&x.length>20000)errors.push("values."+k+" on liian pitkä.")}}
 function validateV1(raw){
  const errors=[],warnings=[],v=raw.values;
  if(raw.status!=null&&!["ready","approved"].includes(raw.status))errors.push("status pitää olla ready tai approved.");
  if(raw.material!=null&&!materials.has(raw.material))errors.push("Materiaali pitää olla PLA, PETG tai ASA.");
  if(raw.material==null&&v?.material!=null&&!materials.has(v.material))errors.push("values.material pitää olla PLA, PETG tai ASA.");
  if(!supportedV1.has(raw.partType))errors.push("Schema v1 -osatyyppiä ei tueta.");
  if(!v||typeof v!=="object"||Array.isArray(v))errors.push("values-objekti puuttuu.");
  checkFlatValues(v,errors);
  if(v&&raw.partType==="spike"){
   if(!positive(v.nutAf))errors.push("nutAf puuttuu tai ei ole positiivinen luku.");
   if(!positive(v.wall))errors.push("wall puuttuu tai ei ole positiivinen luku.");
   if(!positive(v.totalHeight))errors.push("totalHeight puuttuu tai ei ole positiivinen luku.");
   if(positive(v.baseHeight)&&positive(v.totalHeight)&&Number(v.baseHeight)>=Number(v.totalHeight))errors.push("baseHeight pitää olla kokonaiskorkeutta pienempi.");
   if(v.clearance!=null&&!nonNegative(v.clearance))errors.push("clearance ei voi olla negatiivinen.");
   if(v.lockAmount!=null&&!nonNegative(v.lockAmount))errors.push("lockAmount ei voi olla negatiivinen.");
   if(positive(v.lockZ)&&positive(v.baseHeight)&&Number(v.lockZ)>=Number(v.baseHeight))warnings.push("lockZ on mutteriosan korkeudella tai sen yläpuolella; tarkista lukituskohta.");
   if(v.monogram!=null){const mark=String(v.monogram).trim().toUpperCase();if(mark!=="M")errors.push("Tässä versiossa spike-monogrammina tuetaan vain M-kirjainta.");else{if(!positive(v.monogramWidth))errors.push("M-muoto tarvitsee positiivisen monogramWidth-arvon.");if(!positive(v.monogramDepth))errors.push("M-muoto tarvitsee positiivisen monogramDepth-arvon.");if(!positive(v.monogramHeight))errors.push("M-muoto tarvitsee positiivisen monogramHeight-arvon.");if(positive(v.baseHeight)&&positive(v.totalHeight)&&Number(v.totalHeight)<=Number(v.baseHeight)+18)errors.push("M-piikkimutterisuojuksen kokonaiskorkeuden pitää olla yli 18 mm mutteriosaa korkeampi.");if(positive(v.monogramHeight)&&positive(v.baseHeight)&&positive(v.totalHeight)&&Number(v.monogramHeight)>Number(v.totalHeight)-Number(v.baseHeight))errors.push("monogramHeight ei saa ulottua mutteriosan alapuolelle.");if(positive(v.lockZ)&&positive(v.baseHeight)&&Number(v.lockZ)>=Number(v.baseHeight))errors.push("M-piikissä lockZ pitää olla mutteriosan korkeuden alapuolella.")}}
  }
  if(v&&raw.partType==="sleeve"){
   if(!positive(v.sleeveID??v.insideDiameter))errors.push("Holkin sisähalkaisija puuttuu.");
   if(!positive(v.sleeveWall??v.wall))errors.push("Holkin seinämä puuttuu.");
   if(!positive(v.sleeveLength??v.length))errors.push("Holkin pituus puuttuu.")
  }
  if(v&&raw.partType==="plug"){
   const W=v.tubeW??v.width,H=v.tubeH??v.height,wall=v.tubeWall??v.wall,clear=v.plugClear??v.clearance??0,depth=v.insertDepth,cap=v.capThickness??v.thickness;
   if(!positive(W))errors.push("Tulpan leveys puuttuu.");if(!positive(H))errors.push("Tulpan korkeus puuttuu.");if(!positive(wall))errors.push("Tulpan seinämä puuttuu.");if(!positive(depth))errors.push("Tulpan upotussyvyys puuttuu.");if(!positive(cap))errors.push("Tulpan päätylevyn paksuus puuttuu.");if(!nonNegative(clear))errors.push("Tulpan sovitusvälys ei voi olla negatiivinen.");if(positive(W)&&positive(wall)&&nonNegative(clear)&&Number(W)-2*Number(wall)-2*Number(clear)<=2)errors.push("Tulpan sisäleveys jää liian pieneksi seinämän ja välyksen jälkeen.");if(positive(H)&&positive(wall)&&nonNegative(clear)&&Number(H)-2*Number(wall)-2*Number(clear)<=2)errors.push("Tulpan sisäkorkeus jää liian pieneksi seinämän ja välyksen jälkeen.")
  }
  if(v&&raw.partType==="plate"){
   if(!positive(v.plateL??v.length))errors.push("Levyn pituus puuttuu.");if(!positive(v.plateW??v.width))errors.push("Levyn leveys puuttuu.");if(!positive(v.plateT??v.thickness))errors.push("Levyn paksuus puuttuu.");if(v.plateCornerSize!=null&&!nonNegative(v.plateCornerSize))errors.push("Levyn pyöristys/viiste ei voi olla negatiivinen.")
  }
  checkMagnitude(v,warnings);return{ok:errors.length===0,errors,warnings,schema:1}
 }
 function collectHoles(raw){const holes=[];const add=h=>{if(holes.length>=MAX_HOLES)return;if(!h)return;if(typeof h==="number"){holes.push({x:0,y:0,diameter:h});return}holes.push({x:h.x??0,y:h.y??0,diameter:h.diameter??h.d})};const p=raw.parameters||{};(Array.isArray(p.holes)?p.holes.slice(0,MAX_HOLES):[]).forEach(add);if(p.centerHole)add(p.centerHole);for(const op of (Array.isArray(raw.operations)?raw.operations:[]).slice(0,MAX_OPS)){if(op?.type==="hole")add(op);if(op?.type==="holes"&&Array.isArray(op.holes))op.holes.slice(0,MAX_HOLES).forEach(add);if(holes.length>=MAX_HOLES)break}return holes}
 function checkOperationBudget(raw,errors){const p=raw.parameters||{},ops=Array.isArray(raw.operations)?raw.operations:[];if(Array.isArray(p.holes)&&p.holes.length>MAX_HOLES)errors.push(`parameters.holes sisältää yli ${MAX_HOLES} reikää.`);if(ops.length>MAX_OPS)errors.push(`operations sisältää yli ${MAX_OPS} operaatiota.`);let total=Array.isArray(p.holes)?p.holes.length:0;if(p.centerHole)total++;for(const op of ops.slice(0,MAX_OPS+1)){if(op?.type==="hole")total++;if(op?.type==="holes"&&Array.isArray(op.holes)){if(op.holes.length>MAX_HOLES)errors.push(`Yksi holes-operaatio sisältää yli ${MAX_HOLES} reikää.`);total+=op.holes.length}if(total>MAX_HOLES)break}if(total>MAX_HOLES)errors.push(`Suunnitelmassa on yhteensä yli ${MAX_HOLES} reikää.`)}
 function validateV2(raw){
  const errors=[],warnings=[];
  if(!["ready","approved"].includes(raw.status))errors.push("status pitää olla ready tai approved.");
  if(!supportedV2.has(raw.partType))errors.push("Osatyyppiä ei tueta Schema v2:ssa.");
  if(!materials.has(raw.material))errors.push("Materiaali pitää olla PLA, PETG tai ASA.");
  const p=raw.parameters;if(!p||typeof p!=="object"||Array.isArray(p))errors.push("parameters-objekti puuttuu.");
  if(raw.operations!=null&&!Array.isArray(raw.operations))errors.push("operations pitää olla taulukko.");
  if(Array.isArray(raw.operations)&&raw.operations.length>MAX_OPS)errors.push(`operations sisältää yli ${MAX_OPS} operaatiota.`);
  if(p&&typeof p==="object"){
   const need=k=>{if(!positive(p[k]))errors.push(k+" puuttuu tai ei ole positiivinen luku.")};
   if(raw.partType==="mountingPlate"){need("length");need("width");need("thickness");const cr=p.cornerRadius??0,ch=p.chamfer??0;if(!nonNegative(cr)||!nonNegative(ch))errors.push("Kiinnikelevyn cornerRadius/chamfer ei voi olla negatiivinen.");if(positive(cr)&&positive(ch))errors.push("Kiinnikelevylle ei voi käyttää cornerRadius- ja chamfer-arvoa yhtä aikaa.");if(positive(p.length)&&positive(p.width)){const maxCorner=Math.min(Number(p.length),Number(p.width))/2;if(Number(cr)>=maxCorner||Number(ch)>=maxCorner)errors.push("Kiinnikelevyn cornerRadius/chamfer on liian suuri levyn mittoihin nähden.")}checkOperationBudget(raw,errors);const holes=collectHoles(raw);holes.forEach((h,i)=>{if(!finite(h.x)||!finite(h.y)||!positive(h.diameter))errors.push(`Reikä ${i+1}: x, y ja positiivinen diameter vaaditaan.`);else if(positive(p.length)&&positive(p.width)&&(Math.abs(Number(h.x))+Number(h.diameter)/2>Number(p.length)/2||Math.abs(Number(h.y))+Number(h.diameter)/2>Number(p.width)/2))warnings.push(`Reikä ${i+1} näyttää osuvan levyn ulkoreunaan tai sen yli.`)})}
   if(raw.partType==="sleeve"){need("insideDiameter");need("length");if(!positive(p.wall)&&!positive(p.outsideDiameter))errors.push("Holkki tarvitsee wall- tai outsideDiameter-arvon.");if(positive(p.outsideDiameter)&&positive(p.insideDiameter)&&Number(p.outsideDiameter)<=Number(p.insideDiameter))errors.push("outsideDiameter pitää olla insideDiameter-arvoa suurempi.")}
   if(raw.partType==="spike"){const af=p.nutAcrossFlats??p.nutAf,h=p.height??p.totalHeight;if(!positive(af))errors.push("Piikkimutterin avainkoko puuttuu.");if(!positive(p.wall))errors.push("wall puuttuu.");if(!positive(h))errors.push("Kokonaiskorkeus puuttuu.");if(positive(p.baseHeight)&&positive(h)&&Number(p.baseHeight)>=Number(h))errors.push("baseHeight pitää olla kokonaiskorkeutta pienempi.");if(p.clearance!=null&&!nonNegative(p.clearance))errors.push("clearance ei voi olla negatiivinen.");if(p.lockAmount!=null&&!nonNegative(p.lockAmount))errors.push("lockAmount ei voi olla negatiivinen.");if(positive(p.lockZ)&&positive(p.baseHeight)&&Number(p.lockZ)>=Number(p.baseHeight))warnings.push("lockZ on mutteriosan korkeudella tai sen yläpuolella; tarkista lukituskohta.");if(p.monogram!=null){const mark=String(p.monogram).trim().toUpperCase();if(mark!=="M")errors.push("Schema v2 spike-monogrammina tuetaan tässä versiossa vain M-kirjainta.");else{if(!positive(p.monogramWidth))errors.push("Schema v2 M-muoto tarvitsee monogramWidth-arvon.");if(!positive(p.monogramDepth))errors.push("Schema v2 M-muoto tarvitsee monogramDepth-arvon.");if(!positive(p.monogramHeight))errors.push("Schema v2 M-muoto tarvitsee monogramHeight-arvon.");if(positive(p.baseHeight)&&positive(h)&&Number(h)<=Number(p.baseHeight)+18)errors.push("Schema v2 M-piikin kokonaiskorkeuden pitää olla yli 18 mm mutteriosaa korkeampi.");if(positive(p.monogramHeight)&&positive(p.baseHeight)&&positive(h)&&Number(p.monogramHeight)>Number(h)-Number(p.baseHeight))errors.push("Schema v2 monogramHeight ei saa ulottua mutteriosan alapuolelle.");if(positive(p.lockZ)&&positive(p.baseHeight)&&Number(p.lockZ)>=Number(p.baseHeight))errors.push("Schema v2 M-piikissä lockZ pitää olla mutteriosan korkeuden alapuolella.")}}}
   if(raw.partType==="endPlug"){need("width");need("height");need("wall");need("insertDepth");const clear=p.clearance??.25,cap=p.capThickness??p.thickness??3;if(!nonNegative(clear))errors.push("Tulpan clearance ei voi olla negatiivinen.");if(!positive(cap))errors.push("Tulpan capThickness/thickness puuttuu tai ei ole positiivinen.");if(positive(p.width)&&positive(p.wall)&&nonNegative(clear)&&Number(p.width)-2*Number(p.wall)-2*Number(clear)<=2)errors.push("Tulpan sisäleveys jää liian pieneksi wall- ja clearance-arvojen jälkeen.");if(positive(p.height)&&positive(p.wall)&&nonNegative(clear)&&Number(p.height)-2*Number(p.wall)-2*Number(clear)<=2)errors.push("Tulpan sisäkorkeus jää liian pieneksi wall- ja clearance-arvojen jälkeen.")}
   if(raw.partType==="adapter"){need("length");const id1=p.insideDiameter1??p.insideDiameter,id2=p.insideDiameter2??p.insideDiameter??id1,wall=Number(p.wall||0),od1=p.outsideDiameter1??p.outsideDiameter,od2=p.outsideDiameter2??p.outsideDiameter;if(!positive(id1))errors.push("Adapterin sisähalkaisija puuttuu.");if(!positive(id2))errors.push("Adapterin loppupään sisähalkaisija puuttuu.");if(!positive(od1)&&!(wall>0))errors.push("Adapterin alku tarvitsee outsideDiameter1/outsideDiameter- tai wall-arvon.");if(!positive(od2)&&!(wall>0))errors.push("Adapterin loppu tarvitsee outsideDiameter2/outsideDiameter- tai wall-arvon.");if(positive(od1)&&positive(id1)&&Number(od1)<=Number(id1))errors.push("Adapterin outsideDiameter1 pitää olla insideDiameter1-arvoa suurempi.");if(positive(od2)&&positive(id2)&&Number(od2)<=Number(id2))errors.push("Adapterin outsideDiameter2 pitää olla insideDiameter2-arvoa suurempi.")}
   if(raw.partType==="enclosure"){need("width");need("height");if(!positive(p.length)&&!positive(p.depth))errors.push("Kotelon length/depth puuttuu.");const d=p.length??p.depth,wall=p.wall??p.thickness,floor=p.floorThickness??p.thickness??p.wall;if(!positive(wall))errors.push("Kotelon wall/thickness puuttuu.");if(!positive(floor))errors.push("Kotelon floorThickness/thickness puuttuu.");if(positive(p.width)&&positive(wall)&&Number(p.width)<=2*Number(wall)+2)errors.push("Kotelon leveys on liian pieni seinämäpaksuuteen nähden.");if(positive(d)&&positive(wall)&&Number(d)<=2*Number(wall)+2)errors.push("Kotelon pituus/syvyys on liian pieni seinämäpaksuuteen nähden.");if(positive(p.height)&&positive(floor)&&Number(p.height)<=Number(floor)+2)errors.push("Kotelon korkeus on liian pieni pohjan paksuuteen nähden.")}
   checkMagnitude(p,warnings)
  }
  return{ok:errors.length===0,errors:[...new Set(errors)],warnings:[...new Set(warnings)],schema:2}
 }
 function validate(raw){if(!raw||typeof raw!=="object"||Array.isArray(raw))return{ok:false,errors:["Suunnitelma ei ole JSON-objekti."],warnings:[],schema:null};if(typeof raw.projectName!=="string"||!raw.projectName.trim())return{ok:false,errors:["Projektin nimi puuttuu."],warnings:[],schema:raw.schemaVersion};if(raw.projectName.length>120)return{ok:false,errors:["Projektin nimi on liian pitkä (enintään 120 merkkiä)."],warnings:[],schema:raw.schemaVersion};if(raw.summary!=null&&typeof raw.summary!=="string")return{ok:false,errors:["summary pitää olla tekstiä."],warnings:[],schema:raw.schemaVersion};if(typeof raw.summary==="string"&&raw.summary.length>5000)return{ok:false,errors:["summary on liian pitkä."],warnings:[],schema:raw.schemaVersion};if(raw.schemaVersion===1)return validateV1(raw);if(raw.schemaVersion===2)return validateV2(raw);return{ok:false,errors:["Tuntematon schemaVersion."],warnings:[],schema:raw.schemaVersion}}
 function gate(){const b=document.querySelector('[data-plan="chatgpt-current"]');if(!b)return;const ok=!running&&lastResult?.ok===true;b.disabled=!ok;b.classList.toggle("unsupported",!ok);if(ok)b.removeAttribute("title");else b.title=running?"Suunnitelman ennakkotarkistus on kesken.":"Suunnitelma on estetty, koska ennakkotarkistus löysi virheitä."}
 async function run(){let box=$("planPreflight");if(!box){const side=document.querySelector(".project-sidebar");if(!side)return;box=document.createElement("div");box.id="planPreflight";box.style.margin="8px 0";box.style.padding="9px";box.style.border="1px solid #334155";box.style.borderRadius="10px";side.appendChild(box)}running=true;lastResult=null;box.textContent="⏳ Tarkistetaan ChatGPT-suunnitelmaa…";gate();try{const r=await fetch("chatgpt_plan.json?preflight="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const raw=await r.json(),checked=validate(raw);lastResult={...checked,fingerprint:fingerprint(raw)};running=false;box.textContent=lastResult.ok?(lastResult.warnings.length?`✓ Schema v${lastResult.schema} -suunnitelman rakenne OK. `+lastResult.warnings.join(" "):`✓ ChatGPT-suunnitelman rakenne OK (Schema v${lastResult.schema}).`):"⚠ ChatGPT-suunnitelma estetty: "+lastResult.errors.join(" ");gate()}catch(e){running=false;lastResult={ok:false,errors:[String(e?.message||e)],warnings:[],schema:null,fingerprint:null};box.textContent="⚠ Suunnitelman ennakkotarkistus ei onnistunut: "+lastResult.errors[0];gate()}}
 function resetForRefresh(){running=true;lastResult=null;gate();setTimeout(run,350)}
 function init(){const list=$("planList");if(list)new MutationObserver(gate).observe(list,{childList:true,subtree:true});run();document.addEventListener("click",e=>{if(e.target&&e.target.id==="btnReloadPlans")resetForRefresh()})}
 window.AI3DPlanPreflight={validate,run,getLastResult:()=>lastResult};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();