"use strict";
(()=>{
 const $=id=>document.getElementById(id);
 const support={mountingPlate:new Set(["hole","holes"]),sleeve:new Set(),spike:new Set(),endPlug:new Set(),adapter:new Set(),enclosure:new Set()};
 let running=true,last={ok:false,errors:["Tarkistus ei ole vielä valmis."],fingerprint:null};
 const finite=v=>Number.isFinite(Number(v));
 const positive=v=>finite(v)&&Number(v)>0;
 function fingerprint(raw){try{return JSON.stringify(raw)}catch{return null}}
 function plateHoles(raw){const out=[];const add=(h,label)=>{if(!h||typeof h!=="object"||Array.isArray(h)){out.push({invalid:true,label});return}out.push({x:Number(h.x??0),y:Number(h.y??0),d:Number(h.diameter??h.d),label})};for(const op of raw.operations||[]){if(op?.type==="hole")add(op,"hole");if(op?.type==="holes"&&Array.isArray(op.holes))op.holes.forEach((h,i)=>add(h,`holes ${i+1}`))}return out}
 function validatePlateGeometry(raw,errors,warnings){const p=raw.parameters||{},L=Number(p.length),W=Number(p.width),holes=plateHoles(raw);if(!positive(L)||!positive(W))return;for(let i=0;i<holes.length;i++){const h=holes[i];if(h.invalid||!finite(h.x)||!finite(h.y)||!positive(h.d)){errors.push(`Reikä ${i+1}: x, y ja positiivinen diameter vaaditaan.`);continue}const r=h.d/2;if(Math.abs(h.x)+r>L/2||Math.abs(h.y)+r>W/2)errors.push(`Reikä ${i+1} (Ø${h.d}) ulottuu levyn ulkopuolelle.`);else if(Math.abs(h.x)+r+0.6>L/2||Math.abs(h.y)+r+0.6>W/2)warnings.push(`Reikä ${i+1} on alle 0,6 mm levyn reunasta.`)}for(let i=0;i<holes.length;i++)for(let j=i+1;j<holes.length;j++){const a=holes[i],b=holes[j];if(a.invalid||b.invalid||![a.x,a.y,a.d,b.x,b.y,b.d].every(Number.isFinite)||a.d<=0||b.d<=0)continue;const gap=Math.hypot(a.x-b.x,a.y-b.y)-(a.d+b.d)/2;if(gap<0)errors.push(`Reiät ${i+1} ja ${j+1} menevät päällekkäin.`);else if(gap<1)warnings.push(`Reikien ${i+1} ja ${j+1} väli on alle 1 mm.`)}}
 function validate(raw){const errors=[],warnings=[];if(!raw||raw.schemaVersion!==2)return{ok:true,errors,warnings};const ops=raw.operations;if(ops==null)return{ok:true,errors,warnings};if(!Array.isArray(ops))return{ok:false,errors:["operations pitää olla taulukko."],warnings};if(ops.length>200)warnings.push("operations sisältää yli 200 operaatiota.");const allowed=support[raw.partType]||new Set();ops.forEach((op,i)=>{if(!op||typeof op!=="object"||Array.isArray(op)){errors.push(`Operaatio ${i+1} ei ole kelvollinen objekti.`);return}const type=String(op.type||"").trim();if(!type){errors.push(`Operaatio ${i+1}: type puuttuu.`);return}if(!allowed.has(type))errors.push(`Operaatiota ”${type}” ei toteuteta ${raw.partType||"tämän"}-editorissa.`);if(type==="holes"&&!Array.isArray(op.holes))errors.push(`Operaatio ${i+1}: holes-taulukko puuttuu.`)});if(raw.partType==="mountingPlate")validatePlateGeometry(raw,errors,warnings);return{ok:errors.length===0,errors:[...new Set(errors)],warnings:[...new Set(warnings)]}}
 function sameRevision(){const base=window.AI3DPlanPreflight?.getLastResult?.();return!!(base?.fingerprint&&last.fingerprint&&base.fingerprint===last.fingerprint)}
 function allowed(){const base=window.AI3DPlanPreflight?.getLastResult?.();return !running&&last.ok&&base?.ok===true&&sameRevision()}
 function gate(){const b=document.querySelector('[data-plan="chatgpt-current"]');if(!b)return;const ok=allowed();b.disabled=!ok;b.classList.toggle("unsupported",!ok);if(ok)b.removeAttribute("title");else if(running)b.title="CAD-operaatioiden tarkistus on kesken.";else if(last.ok&&!sameRevision())b.title="ChatGPT-suunnitelman tarkistukset koskevat eri tiedostoversioita. Päivitä suunnitelma uudelleen.";else b.title=last.errors[0]||"Suunnitelma on estetty."}
 function blockUnsafeClick(e){const b=e.target?.closest?.('[data-plan="chatgpt-current"]');if(!b||allowed())return;e.preventDefault();e.stopImmediatePropagation();gate();const box=$("planPreflight");if(box&&running)box.textContent="⏳ Tarkistetaan ChatGPT-suunnitelman CAD-operaatioita…";else if(box&&last.ok&&!sameRevision())box.textContent="⚠ ChatGPT-suunnitelma estetty: tarkistukset koskevat eri suunnitelmaversioita. Päivitä suunnitelma uudelleen."}
 async function run(){running=true;last={ok:false,errors:["Tarkistus kesken."],warnings:[],fingerprint:null};gate();try{const r=await fetch("chatgpt_plan.json?operations="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const raw=await r.json(),checked=validate(raw);last={...checked,fingerprint:fingerprint(raw)}}catch(e){last={ok:false,errors:["CAD-operaatioiden tarkistus epäonnistui: "+(e?.message||e)],warnings:[],fingerprint:null}}running=false;gate();const box=$("planPreflight");if(box&&!last.ok)box.textContent="⚠ ChatGPT-suunnitelma estetty: "+last.errors.join(" ");else if(box&&last.ok&&!sameRevision())box.textContent="⚠ ChatGPT-suunnitelma estetty: tarkistukset koskevat eri suunnitelmaversioita. Päivitä suunnitelma uudelleen."}
 function init(){const list=$("planList");if(list)new MutationObserver(()=>{const b=document.querySelector('[data-plan="chatgpt-current"]');if(b&&!allowed()&&!b.disabled)gate()}).observe(list,{childList:true,subtree:true,attributes:true,attributeFilter:["disabled","class"]});document.addEventListener("click",blockUnsafeClick,true);run();document.addEventListener("click",e=>{if(e.target?.id==="btnReloadPlans")setTimeout(run,420)})}
 window.AI3DPlanOperationGuard={validate,run,getLastResult:()=>last,isAllowed:allowed};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();