"use strict";
(()=>{
 const $=id=>document.getElementById(id),SUPPORTED=new Set(["spike","plug","sleeve","plate"]),MATS=new Set(["PLA","PETG","ASA"]);let pending=null;
 function validNumber(v,min,max){return typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max}
 function validate(plan){const errors=[];if(!plan||plan.schemaVersion!==1)errors.push("Tuntematon suunnitelmaformaatti.");if(plan.status!=="approved")errors.push("ChatGPT-suunnitelmaa ei ole vielä hyväksytty.");if(!SUPPORTED.has(plan.partType))errors.push("Osatyyppiä ei tueta nykyisessä CAD-moottorissa.");if(!MATS.has(plan.material))errors.push("Materiaali ei ole PLA, PETG tai ASA.");const v=plan.values||{};
  if(plan.partType==="sleeve"){if(!validNumber(v.sleeveID,1,500))errors.push("Holkin sisähalkaisija puuttuu/virheellinen.");if(!validNumber(v.sleeveWall,.4,100))errors.push("Holkin seinämä puuttuu/virheellinen.");if(!validNumber(v.sleeveLength,1,1000))errors.push("Holkin pituus puuttuu/virheellinen.")}
  if(plan.partType==="spike"){if(!validNumber(v.nutAf,5,150))errors.push("Mutterin avainkoko puuttuu/virheellinen.");if(!validNumber(v.totalHeight,5,500))errors.push("Kokonaiskorkeus puuttuu/virheellinen.");if(!validNumber(v.wall,.8,20))errors.push("Seinämä puuttuu/virheellinen.")}
  if(plan.partType==="plug"){if(!validNumber(v.tubeW,5,500)||!validNumber(v.tubeH,5,500))errors.push("Putken ulkomitat puuttuvat/virheelliset.");if(!validNumber(v.tubeWall,.5,30))errors.push("Putken seinämä puuttuu/virheellinen.");if(!validNumber(v.insertDepth,2,300))errors.push("Upotussyvyys puuttuu/virheellinen.")}
  if(plan.partType==="plate"){if(!validNumber(v.plateL,5,1000)||!validNumber(v.plateW,5,1000)||!validNumber(v.plateT,.5,100))errors.push("Levyn päämitat puuttuvat/virheelliset.");if(v.plateHoleD!=null&&!validNumber(v.plateHoleD,0,300))errors.push("Reiän halkaisija on virheellinen.")}
  return errors;
 }
 function fmt(plan){return Object.entries(plan.values||{}).map(([k,v])=>`${k}: <b>${v}</b>`).join(" • ")}
 function inject(){const head=document.querySelector(".chat-head");if(!head||$("chatgptPlanBox"))return;const box=document.createElement("div");box.id="chatgptPlanBox";box.style.cssText="margin-top:10px;padding:10px;border:1px solid #334155;border-radius:12px;background:#0b1220";box.innerHTML=`<button id="btnFetchChatGPTPlan" class="tool" style="width:100%">↻ HAE CHATGPT-SUUNNITELMA</button><div id="chatgptPlanStatus" style="margin-top:8px;color:#94a3b8;font-size:12px">Ei haettua suunnitelmaa.</div><div id="chatgptPlanPreview" hidden style="margin-top:8px;color:#cbd5e1;font-size:12px;line-height:1.5"></div><button id="btnApplyChatGPTPlan" class="primary" hidden style="width:100%;margin-top:8px">HYVÄKSY JA LUO 3D-MALLI</button>`;head.appendChild(box);$("btnFetchChatGPTPlan").onclick=fetchPlan;$("btnApplyChatGPTPlan").onclick=applyPlan;}
 async function fetchPlan(){const st=$("chatgptPlanStatus"),pv=$("chatgptPlanPreview"),ap=$("btnApplyChatGPTPlan");st.textContent="Haetaan hyväksyttyä suunnitelmaa…";pv.hidden=true;ap.hidden=true;pending=null;try{const res=await fetch(`chatgpt_plan.json?t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw Error(`HTTP ${res.status}`);const plan=await res.json();const errors=validate(plan);pending=errors.length?null:plan;pv.hidden=false;pv.innerHTML=`<b>${plan.projectName||"ChatGPT-suunnitelma"}</b><br>${plan.summary||""}<br><br>${fmt(plan)}${errors.length?`<br><br><span style="color:#fecaca">✕ ${errors.join("<br>✕ ")}</span>`:""}`;st.textContent=errors.length?"Suunnitelmaa ei voi vielä tuoda.":"✓ Suunnitelma tarkistettu. Tarkista mitat ennen hyväksymistä.";ap.hidden=errors.length>0}catch(e){st.textContent="Suunnitelman haku epäonnistui: "+e.message}}
 function applyPlan(){if(!pending)return;try{if($("material"))$("material").value=pending.material;window.AI3D.setPart(pending.partType,pending.values);$("chatgptPlanStatus").textContent="✓ ChatGPT-suunnitelma siirretty CAD-moottoriin ja malli luotu tarkistettavaksi.";document.querySelector(".preview-panel")?.scrollIntoView({behavior:"smooth",block:"start"})}catch(e){$("chatgptPlanStatus").textContent="CAD-siirto epäonnistui: "+e.message}}
 document.addEventListener("DOMContentLoaded",inject);
})();
