"use strict";
(()=>{
 const el=id=>document.getElementById(id),OLD=buildPlate,OUTER_N=80,HOLE_N=36,MAX_HOLES=200,MAX_INPUT=50000;
 function resample(points,n=OUTER_N){const seg=[];let total=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],l=Math.hypot(b.x-a.x,b.y-a.y);seg.push({a,b,l,s:total});total+=l}const out=[];for(let k=0;k<n;k++){const q=total*k/n;let g=seg[seg.length-1];for(const s of seg)if(q>=s.s&&q<=s.s+s.l){g=s;break}const t=g.l?(q-g.s)/g.l:0;out.push(v(g.a.x+(g.b.x-g.a.x)*t,g.a.y+(g.b.y-g.a.y)*t,g.a.z))}return out}
 function rounded(L,W,z,r){r=Math.max(0,Math.min(r,L/2-.2,W/2-.2));if(r<.001)return resample([v(-L/2,-W/2,z),v(L/2,-W/2,z),v(L/2,W/2,z),v(-L/2,W/2,z)]);const out=[],per=20,c=[[L/2-r,-W/2+r,-Math.PI/2,0],[L/2-r,W/2-r,0,Math.PI/2],[-L/2+r,W/2-r,Math.PI/2,Math.PI],[-L/2+r,-W/2+r,Math.PI,Math.PI*1.5]];for(const[x,y,a0,a1]of c)for(let i=0;i<per;i++){const a=a0+(a1-a0)*i/per;out.push(v(x+r*Math.cos(a),y+r*Math.sin(a),z))}return out.length===OUTER_N?out:resample(out)}
 function chamfer(L,W,z,c){c=Math.max(0,Math.min(c,L/2-.2,W/2-.2));return resample([v(-L/2+c,-W/2,z),v(L/2-c,-W/2,z),v(L/2,-W/2+c,z),v(L/2,W/2-c,z),v(L/2-c,W/2,z),v(-L/2+c,W/2,z),v(-L/2,W/2-c,z),v(-L/2,-W/2+c,z)])}
 function outer(L,W,z,style,size){return style==="round"?rounded(L,W,z,size):style==="chamfer"?chamfer(L,W,z,size):rounded(L,W,z,0)}
 function hole(cx,cy,r,z){return Array.from({length:HOLE_N},(_,i)=>{const a=i*2*Math.PI/HOLE_N;return v(cx+r*Math.cos(a),cy+r*Math.sin(a),z)})}
 function inside(x,y,L,W,style,size){if(style==="square")return Math.abs(x)<=L/2&&Math.abs(y)<=W/2;if(style==="chamfer"){const ax=Math.abs(x),ay=Math.abs(y);return ax<=L/2&&ay<=W/2&&ax+ay<=L/2+W/2-size+1e-7}const r=Math.min(size,L/2,W/2),ax=Math.abs(x),ay=Math.abs(y);if(ax<=L/2-r||ay<=W/2-r)return ax<=L/2&&ay<=W/2;return Math.hypot(ax-(L/2-r),ay-(W/2-r))<=r+1e-7}
 function holeFits(h,L,W,style,size,margin=.6){const r=h.d/2+margin;for(let i=0;i<HOLE_N;i++){const a=i*2*Math.PI/HOLE_N;if(!inside(h.x+r*Math.cos(a),h.y+r*Math.sin(a),L,W,style,size))return false}return true}
 function parse(){const text=el("plateCustomHoles")?.value||"",rows=[];if(text.length>MAX_INPUT)throw Error("Mukautettu reikälista on liian pitkä.");for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(rows.length>=MAX_HOLES)throw Error(`Mukautetussa levyssä voi olla enintään ${MAX_HOLES} reikää.`);const p=line.split(";").map(s=>Number(String(s).trim().replace(",",".")));if(p.length<3||p.some(x=>!Number.isFinite(x)))throw Error(`Virheellinen reikärivi: ${line}. Käytä muotoa X;Y;Ø`);if(p[2]<=0)throw Error("Reiän halkaisijan pitää olla yli 0 mm.");rows.push({x:p[0],y:p[1],d:p[2]})}return rows}
 function faces(T,o,hs,t){if(typeof earcut!=="function")throw Error("CAD-triangulointikirjasto ei latautunut.");const rings=[o,...hs],flat=[],idx=[];let n=0;rings.forEach((r,i)=>{if(i)idx.push(n);for(const p of r){flat.push(p.x,p.y);n++}});const ids=earcut(flat,idx,2),all0=rings.flat(),all1=all0.map(p=>v(p.x,p.y,t));for(let i=0;i<ids.length;i+=3){const a=ids[i],b=ids[i+1],c=ids[i+2];T.push(tri(all0[a],all0[c],all0[b]),tri(all1[a],all1[b],all1[c]))}}
 function custom(){const L=+el("plateL").value,W=+el("plateW").value,T=+el("plateT").value,style=el("plateCornerStyle")?.value||"square",size=Math.max(0,+el("plateCornerSize")?.value||0),holes=parse();if(L<=2||W<=2||T<1)throw Error("Levyn mitat eivät ole mahdollisia.");if(!holes.length)throw Error("Lisää vähintään yksi mukautettu reikä.");for(const h of holes)if(!holeFits(h,L,W,style,size))throw Error(`Reikä Ø${h.d} @ ${h.x},${h.y} on liian lähellä levyn todellista reunaa tai kulmaa.`);for(let i=0;i<holes.length;i++)for(let j=i+1;j<holes.length;j++)if(Math.hypot(holes[i].x-holes[j].x,holes[i].y-holes[j].y)<=(holes[i].d+holes[j].d)/2+1)throw Error(`Reiät ${i+1} ja ${j+1} ovat liian lähellä toisiaan.`);const o0=outer(L,W,0,style,size),o1=o0.map(p=>v(p.x,p.y,T)),h0=holes.map(h=>hole(h.x,h.y,h.d/2,0)),h1=h0.map(r=>r.map(p=>v(p.x,p.y,T))),tris=[];faces(tris,o0,h0,T);bridge(tris,o0,o1);for(let i=0;i<h0.length;i++)bridge(tris,h0[i],h1[i],true);currentFitMesh=null;const measure=[["Pituus",L],["Leveys",W],["Paksuus",T],["Reikiä",`${holes.length} kpl`]];holes.slice(0,6).forEach((h,i)=>measure.push([`R${i+1}`,`Ø${h.d} @ ${h.x},${h.y}`]));if(holes.length>6)measure.push(["Muut reiät",`${holes.length-6} kpl`]);if(style!=="square")measure.push([style==="round"?"Pyöristys":"Viiste",size]);return{triangles:tris,name:"kiinnikelevy_mukautetut_reiat",width:L,depth:W,height:T,measure}}
 buildPlate=function(){return el("plateHolePattern")?.value==="custom"?custom():OLD()};
})();