"use strict";
(()=>{
 const $=id=>document.getElementById(id),KEY="ai3d:projects:v3",BACKUP=KEY+":backup",ALLOWED=new Set(["lightSign","spike","plug","sleeve","plate","adapter","enclosure"]),BLOCKED_KEYS=new Set(["__proto__","prototype","constructor"]);
 function parse(raw){try{const a=JSON.parse(raw||"[]");return Array.isArray(a)?a:null}catch{return null}}
 function validValues(v){if(!v||typeof v!=="object"||Array.isArray(v))return false;const e=Object.entries(v);if(e.length>100)return false;return e.every(([k,x])=>!BLOCKED_KEYS.has(k)&&(x===null||["string","number","boolean"].includes(typeof x))&&(typeof x!=="number"||Number.isFinite(x)))}
 function validProject(p){return!!(p&&typeof p==="object"&&!Array.isArray(p)&&typeof p.id==="string"&&p.id&&p.id.length<=160&&ALLOWED.has(p.type)&&validValues(p.values)&&(p.name==null||typeof p.name==="string")&&(p.description==null||typeof p.description==="string"))}
 function cleanPrint(pr){if(!pr||typeof pr!=="object"||Array.isArray(pr))return null;const out={};for(const k of ["printer","nozzle","layer","walls","infill","notes"]){const v=pr[k];if(v==null)continue;if(!["string","number","boolean"].includes(typeof v)||(typeof v==="number"&&!Number.isFinite(v)))continue;out[k]=typeof v==="string"?v.slice(0,k==="notes"?1000:160):v}return Object.keys(out).length?out:null}
 function cleanTime(v,fallback){const n=Number(v);return Number.isFinite(n)&&n>=0&&n<=8.64e15?n:fallback}
 function cleanImportedProject(p){const now=Date.now(),created=cleanTime(p.created,now),updated=cleanTime(p.updated,created),out={id:p.id,name:String(p.name||"Tuotu projekti").slice(0,120),description:String(p.description||"").slice(0,1000),type:p.type,values:{...p.values},created,updated};const print=cleanPrint(p.print);if(print)out.print=print;if(typeof p.sourcePlan==="string")out.sourcePlan=p.sourcePlan.slice(0,160);if([1,2].includes(p.sourceSchema))out.sourceSchema=p.sourceSchema;return out}
 function read(){const main=parse(localStorage.getItem(KEY));if(main&&main.every(validProject))return main;const backup=parse(localStorage.getItem(BACKUP));if(backup&&backup.every(validProject)){try{localStorage.setItem(KEY,JSON.stringify(backup))}catch{}return backup}return[]}
 function restoreStorage(key,value){try{if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value)}catch{}}
 function write(items,active){let prev=null,prevActive=null,prevBackup=null,captured=false;try{if(!Array.isArray(items)||!items.every(validProject))throw Error("Projektidata ei läpäissyt rakennetarkistusta.");const next=JSON.stringify(items),nextActive=active||"";prev=localStorage.getItem(KEY);prevActive=localStorage.getItem(KEY+":active");prevBackup=localStorage.getItem(BACKUP);captured=true;const current=parse(prev);localStorage.setItem(KEY,next);localStorage.setItem(KEY+":active",nextActive);if(localStorage.getItem(KEY)!==next||localStorage.getItem(KEY+":active")!==nextActive)throw Error("Tallennuksen varmennus epäonnistui.");if(current&&current.every(validProject)&&prev!==next){try{localStorage.setItem(BACKUP,prev)}catch{}}return true}catch(e){if(captured){restoreStorage(KEY,prev);restoreStorage(KEY+":active",prevActive);restoreStorage(BACKUP,prevBackup)}alert("Projektien tallennus epäonnistui: "+(e?.message||e));return false}}
 function active(){return window.AI3DProjects?.active?.()||null}
 function newProjectId(items){const used=new Set((items||[]).map(p=>p?.id));let id="";do{try{id="p"+(globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`)}catch{id="p"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,10)}}while(used.has(id));return id}
 function duplicate(){const p=active();if(!p)return alert("Valitse projekti ensin.");const items=read(),src=items.find(x=>x.id===p.id)||p,id=newProjectId(items),copy={...src,id,name:String(src.name||"Projekti")+" – kopio",values:{...(src.values||{})},created:Date.now(),updated:Date.now()};items.unshift(copy);if(write(items,id))location.reload()}
 function remove(){const p=active();if(!p)return alert("Valitse projekti ensin.");if(!confirm(`Poistetaanko projekti ”${p.name||"projekti"}” tältä laitteelta?\n\nChatGPT-suunnitelmaa tai GitHub-tiedostoja ei poisteta. Edellinen projektitilanne jää paikalliseen varmuuskopioon.`))return;const items=read().filter(x=>x.id!==p.id),next=items[0]?.id||"";if(write(items,next))location.reload()}
 function restore(){const backup=parse(localStorage.getItem(BACKUP));if(!backup?.length||!backup.every(validProject))return alert("Rakenteellisesti kelvollista paikallista projektivarmuuskopiota ei löytynyt.");if(!confirm(`Palautetaanko edellinen paikallinen projektitilanne (${backup.length} projektia)?\n\nNykyinen tila siirtyy samalla varmuuskopioksi.`))return;const ids=new Set(backup.map(x=>x.id)),activeId=localStorage.getItem(KEY+":active"),wanted=ids.has(activeId)?activeId:backup[0]?.id||"";if(write(backup,wanted))location.reload()}
 function exportAll(){const items=read().filter(validProject);if(!items.length)return alert("Tallennettavia projekteja ei löytynyt.");const data={format:"AI3D-project-backup",version:1,exportedAt:new Date().toISOString(),activeId:localStorage.getItem(KEY+":active")||"",projects:items};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="ai3d-kaikki-projektit-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function importAll(file){if(!file||file.size>5_000_000)return alert("Varmuuskopiotiedosto on liian suuri.");const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d?.format!=="AI3D-project-backup"||d.version!==1||!Array.isArray(d.projects))throw Error("Tiedosto ei ole AI 3D Studio -projektivarmuuskopio.");const bad=d.projects.filter(p=>!validProject(p));if(bad.length)throw Error(`Varmuuskopiossa on ${bad.length} virheellistä tai tuntematonta projektia.`);const ids=new Set(),clean=[];for(const p of d.projects){if(ids.has(p.id))throw Error("Varmuuskopiossa on päällekkäisiä projektitunnuksia.");ids.add(p.id);clean.push(cleanImportedProject(p))}if(!clean.length)throw Error("Varmuuskopio ei sisällä projekteja.");const wanted=ids.has(d.activeId)?d.activeId:clean[0].id;if(!confirm(`Palautetaanko tiedostosta ${clean.length} projektia?\n\nNykyiset paikalliset projektit siirtyvät ensin varmuuskopioksi. GitHub-tiedostoihin ei tehdä muutoksia.`))return;if(write(clean,wanted))location.reload()}catch(e){alert("Varmuuskopion tuonti epäonnistui: "+(e?.message||e))}};r.onerror=()=>alert("Varmuuskopiotiedostoa ei voitu lukea.");r.readAsText(file)}
 function storage(){const root=$("projectStorageInfo");if(!root)return;const raw=localStorage.getItem(KEY)||"[]",bytes=new Blob([raw]).size,count=read().length,backup=parse(localStorage.getItem(BACKUP));root.textContent=`Paikalliset projektit: ${count} • tallennus noin ${(bytes/1024).toFixed(1)} kB${backup?.length?` • varmuuskopio ${backup.length} projektia`:""}`;root.title="Projektit tallennetaan tämän selaimen localStorageen. Jokaisen hallintakirjoituksen yhteydessä edellinen tila säilytetään paikallisena varmuuskopiona. Vie lisäksi kaikki projektit tiedostoksi tärkeiden töiden varmistamiseksi.";const b=$("btnRestoreProjects");if(b)b.disabled=!(backup?.length&&backup.every(validProject))}
 function inject(){if($("btnDuplicateProject"))return;const sync=$("planSyncStatus");if(!sync)return;const menu=document.createElement("details");menu.className="project-actions-menu";menu.innerHTML='<summary>⋮ PROJEKTIN TOIMINNOT</summary><div class="project-actions-body"><button id="btnDuplicateProject" class="ghost">KOPIOI PROJEKTI</button><button id="btnDeleteProject" class="ghost">POISTA PROJEKTI</button><button id="btnExportAllProjects" class="ghost">VIE PROJEKTIT VARMUUSKOPIOON</button><button id="btnImportAllProjects" class="ghost">TUO VARMUUSKOPIO</button><input id="projectBackupFile" type="file" accept="application/json,.json" hidden><button id="btnRestoreProjects" class="ghost">PALAUTA EDELLINEN PROJEKTITILA</button><small id="projectStorageInfo"></small></div>';sync.after(menu);$("btnDuplicateProject").onclick=duplicate;$("btnDeleteProject").onclick=remove;$("btnExportAllProjects").onclick=exportAll;$("btnImportAllProjects").onclick=()=>$("projectBackupFile").click();$("projectBackupFile").onchange=e=>{const f=e.target.files?.[0];if(f)importAll(f);e.target.value=""};$("btnRestoreProjects").onclick=restore;storage()}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(inject,80));else setTimeout(inject,80);
})();