"use strict";
(()=>{
 const loader=document.createElement("script");loader.src=`centauri.js?v=1.4&t=${Date.now()}`;document.head.appendChild(loader);
 const KEY="ai3d:projects:v3", $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 let projects=[],plans=[],activeId="";
 const save=()=>{localStorage.setItem(KEY,JSON.stringify(projects));localStorage.setItem(KEY+":active",activeId||"")};
 const current=()=>projects.find(p=>p.id===activeId);
 const num=x=>Number.isFinite(+x)?+x:0;
 function renderPlans(){const root=$("planList");if(!root)return;root.innerHTML=plans.map(p=>`<button class="project-item plan-item" data-plan="${esc(p.id)}"><b>${esc(p.name)}</b><small>${esc(p.description||"")}</small>${p.source==="chatgpt"?'<span class="plan-source">ChatGPT-suunnitelma</span>':''}</button>`).join("");root.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>openPlan(b.dataset.plan))}
 function renderProjects(){const root=$("projectList");if(!root)return;root.innerHTML=projects.map(p=>`<button class="project-item ${p.id===activeId?"active":""}" data-id="${esc(p.id)}"><b>${esc(p.name)}</b><small>${new Date(p.updated||p.created||Date.now()).toLocaleDateString("fi-FI")}</small></button>`).join("");root.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openProject(b.dataset.id))}
 function showInfo(p){$("projectName").textContent=p?.name||"–";$("projectDescription").textContent=p?.description||"Muuta mittoja CAD-työtilassa ja lataa STL-tiedostot.";const pr=p?.print;$("projectPrintInfo").innerHTML=pr?`<b>Tulostus:</b> ${esc(pr.printer||"")} • suutin ${esc(pr.nozzle||"")} • kerros ${esc(pr.layer||"")} • seinät ${esc(pr.walls||"")} • täyttö ${esc(pr.infill||"")}<br><span>${esc(pr.notes||"")}</span>`:`<b>Tulostin:</b> Elegoo Centauri Carbon 2 Combo<br><span>STL voidaan avata ElegooSlicerissa, Orcassa tai Curassa.</span>`}
 function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;activeId=id;save();renderProjects();showInfo(p);window.AI3D?.setPart(p.type||"spike",p.values||{});setTimeout(()=>window.CentauriProfile?.check?.(),80)}
 function snapshotValues(type){const map={lightSign:["signDiameter","signRingWidth","signDepth","signWall","diffuserThickness","starWidth","starThickness","ledWidth","filamentPriceKg","ledCost","powerCost","miscCost","material"],spike:["nutAf","clearance","lockAmount","lockZ","wall","baseHeight","totalHeight","tipRadius","material"],plug:["tubeW","tubeH","tubeWall","plugClear","insertDepth","capThickness","capOverhang","material"],sleeve:["sleeveID","sleeveWall","sleeveLength","material"],plate:["plateL","plateW","plateT","plateHolePattern","plateHoleD","plateHoleEdge","plateCornerStyle","plateCornerSize","plateCustomHoles","material"]};const out={};(map[type]||map.spike).forEach(id=>{const e=$(id);if(e)out[id]=e.type==="number"?+e.value:e.value});return out}
 function openPlan(id){const plan=plans.find(x=>x.id===id);if(!plan)return;const p={id:"p"+Date.now(),name:plan.name,description:plan.description||"",type:plan.type,values:{...(plan.values||{})},print:plan.print||null,created:Date.now(),updated:Date.now(),sourcePlan:id,sourceSchema:plan.sourceSchema||null};projects.unshift(p);activeId=p.id;save();renderProjects();showInfo(p);window.AI3D?.setPart(p.type,p.values);setTimeout(()=>window.CentauriProfile?.check?.(),80)}
 function newProject(){const name=prompt("Projektin nimi","Uusi 3D-projekti");if(!name)return;const type=$("partType")?.value||"spike",p={id:"p"+Date.now(),name:name.trim()||"Uusi 3D-projekti",description:"Oma muokattava projekti",type,values:snapshotValues(type),created:Date.now(),updated:Date.now()};projects.unshift(p);activeId=p.id;save();renderProjects();showInfo(p)}
 function autosave(){const p=current();if(!p)return;p.type=$("partType")?.value||p.type;p.values={...p.values,...snapshotValues(p.type)};p.updated=Date.now();save();renderProjects()}
 function holeLines(raw){const out=[];const add=h=>{if(!h)return;const x=num(h.x),y=num(h.y),d=num(h.diameter??h.d);if(d>0)out.push(`${x};${y};${d}`)};(raw?.parameters?.holes||[]).forEach(add);if(raw?.parameters?.centerHole)add({x:0,y:0,diameter:raw.parameters.centerHole.diameter??raw.parameters.centerHole});for(const op of raw?.operations||[]){if(op?.type==="hole")add(op);if(op?.type==="holes")(op.holes||[]).forEach(add)}return out}
 function normalizeChatGPT(raw){if(!raw||![1,2].includes(raw.schemaVersion))return null;if(raw.schemaVersion===1){const aliases={plug:"plug",sleeve:"sleeve",spike:"spike",plate:"plate"};if(!aliases[raw.partType])return null;return{id:"chatgpt-current",name:raw.projectName||"ChatGPT-suunnitelma",description:raw.summary||"ChatGPTissa tehty muokattava suunnitelma",type:aliases[raw.partType],values:{...(raw.values||{}),material:raw.material||"PETG"},source:"chatgpt",sourceSchema:1}}
  const t=raw.partType,p=raw.parameters||{},base={id:"chatgpt-current",name:raw.projectName||"ChatGPT-suunnitelma",description:raw.summary||"",source:"chatgpt",sourceSchema:2};
  if(t==="sleeve")return{...base,type:"sleeve",values:{sleeveID:p.insideDiameter,sleeveWall:p.wall??((p.outsideDiameter-p.insideDiameter)/2),sleeveLength:p.length,material:raw.material||"PETG"}};
  if(t==="spike")return{...base,type:"spike",values:{nutAf:p.nutAcrossFlats??p.nutAf,clearance:p.clearance??.25,lockAmount:p.lockAmount??.2,lockZ:p.lockZ??7,wall:p.wall,baseHeight:p.baseHeight??24,totalHeight:p.height??p.totalHeight,tipRadius:p.tipRadius??.8,material:raw.material||"ASA"}};
  if(t==="endPlug")return{...base,type:"plug",values:{tubeW:p.width,tubeH:p.height,tubeWall:p.wall,plugClear:p.clearance??.25,insertDepth:p.insertDepth,capThickness:p.capThickness??p.thickness??3,capOverhang:p.overhang??1,material:raw.material||"PETG"}};
  if(t==="mountingPlate"){
    const holes=holeLines(raw),cornerRadius=num(p.cornerRadius),chamfer=num(p.chamfer);
    return{...base,type:"plate",values:{plateL:p.length,plateW:p.width,plateT:p.thickness,plateHolePattern:holes.length?"custom":"none",plateCustomHoles:holes.join("\n"),plateHoleD:0,plateHoleEdge:10,plateCornerStyle:cornerRadius>0?"round":chamfer>0?"chamfer":"square",plateCornerSize:cornerRadius||chamfer||0,material:raw.material||"PETG"}};
  }
  return null}
 async function loadPlans(){let base=[];try{const r=await fetch(`plans.json?v=${Date.now()}`,{cache:"no-store"});if(r.ok){const data=await r.json();base=Array.isArray(data.plans)?data.plans:[]}}catch{}try{const r=await fetch(`chatgpt_plan.json?v=${Date.now()}`,{cache:"no-store"});if(r.ok){const c=normalizeChatGPT(await r.json());if(c)base.unshift(c)}}catch{}plans=base.length?base:[{id:"light-sign-400",name:"Valokyltti 400 mm",description:"400 mm LED-valokyltti",type:"lightSign",values:{signDiameter:400,signRingWidth:28,signDepth:24,signWall:2.4,diffuserThickness:1.2,starWidth:28,starThickness:4,ledWidth:10,material:"PETG"}}];renderPlans();if(!projects.length&&plans.length)openPlan(plans[0].id);else if(projects.length)openProject(activeId||projects[0].id)}
 function downloadProject(){const p=current();if(!p)return alert("Valitse projekti ensin.");autosave();const copy={format:"AI3D-project",version:1,exportedAt:new Date().toISOString(),project:{...p}};delete copy.project.id;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(copy,null,2)],{type:"application/json"}));a.download=(p.name||"3d-projekti").replace(/[^a-z0-9åäö_-]+/gi,"_")+".ai3d.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function importProject(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),src=d?.format==="AI3D-project"?d.project:d;if(!src||!src.type||!src.values)throw Error("Tiedosto ei ole 3D Studio -projekti.");const p={...src,id:"p"+Date.now(),name:src.name||"Tuotu projekti",created:Date.now(),updated:Date.now()};projects.unshift(p);activeId=p.id;save();renderProjects();openProject(p.id)}catch(e){alert("Projektin tuonti epäonnistui: "+e.message)}};r.readAsText(file)}
 function injectTools(){const side=document.querySelector(".project-sidebar");if(side&&!$("btnReloadPlans")){const box=document.createElement("div");box.style.display="grid";box.style.gap="6px";box.style.margin="8px 0 12px";box.innerHTML='<button id="btnReloadPlans" class="ghost">↻ PÄIVITÄ CHATGPT-SUUNNITELMA</button><button id="btnExportProject" class="ghost">VIE PROJEKTI JSON</button><button id="btnImportProject" class="ghost">TUO PROJEKTI JSON</button><input id="projectImportFile" type="file" accept="application/json,.json" hidden>';side.insertBefore(box,side.querySelector(".section-title"));$("btnReloadPlans").onclick=loadPlans;$("btnExportProject").onclick=downloadProject;$("btnImportProject").onclick=()=>$("projectImportFile").click();$("projectImportFile").onchange=e=>{const f=e.target.files?.[0];if(f)importProject(f);e.target.value=""}}
  const grid=$("fields-plate")?.querySelector(".grid");if(grid&&!$("plateCustomHoles")){const opt=document.createElement("option");opt.value="custom";opt.textContent="Mukautetut reiät";$("plateHolePattern")?.appendChild(opt);const lab=document.createElement("label");lab.style.gridColumn="1 / -1";lab.innerHTML='Mukautetut reiät — yksi per rivi: X;Y;Ø (mm)<textarea id="plateCustomHoles" rows="5" placeholder="-35;-15;6\n35;-15;6\n35;15;6\n-35;15;6"></textarea>';grid.appendChild(lab)} }
 function loadAddon(src,done){const s=document.createElement("script");s.src=src;s.onload=()=>done?.();s.onerror=()=>done?.();document.body.appendChild(s)}
 document.addEventListener("DOMContentLoaded",()=>{try{projects=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{projects=[]}activeId=localStorage.getItem(KEY+":active")||projects[0]?.id||"";injectTools();$("btnNewProject").onclick=newProject;["partType","material"].forEach(id=>$(id)?.addEventListener("change",()=>setTimeout(autosave,0)));document.querySelector(".controls")?.addEventListener("input",e=>{if(e.target.matches("input,select,textarea"))setTimeout(autosave,0)});loadAddon("plate_custom.js?v=1.4",loadPlans)});
 window.AI3DProjects={openPlan,newProject,active:current,reloadPlans:loadPlans,exportProject:downloadProject};
})();