"use strict";
(()=>{
 const $=id=>document.getElementById(id),KEY="ai3d:projects:v3",BACKUP=KEY+":backup";
 function parse(raw){try{const a=JSON.parse(raw||"[]");return Array.isArray(a)?a:null}catch{return null}}
 function read(){const main=parse(localStorage.getItem(KEY));if(main)return main;const backup=parse(localStorage.getItem(BACKUP));if(backup){try{localStorage.setItem(KEY,JSON.stringify(backup))}catch{}return backup}return[]}
 function write(items,active){try{const current=parse(localStorage.getItem(KEY));if(current)localStorage.setItem(BACKUP,JSON.stringify(current));localStorage.setItem(KEY,JSON.stringify(items));localStorage.setItem(KEY+":active",active||"");return true}catch(e){alert("Projektien tallennus epäonnistui: "+(e?.message||e));return false}}
 function active(){return window.AI3DProjects?.active?.()||null}
 function duplicate(){const p=active();if(!p)return alert("Valitse projekti ensin.");const items=read(),src=items.find(x=>x.id===p.id)||p,id="p"+Date.now(),copy={...src,id,name:String(src.name||"Projekti")+" – kopio",values:{...(src.values||{})},created:Date.now(),updated:Date.now()};items.unshift(copy);if(write(items,id))location.reload()}
 function remove(){const p=active();if(!p)return alert("Valitse projekti ensin.");if(!confirm(`Poistetaanko projekti ”${p.name||"projekti"}” tältä laitteelta?\n\nChatGPT-suunnitelmaa tai GitHub-tiedostoja ei poisteta. Edellinen projektitilanne jää paikalliseen varmuuskopioon.`))return;const items=read().filter(x=>x.id!==p.id),next=items[0]?.id||"";if(write(items,next))location.reload()}
 function restore(){const backup=parse(localStorage.getItem(BACKUP));if(!backup?.length)return alert("Paikallista projektivarmuuskopiota ei löytynyt.");if(!confirm(`Palautetaanko edellinen paikallinen projektitilanne (${backup.length} projektia)?\n\nNykyinen tila siirtyy samalla varmuuskopioksi.`))return;const current=parse(localStorage.getItem(KEY))||[];try{localStorage.setItem(BACKUP,JSON.stringify(current));localStorage.setItem(KEY,JSON.stringify(backup));const ids=new Set(backup.map(x=>x?.id));const activeId=localStorage.getItem(KEY+":active");if(!ids.has(activeId))localStorage.setItem(KEY+":active",backup[0]?.id||"");location.reload()}catch(e){alert("Varmuuskopion palautus epäonnistui: "+(e?.message||e))}}
 function storage(){const root=$("projectStorageInfo");if(!root)return;const raw=localStorage.getItem(KEY)||"[]",bytes=new Blob([raw]).size,count=read().length,backup=parse(localStorage.getItem(BACKUP));root.textContent=`Paikalliset projektit: ${count} • tallennus noin ${(bytes/1024).toFixed(1)} kB${backup?.length?` • varmuuskopio ${backup.length} projektia`:""}`;root.title="Projektit tallennetaan tämän selaimen localStorageen. Jokaisen hallintakirjoituksen yhteydessä edellinen tila säilytetään paikallisena varmuuskopiona. Käytä lisäksi VIE PROJEKTI JSON -toimintoa tärkeille projekteille.";const b=$("btnRestoreProjects");if(b)b.disabled=!backup?.length}
 function inject(){if($("btnDuplicateProject"))return;const sync=$("planSyncStatus");if(!sync)return;const box=document.createElement("div");box.className="project-extra-tools";box.style.display="grid";box.style.gridTemplateColumns="1fr 1fr";box.style.gap="6px";box.innerHTML='<button id="btnDuplicateProject" class="ghost">KOPIOI</button><button id="btnDeleteProject" class="ghost">POISTA</button><button id="btnRestoreProjects" class="ghost" style="grid-column:1/-1">PALAUTA EDELLINEN PROJEKTITILA</button><small id="projectStorageInfo" style="grid-column:1/-1;color:#64748b;padding:2px 3px"></small>';sync.after(box);$("btnDuplicateProject").onclick=duplicate;$("btnDeleteProject").onclick=remove;$("btnRestoreProjects").onclick=restore;storage()}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(inject,80));else setTimeout(inject,80);
})();