"use strict";
(()=>{
 function loadCentauri(){if(window.CentauriProfile||document.querySelector('script[data-ai3d-centauri],script[src^="centauri.js"]'))return;const loader=document.createElement("script");loader.src="centauri.js?v=1.8";loader.dataset.ai3dCentauri="1";loader.onerror=()=>setTimeout(()=>setSync("⚠ Centauri-tarkistuksen lataus epäonnistui. Muut projektit säilyvät käytettävissä, mutta tarkista yhteys ennen STL-vientiä.","warn"),0);document.head.appendChild(loader)}
 loadCentauri();
 const KEY="ai3d:projects:v3",BACKUP=KEY+":backup",OLD_KEYS=["ai3d:projects:v2","ai3d:projects:v1"],$=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const ALLOWED_TYPES=new Set(["lightSign","spike","plug","sleeve","plate","adapter","enclosure"]),BLOCKED_KEYS=new Set(["__proto__","prototype","constructor"]);
 let projects=[],plans=[],activeId="",autosaveTimer=0,storageError="",planLoadSeq=0;
 const num=x=>Number.isFinite(+x)?+x:0;
 const fingerprint=x=>{try{return JSON.stringify(x)}catch{return null}};
 const current=()=>projects.find(p=>p.id===activeId);
 function newProjectId(){let id="";do{try{id="p"+(globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`)}catch{id="p"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,10)}}while(projects.some(p=>p.id===id));return id}
 function validValues(v){if(!v||typeof v!=="object"||Array.isArray(v))return false;const e=Object.entries(v);if(e.length>100)return false;return e.every(([k,x])=>!BLOCKED_KEYS.has(k)&&(x===null||["string","number","boolean"].includes(typeof x))&&(typeof x!=="number"||Number.isFinite(x)))}
 function validProject(p){return!!(p&&typeof p==="object"&&!Array.isArray(p)&&typeof p.id==="string"&&p.id&&ALLOWED_TYPES.has(p.type)&&validValues(p.values))}
 function validProjects(a){return Array.isArray(a)&&a.every(validProject)}
 function setSync(text,kind=""){const e=$("planSyncStatus");if(!e)return;e.textContent=text;e.className="plan-sync-status "+kind}
 function restoreStorage(key,value){try{if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value)}catch{}}
 function save(){let prev=null,prevActive=null,prevBackup=null,captured=false;try{if(!validProjects(projects))throw Error("Projektidata ei läpäissyt rakennetarkistusta.");const next=JSON.stringify(projects),nextActive=activeId||"";prev=localStorage.getItem(KEY);prevActive=localStorage.getItem(KEY+":active");prevBackup=localStorage.getItem(BACKUP);captured=true;localStorage.setItem(KEY,next);localStorage.setItem(KEY+":active",nextActive);if(localStorage.getItem(KEY)!==next||localStorage.getItem(KEY+":active")!==nextActive)throw Error("Tallennuksen varmennus epäonnistui.");if(prev&&prev!==next){try{const old=JSON.parse(prev);if(validProjects(old))localStorage.setItem(BACKUP,prev)}catch{}}storageError="";return true}catch(e){if(captured){restoreStorage(KEY,prev);restoreStorage(KEY+":active",prevActive);restoreStorage(BACKUP,prevBackup)}storageError=e?.message||"Tallennus epäonnistui";setSync("⚠ Projektien paikallinen tallennus epäonnistui: "+storageError,"warn");return false}}
 function migrate(){if(localStorage.getItem(KEY))return;for(const old of OLD_KEYS){const raw=localStorage.getItem(old);if(!raw)continue;try{const arr=JSON.parse(raw);if(validProjects(arr)){localStorage.setItem(KEY,JSON.stringify(arr));const oldActive=localStorage.getItem(old+":active");if(oldActive)localStorage.setItem(KEY+":active",oldActive);setSync(`✓ Vanhan version projektit palautettu (${arr.length} kpl).`,"ok");return}}catch{}}}
 function renderPlans(){const root=$("planList");if(!root)return;root.innerHTML=plans.map(p=>p.unsupported?`<button class="project-item plan-item unsupported" disabled><b>${esc(p.name)}</b><small>${esc(p.description||"")}</small><span class="plan-source">Ei vielä muokattavissa</span></button>`:`<button class="project-item plan-item" data-plan="${esc(p.id)}"><b>${esc(p.name)}</b><small>${esc(p.description||"")}</small>${p.source==="chatgpt"?'<span class="plan-source">ChatGPT-suunnitelma</span>':''}</button>`).join("");root.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>openPlan(b.dataset.plan))}
 function renderProjects(){const root=$("projectList");if(!root)return;root.innerHTML=projects.map(p=>`<button class="project-item ${p.id===activeId?"active":""}" data-id="${esc(p.id)}"><b>${esc(p.name)}</b><small>${new Date(p.updated||p.created||Date.now()).toLocaleString("fi-FI",{dateStyle:"short",timeStyle:"short"})}</small></button>`).join("");root.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openProject(b.dataset.id))}
 function showInfo(p){$("projectName").textContent=p?.name||"–";$("projectDescription").textContent=p?.description||"Muuta mittoja CAD-työtilassa ja lataa STL-tiedostot.";const pr=p?.print;$("projectPrintInfo").innerHTML=pr?`<b>Tulostus:</b> ${esc(pr.printer||"")} • suutin ${esc(pr.nozzle||"")} • kerros ${esc(pr.layer||"")} • seinät ${esc(pr.walls||"")} • täyttö ${esc(pr.infill||"")}<br><span>${esc(pr.notes||"")}</span>`:`<b>Tulostin:</b> Elegoo Centauri Carbon 2 Combo<br><span>3D Studio tarkistaa mallin mitat ennen STL-vientiä. Lopullinen viipalointi tehdään slicerissa.</span>`}
 function cadFailure(){const v=$("validation"),status=$("status")?.textContent||"";if(v?.querySelector(".check.fail"))return status||"CAD-malli ei läpäissyt tarkistusta.";if(/^\s*Virhe\s*:/i.test(status)||/generointi epäonnistui|STL-lataus estetty/i.test(status))return status||"CAD-malli ei läpäissyt tarkistusta.";return""}
 function applyProject(p){if(!p||!ALLOWED_TYPES.has(p.type)||!validValues(p.values))throw Error("Projektin osatyyppiä tai arvoja ei tueta tässä versiossa.");if(typeof window.AI3D?.setPart!=="function")throw Error("CAD-moottori ei ole vielä valmis.");window.AI3D.setPart(p.type,p.values||{});const fail=cadFailure();if(fail)throw Error(fail);setTimeout(()=>window.CentauriProfile?.check?.(),80)}
 function restoreProject(p){if(!p)return;try{window.AI3D?.setPart?.(p.type,p.values||{});setTimeout(()=>window.CentauriProfile?.check?.(),80)}catch{}}
 function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return false;const previous=current(),previousId=activeId;try{applyProject(p);activeId=id;if(!save())throw Error("Projektin aktivointia ei voitu tallentaa.");renderProjects();showInfo(p);setSync("✓ Projekti avattu.","ok");return true}catch(e){activeId=previousId;if(previous&&previous.id!==p.id)restoreProject(previous);renderProjects();showInfo(previous&&previous.id!==p.id?previous:null);setSync("⚠ Projektia ei voitu avata: "+e.message,"warn");return false}}
 function snapshotValues(type){const map={lightSign:["signDiameter","signRingWidth","signDepth","signWall","diffuserThickness","starWidth","starThickness","ledWidth","filamentPriceKg","ledCost","powerCost","miscCost","material"],spike:["nutAf","clearance","lockAmount","lockZ","wall","baseHeight","totalHeight","tipRadius","monogram","monogramWidth","monogramDepth","monogramHeight","material"],plug:["tubeW","tubeH","tubeWall","plugClear","insertDepth","capThickness","capOverhang","material"],sleeve:["sleeveID","sleeveWall","sleeveLength","material"],plate:["plateL","plateW","plateT","plateHolePattern","plateHoleD","plateHoleEdge","plateCornerStyle","plateCornerSize","plateCustomHoles","material"],adapter:["adapterLength","adapterID1","adapterID2","adapterOD1","adapterOD2","material"],enclosure:["enclosureW","enclosureD","enclosureH","enclosureWall","enclosureFloor","material"]};const out={};(map[type]||[]).forEach(id=>{const e=$(id);if(!e)return;if(e.type==="number"){const x=e.valueAsNumber;if(Number.isFinite(x))out[id]=x}else out[id]=e.value});return out}
 function canOpenPlan(plan){if(!plan||plan.unsupported)return false;if(plan.source!=="chatgpt")return true;const pre=window.AI3DPlanPreflight?.getLastResult?.(),ops=window.AI3DPlanOperationGuard?.getLastResult?.(),fp=plan.sourceFingerprint;return!!(fp&&pre?.ok===true&&ops?.ok===true&&pre.fingerprint===fp&&ops.fingerprint===fp&&window.AI3DPlanOperationGuard?.isAllowed?.())}
 function openPlan(id){const plan=plans.find(x=>x.id===id&&!x.unsupported);if(!plan)return;if(!canOpenPlan(plan)){setSync("⚠ ChatGPT-suunnitelmaa ei avattu: odota ennakkotarkistusten valmistumista tai päivitä suunnitelma uudelleen.","warn");return}const p={id:newProjectId(),name:plan.name,description:plan.description||"",type:plan.type,values:{...(plan.values||{})},print:plan.print||null,created:Date.now(),updated:Date.now(),sourcePlan:id,sourceSchema:plan.sourceSchema||null},previous=current(),previousId=activeId;try{applyProject(p);projects.unshift(p);activeId=p.id;if(!save())throw Error("Projektikopiota ei voitu tallentaa.");renderProjects();showInfo(p);setSync(plan.source==="chatgpt"?"✓ ChatGPT-suunnitelmasta tehtiin oma muokattava projektikopio.":"✓ Suunnitelmasta tehtiin oma muokattava projektikopio.","ok")}catch(e){projects=projects.filter(x=>x!==p);activeId=previousId;if(previous)restoreProject(previous);renderProjects();showInfo(previous||null);setSync("⚠ Suunnitelman avaaminen epäonnistui eikä projektia tallennettu: "+e.message,"warn")}}
 function newProject(){const name=prompt("Projektin nimi","Uusi 3D-projekti");if(!name)return;const type=$("partType")?.value||"spike",p={id:newProjectId(),name:name.trim()||"Uusi 3D-projekti",description:"Oma muokattava projekti",type,values:snapshotValues(type),created:Date.now(),updated:Date.now()},previous=current(),previousId=activeId;projects.unshift(p);activeId=p.id;if(!save()){projects=projects.filter(x=>x!==p);activeId=previousId;renderProjects();showInfo(previous||null);return}renderProjects();showInfo(p)}
 function autosave(){const p=current();if(!p)return true;const type=$("partType")?.value||p.type;if(!ALLOWED_TYPES.has(type))return false;const values={...p.values,...snapshotValues(type)};if(!validValues(values)){setSync("⚠ Muokattuja arvoja ei tallennettu: projektidata ei läpäissyt tarkistusta.","warn");return false}const previous={type:p.type,values:p.values,updated:p.updated};p.type=type;p.values=values;p.updated=Date.now();if(!save()){p.type=previous.type;p.values=previous.values;p.updated=previous.updated;return false}return true}
 function scheduleAutosave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(autosave,250)}
 function holeLines(raw){const out=[];const add=h=>{if(!h)return;const x=num(h.x),y=num(h.y),d=num(h.diameter??h.d);if(d>0)out.push(`${x};${y};${d}`)};(raw?.parameters?.holes||[]).forEach(add);if(raw?.parameters?.centerHole)add({x:0,y:0,diameter:raw.parameters.centerHole.diameter??raw.parameters.centerHole});for(const op of raw?.operations||[]){if(op?.type==="hole")add(op);if(op?.type==="holes")(op.holes||[]).forEach(add)}return [...new Set(out)]}
 function normalizeV1Values(type,rawValues,material){const sourceMaterial=["PLA","PETG","ASA"].includes(material)?material:["PLA","PETG","ASA"].includes(rawValues?.material)?rawValues.material:"PETG",v={...(rawValues||{}),material:sourceMaterial},set=(key,...aliases)=>{if(v[key]!=null)return;for(const alias of aliases)if(v[alias]!=null){v[key]=v[alias];return}};if(type==="sleeve"){set("sleeveID","insideDiameter");set("sleeveWall","wall");set("sleeveLength","length")}else if(type==="plug"){set("tubeW","width");set("tubeH","height");set("tubeWall","wall");set("plugClear","clearance");set("capThickness","thickness");set("capOverhang","overhang")}else if(type==="plate"){set("plateL","length");set("plateW","width");set("plateT","thickness");const cr=num(v.cornerRadius),ch=num(v.chamfer);if(v.plateCornerStyle==null)v.plateCornerStyle=cr>0?"round":ch>0?"chamfer":"square";set("plateCornerSize","cornerRadius","chamfer")}return v}
 function normalizeChatGPT(raw){if(!raw||![1,2].includes(raw.schemaVersion))return null;const sourceFingerprint=fingerprint(raw);if(raw.schemaVersion===1){const aliases={plug:"plug",sleeve:"sleeve",spike:"spike",plate:"plate"};if(!aliases[raw.partType])return{id:"chatgpt-current",name:raw.projectName||"ChatGPT-suunnitelma",description:`Osatyyppi ${raw.partType||"?"} ei ole vielä tuettu.`,source:"chatgpt",sourceFingerprint,unsupported:true};return{id:"chatgpt-current",name:raw.projectName||"ChatGPT-suunnitelma",description:raw.summary||"ChatGPTissa tehty muokattava suunnitelma",type:aliases[raw.partType],values:normalizeV1Values(aliases[raw.partType],raw.values,raw.material),source:"chatgpt",sourceSchema:1,sourceFingerprint}}
 const t=raw.partType,p=raw.parameters||{},base={id:"chatgpt-current",name:raw.projectName||"ChatGPT-suunnitelma",description:raw.summary||"",source:"chatgpt",sourceSchema:2,sourceFingerprint};
 if(t==="sleeve")return{...base,type:"sleeve",values:{sleeveID:p.insideDiameter,sleeveWall:p.wall??((p.outsideDiameter-p.insideDiameter)/2),sleeveLength:p.length,material:raw.material||"PETG"}};
 if(t==="spike"){const values={nutAf:p.nutAcrossFlats??p.nutAf,clearance:p.clearance??.25,lockAmount:p.lockAmount??.2,lockZ:p.lockZ??7,wall:p.wall,baseHeight:p.baseHeight??24,totalHeight:p.height??p.totalHeight,tipRadius:p.tipRadius??.8,material:raw.material||"ASA"},mark=String(p.monogram??"").trim().toUpperCase();if(mark==="M"){values.monogram="M";values.monogramWidth=p.monogramWidth;values.monogramDepth=p.monogramDepth;values.monogramHeight=p.monogramHeight}return{...base,type:"spike",values}}
 if(t==="endPlug")return{...base,type:"plug",values:{tubeW:p.width,tubeH:p.height,tubeWall:p.wall,plugClear:p.clearance??.25,insertDepth:p.insertDepth,capThickness:p.capThickness??p.thickness??3,capOverhang:p.overhang??1,material:raw.material||"PETG"}};
 if(t==="mountingPlate"){const holes=holeLines(raw),cornerRadius=num(p.cornerRadius),chamfer=num(p.chamfer);return{...base,type:"plate",values:{plateL:p.length,plateW:p.width,plateT:p.thickness,plateHolePattern:holes.length?"custom":"none",plateCustomHoles:holes.join("\n"),plateHoleD:0,plateHoleEdge:10,plateCornerStyle:cornerRadius>0?"round":chamfer>0?"chamfer":"square",plateCornerSize:cornerRadius||chamfer||0,material:raw.material||"PETG"}}}
 if(t==="adapter"){const id1=num(p.insideDiameter1??p.insideDiameter),id2=num(p.insideDiameter2??p.insideDiameter??id1),wall=num(p.wall);const od1=num(p.outsideDiameter1??p.outsideDiameter??(id1+2*wall)),od2=num(p.outsideDiameter2??p.outsideDiameter??(id2+2*wall));return{...base,type:"adapter",values:{adapterLength:num(p.length),adapterID1:id1,adapterID2:id2,adapterOD1:od1,adapterOD2:od2,material:raw.material||"PETG"}}}
 if(t==="enclosure")return{...base,type:"enclosure",values:{enclosureW:num(p.width),enclosureD:num(p.length??p.depth),enclosureH:num(p.height),enclosureWall:num(p.wall??p.thickness),enclosureFloor:num(p.floorThickness??p.thickness??p.wall),material:raw.material||"PETG"}};
 return{...base,description:`${raw.summary||""}${raw.summary?" ":""}Osatyyppi ${t||"?"} on tunnistettu Schema v2 -suunnitelmaksi, mutta sille ei ole vielä muokattavaa editoria.`,unsupported:true}
 }
 async function loadPlans(){const seq=++planLoadSeq;setSync("Päivitetään suunnitelmia…");let base=[],errors=[];try{const r=await fetch(`plans.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const data=await r.json();base=Array.isArray(data.plans)?data.plans:[]}catch(e){errors.push("plans.json: "+e.message)}try{const r=await fetch(`chatgpt_plan.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const c=normalizeChatGPT(await r.json());if(c)base.unshift(c);else errors.push("chatgpt_plan.json: tuntematon skeema")}catch(e){errors.push("chatgpt_plan.json: "+e.message)}if(seq!==planLoadSeq)return;plans=base.length?base:[{id:"light-sign-400",name:"Valokyltti 400 mm",description:"400 mm LED-valokyltti",type:"lightSign",values:{signDiameter:400,signRingWidth:28,signDepth:24,signWall:2.4,diffuserThickness:1.2,starWidth:28,starThickness:4,ledWidth:10,material:"PETG"}}];renderPlans();setSync(errors.length?"⚠ "+errors.join(" • "):`✓ Suunnitelmat päivitetty (${plans.length} kpl).`,errors.length?"warn":"ok");if(!projects.length&&plans.length){const first=plans.find(p=>!p.unsupported&&p.source!=="chatgpt")||plans.find(p=>!p.unsupported&&canOpenPlan(p));if(first)openPlan(first.id)}else if(projects.length){const wanted=activeId||projects[0].id;if(!openProject(wanted)){let opened=false;for(const p of projects){if(p.id===wanted)continue;if(openProject(p.id)){opened=true;break}}if(!opened){activeId="";try{localStorage.setItem(KEY+":active","")}catch{}renderProjects();showInfo(null);setSync("⚠ Tallennetuista projekteista ei löytynyt avattavaa CAD-mallia. Projektit säilytettiin, mutta STL-vienti on estetty.","warn")}}}}
 function downloadProject(){const p=current();if(!p)return alert("Valitse projekti ensin.");if(!autosave())return alert("Viimeisimpiä muutoksia ei voitu tallentaa. Projektivienti keskeytettiin, jotta vanhaa tilaa ei viedä vahingossa.");const copy={format:"AI3D-project",version:1,exportedAt:new Date().toISOString(),project:{...p}};delete copy.project.id;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(copy,null,2)],{type:"application/json"}));a.download=(p.name||"3d-projekti").replace(/[^a-z0-9åäö_-]+/gi,"_")+".ai3d.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function importProject(file){if(!file||file.size>2_000_000)return alert("Projektitiedosto on liian suuri.");const r=new FileReader();r.onload=()=>{const previous=current(),previousId=activeId;let p=null;try{const d=JSON.parse(r.result),src=d?.format==="AI3D-project"?d.project:d;if(!src||!ALLOWED_TYPES.has(src.type)||!validValues(src.values))throw Error("Tiedosto ei ole tuettu tai projektin arvot ovat virheelliset.");p={...src,id:newProjectId(),name:String(src.name||"Tuotu projekti").slice(0,120),description:String(src.description||"Tuotu projekti").slice(0,1000),values:{...src.values},created:Date.now(),updated:Date.now()};applyProject(p);projects.unshift(p);activeId=p.id;if(!save())throw Error("Tuotua projektia ei voitu tallentaa.");renderProjects();showInfo(p);setSync("✓ Projekti tuotu ja CAD-malli tarkistettu onnistuneesti.","ok")}catch(e){if(p)projects=projects.filter(x=>x!==p);activeId=previousId;if(previous)restoreProject(previous);renderProjects();showInfo(previous||null);alert("Projektin tuonti epäonnistui eikä projektia tallennettu: "+e.message)}};r.onerror=()=>alert("Projektitiedostoa ei voitu lukea.");r.readAsText(file)}
 function injectTools(){const side=document.querySelector(".project-sidebar");if(side&&!$("btnReloadPlans")){const box=document.createElement("div");box.style.display="grid";box.style.gap="6px";box.style.margin="8px 0 12px";box.innerHTML='<button id="btnReloadPlans" class="ghost">↻ PÄIVITÄ CHATGPT-SUUNNITELMA</button><button id="btnExportProject" class="ghost">VIE PROJEKTI JSON</button><button id="btnImportProject" class="ghost">TUO PROJEKTI JSON</button><input id="projectImportFile" type="file" accept="application/json,.json" hidden><div id="planSyncStatus" class="plan-sync-status"></div>';side.insertBefore(box,side.querySelector(".section-title"));$("btnReloadPlans").onclick=loadPlans;$("btnExportProject").onclick=downloadProject;$("btnImportProject").onclick=()=>$("projectImportFile").click();$("projectImportFile").onchange=e=>{const f=e.target.files?.[0];if(f)importProject(f);e.target.value=""}}
 const grid=$("fields-plate")?.querySelector(".grid");if(grid&&!$("plateCustomHoles")){const opt=document.createElement("option");opt.value="custom";opt.textContent="Mukautetut reiät";$("plateHolePattern")?.appendChild(opt);const lab=document.createElement("label");lab.style.gridColumn="1 / -1";lab.innerHTML='Mukautetut reiät — yksi per rivi: X;Y;Ø (mm)<textarea id="plateCustomHoles" rows="5" placeholder="-35;-15;6\n35;-15;6\n35;15;6\n-35;15;6"></textarea>';grid.appendChild(lab)}}
 function loadAddon(src,done){const s=document.createElement("script");s.src=src;s.onload=()=>done?.();s.onerror=()=>{setSync("⚠ CAD-lisäosan lataus epäonnistui: "+src,"warn");done?.()};document.body.appendChild(s)}
 document.addEventListener("DOMContentLoaded",()=>{injectTools();migrate();try{projects=JSON.parse(localStorage.getItem(KEY)||"[]");if(!validProjects(projects))projects=[]}catch{projects=[]}activeId=localStorage.getItem(KEY+":active")||projects[0]?.id||"";$("btnNewProject").onclick=newProject;["partType","material"].forEach(id=>$(id)?.addEventListener("change",scheduleAutosave));document.querySelector(".controls")?.addEventListener("input",e=>{if(e.target.matches("input,select,textarea"))scheduleAutosave()});window.addEventListener("pagehide",autosave);loadAddon("parametric_parts.js?v=1.8",()=>loadAddon("plate_custom.js?v=1.6",loadPlans))});
 window.AI3DProjects={openPlan,newProject,active:current,reloadPlans:loadPlans,exportProject:downloadProject};
})();