"use strict";
(()=>{
 const $=id=>document.getElementById(id);
 const fieldMap={
  "Korkeus":"totalHeight","Kokonaiskorkeus":"totalHeight","Mutteriosa":"baseHeight","Sisä Ø":"sleeveID","Seinämä":"sleeveWall","Pituus":"plateL","Leveys":"plateW","Paksuus":"plateT","Upotus":"insertDepth","Päätylevy":"capThickness","M leveys":"monogramWidth","M syvyys":"monogramDepth","M alkaa":"monogramHeight"
 };
 let stage="design",syncing=false;
 function setStage(next){stage=next;document.querySelectorAll(".workflow-step").forEach((e,i)=>{const names=["design","check","print"],n=names[i];e.classList.toggle("active",n===next);e.classList.toggle("done",names.indexOf(n)<names.indexOf(next))})}
 function injectWorkflow(){if($("workflowSteps"))return;const workspace=document.querySelector(".project-workspace");if(!workspace)return;const nav=document.createElement("div");nav.id="workflowSteps";nav.className="workflow-steps";nav.innerHTML='<div class="workflow-step active"><b>1</b><span>SUUNNITTELE</span></div><div class="workflow-line"></div><div class="workflow-step"><b>2</b><span>TARKISTA</span></div><div class="workflow-line"></div><div class="workflow-step"><b>3</b><span>TULOSTA</span></div>';workspace.before(nav)}
 function simplifySpike(){const root=$("fields-spike");if(!root||$("spikeMainFields"))return;const mainIds=["nutAf","totalHeight","wall","monogramWidth","monogramDepth","monogramHeight"],advancedIds=["clearance","lockAmount","lockZ","baseHeight","tipRadius"];
  const mainLabels=mainIds.map(id=>$(id)?.closest("label")).filter(Boolean),advancedLabels=advancedIds.map(id=>$(id)?.closest("label")).filter(Boolean);
  const mainTitle=document.createElement("div");mainTitle.className="section-title";mainTitle.textContent="Päämitat";const main=document.createElement("div");main.id="spikeMainFields";main.className="grid";const details=document.createElement("details");details.id="spikeAdvanced";details.className="advanced-settings";details.innerHTML='<summary>LISÄASETUKSET</summary><div class="grid advanced-grid"></div>';const adv=details.querySelector(".advanced-grid");
  root.replaceChildren(mainTitle,main,details);mainLabels.forEach(x=>main.appendChild(x));advancedLabels.forEach(x=>adv.appendChild(x));
 }
 function simplifyActions(){const actions=document.querySelector(".actions");if(!actions||$("secondaryActions"))return;const gen=$("btnGenerate"),download=$("btnDownload"),fit=$("btnFitTest"),reset=$("btnReset");if(gen)gen.textContent="TARKISTA MALLI";const details=document.createElement("details");details.id="secondaryActions";details.className="secondary-actions";details.innerHTML='<summary>LISÄTOIMINNOT</summary><div class="secondary-actions-body"></div>';const body=details.querySelector("div");if(fit)body.appendChild(fit);if(reset)body.appendChild(reset);actions.appendChild(details);syncPrimaryAction()}
 function syncPrimaryAction(){const gen=$("btnGenerate"),download=$("btnDownload");if(!gen||!download)return;const ready=!download.disabled;if(ready){download.textContent="✓ MALLI VALMIS – LATAA STL";download.classList.add("primary");gen.classList.remove("primary");setStage("print")}else{download.textContent="LATAA STL";download.classList.remove("primary");gen.classList.add("primary");if(stage!=="check")setStage("design")}}
 function simplifyValidation(){const v=$("validation");if(!v||$("validationSummary"))return;const summary=document.createElement("div");summary.id="validationSummary";summary.className="validation-summary";summary.textContent="Malli odottaa tarkistusta.";const details=document.createElement("details");details.id="validationDetails";details.className="validation-details";details.innerHTML="<summary>TARKISTUKSEN TIEDOT</summary>";v.before(summary);v.before(details);details.appendChild(v);
  const update=()=>{if(syncing)return;syncing=true;const dl=$("btnDownload"),text=v.textContent||"",ready=dl&&!dl.disabled;if(ready){summary.className="validation-summary ok";summary.textContent="✓ Malli on teknisesti ehjä ja voidaan viedä STL-tiedostoksi."}else if(text.trim()){summary.className="validation-summary fail";summary.textContent="✕ Mallissa on ongelma. STL-vienti on estetty."}else{summary.className="validation-summary";summary.textContent="Malli odottaa tarkistusta."}syncPrimaryAction();syncing=false};
  new MutationObserver(update).observe(v,{childList:true,subtree:true,characterData:true});update()}
 function linkMeasures(){const overlay=$("measureOverlay");if(!overlay)return;const bind=()=>overlay.querySelectorAll("span").forEach(s=>{if(s.dataset.bound)return;const label=(s.childNodes[0]?.textContent||s.textContent||"").trim();const key=Object.keys(fieldMap).find(k=>label.startsWith(k));const id=key&&fieldMap[key],input=id&&$(id);if(!input)return;s.dataset.bound="1";s.dataset.field=id;s.title="Avaa tätä mittaa vastaava syöttökenttä";s.onclick=()=>{const adv=input.closest("details");if(adv)adv.open=true;input.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>input.focus(),250)}});new MutationObserver(bind).observe(overlay,{childList:true,subtree:true});bind()}
 function watchInputs(){document.addEventListener("input",e=>{if(e.target?.matches?.("input,select,textarea")){const dl=$("btnDownload");if(dl&&!dl.disabled){dl.disabled=true;syncPrimaryAction()}setStage("design")}},true);$("btnGenerate")?.addEventListener("click",()=>setStage("check"),true)}
 function init(){injectWorkflow();simplifySpike();simplifyActions();simplifyValidation();linkMeasures();watchInputs();syncPrimaryAction()}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,180));else setTimeout(init,180);
})();