"use strict";
(()=>{
 const $=id=>document.getElementById(id);
 const fieldMapByType={
  spike:{"Kokonaiskorkeus":"totalHeight","Korkeus":"totalHeight","Mutteriosa":"baseHeight","M leveys":"monogramWidth","M syvyys":"monogramDepth"},
  plug:{"Upotus":"insertDepth","Päätylevy":"capThickness","Putki":"tubeW"},
  sleeve:{"Sisä Ø":"sleeveID","Seinämä":"sleeveWall","Pituus":"sleeveLength"},
  plate:{"Pituus":"plateL","Leveys":"plateW","Paksuus":"plateT","Reuna → keskipiste":"plateHoleEdge","Pyöristys":"plateCornerSize","Viiste":"plateCornerSize"}
 };
 let stage="design",syncing=false,movingM=false,dirty=false;
 function setStage(next){stage=next;document.querySelectorAll(".workflow-step").forEach((e,i)=>{const names=["design","check","print"],n=names[i];e.classList.toggle("active",n===next);e.classList.toggle("done",names.indexOf(n)<names.indexOf(next))})}
 function injectWorkflow(){if($("workflowSteps"))return;const workspace=document.querySelector(".project-workspace");if(!workspace)return;const nav=document.createElement("div");nav.id="workflowSteps";nav.className="workflow-steps";nav.setAttribute("aria-label","Työvaiheet");nav.innerHTML='<div class="workflow-step active"><b>1</b><span>SUUNNITTELE</span></div><div class="workflow-line"></div><div class="workflow-step"><b>2</b><span>TARKISTA</span></div><div class="workflow-line"></div><div class="workflow-step"><b>3</b><span>TULOSTA</span></div>';workspace.before(nav)}
 function moveMFields(){if(movingM)return;const main=$("spikeMainFields");if(!main)return;movingM=true;["monogramWidth","monogramDepth","monogramHeight"].forEach(id=>{const label=$(id)?.closest("label");if(label&&!main.contains(label))main.appendChild(label)});const box=$("mNutParams");if(box&&$("monogramWidth"))box.hidden=true;movingM=false}
 function simplifySpike(){const root=$("fields-spike");if(!root||$("spikeMainFields"))return;const mainIds=["nutAf","totalHeight","wall"],advancedIds=["clearance","lockAmount","lockZ","baseHeight","tipRadius"],mBox=$("mNutParams");
  const mainLabels=mainIds.map(id=>$(id)?.closest("label")).filter(Boolean),advancedLabels=advancedIds.map(id=>$(id)?.closest("label")).filter(Boolean);
  const mainTitle=document.createElement("div");mainTitle.className="section-title";mainTitle.textContent="Päämitat";const main=document.createElement("div");main.id="spikeMainFields";main.className="grid";const details=document.createElement("details");details.id="spikeAdvanced";details.className="advanced-settings";details.innerHTML='<summary>LISÄASETUKSET</summary><div class="grid advanced-grid"></div>';const adv=details.querySelector(".advanced-grid");
  root.replaceChildren(mainTitle,main,details);mainLabels.forEach(x=>main.appendChild(x));advancedLabels.forEach(x=>adv.appendChild(x));if(mBox)root.appendChild(mBox);moveMFields();new MutationObserver(moveMFields).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:["hidden"]})
 }
 function simplifyPlug(){const root=$("fields-plug");if(!root||$("plugMainFields"))return;const mainIds=["tubeW","tubeH","insertDepth","capThickness"],advancedIds=["tubeWall","plugClear","capOverhang"];
  const mainLabels=mainIds.map(id=>$(id)?.closest("label")).filter(Boolean),advancedLabels=advancedIds.map(id=>$(id)?.closest("label")).filter(Boolean);
  const mainTitle=document.createElement("div");mainTitle.className="section-title";mainTitle.textContent="Päämitat";const main=document.createElement("div");main.id="plugMainFields";main.className="grid";const details=document.createElement("details");details.id="plugAdvanced";details.className="advanced-settings";details.innerHTML='<summary>LISÄASETUKSET</summary><div class="grid advanced-grid"></div>';const adv=details.querySelector(".advanced-grid");
  root.replaceChildren(mainTitle,main,details);mainLabels.forEach(x=>main.appendChild(x));advancedLabels.forEach(x=>adv.appendChild(x))
 }
 function simplifyActions(){const actions=document.querySelector(".actions");if(!actions||$("secondaryActions"))return;const gen=$("btnGenerate"),download=$("btnDownload"),fit=$("btnFitTest"),reset=$("btnReset");if(gen)gen.textContent="TARKISTA MALLI";const details=document.createElement("details");details.id="secondaryActions";details.className="secondary-actions";details.innerHTML='<summary>LISÄTOIMINNOT</summary><div class="secondary-actions-body"></div>';const body=details.querySelector("div");if(fit)body.appendChild(fit);if(reset)body.appendChild(reset);actions.appendChild(details);syncPrimaryAction()}
 function syncPrimaryAction(){const gen=$("btnGenerate"),download=$("btnDownload");if(!gen||!download)return;const ready=!download.disabled&&!dirty;if(ready){download.textContent="✓ MALLI VALMIS – LATAA STL";download.classList.add("primary");gen.classList.remove("primary");setStage("print")}else{download.textContent="LATAA STL";download.classList.remove("primary");gen.classList.add("primary");if(stage!=="check")setStage("design")}}
 function setSummary(kind,text){const summary=$("validationSummary");if(!summary)return;summary.className="validation-summary"+(kind?" "+kind:"");summary.textContent=text}
 function simplifyValidation(){const v=$("validation");if(!v||$("validationSummary"))return;const summary=document.createElement("div");summary.id="validationSummary";summary.className="validation-summary";summary.textContent="Malli odottaa tarkistusta.";const details=document.createElement("details");details.id="validationDetails";details.className="validation-details";details.innerHTML="<summary>TARKISTUKSEN TIEDOT</summary>";v.before(summary);v.before(details);details.appendChild(v);
  const update=()=>{if(syncing)return;syncing=true;const dl=$("btnDownload"),text=v.textContent||"",hasFail=!!v.querySelector(".check.fail");if((dl&&!dl.disabled)||hasFail)dirty=false;const ready=dl&&!dl.disabled&&!dirty;if(dirty){setSummary("","Mitat muuttuivat. Tarkista malli uudelleen.")}else if(ready){setSummary("ok","✓ Malli on teknisesti ehjä ja voidaan viedä STL-tiedostoksi.")}else if(hasFail||text.trim()){setSummary("fail","✕ Mallissa on ongelma. STL-vienti on estetty.")}else{setSummary("","Malli odottaa tarkistusta.")}syncPrimaryAction();syncing=false};
  new MutationObserver(update).observe(v,{childList:true,subtree:true,characterData:true});window.AI3DGuidedUI={refreshValidation:update};update()}
 function linkMeasures(){const overlay=$("measureOverlay");if(!overlay)return;const bind=()=>{const type=$("partType")?.value||"";const map=fieldMapByType[type]||{};overlay.querySelectorAll("span").forEach(s=>{delete s.dataset.bound;delete s.dataset.field;s.removeAttribute("title");s.onclick=null;const label=(s.childNodes[0]?.textContent||s.textContent||"").trim();const key=Object.keys(map).sort((a,b)=>b.length-a.length).find(k=>label.startsWith(k));const id=key&&map[key],input=id&&$(id);if(!input)return;s.dataset.bound="1";s.dataset.field=id;s.title="Avaa tätä mittaa vastaava syöttökenttä";s.onclick=()=>{const adv=input.closest("details");if(adv)adv.open=true;input.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>input.focus(),250)}})};new MutationObserver(bind).observe(overlay,{childList:true,subtree:true});$("partType")?.addEventListener("change",()=>setTimeout(bind,0));bind()}
 function watchInputs(){document.addEventListener("input",e=>{if(!e.target?.matches?.("input,select,textarea")||!e.target.closest(".controls"))return;dirty=true;const dl=$("btnDownload");if(dl&&!dl.disabled)dl.disabled=true;setSummary("","Mitat muuttuivat. Tarkista malli uudelleen.");syncPrimaryAction();setStage("design")},true);$("btnGenerate")?.addEventListener("click",()=>{dirty=false;setStage("check");setTimeout(()=>window.AI3DGuidedUI?.refreshValidation?.(),0)},true)}
 function init(){injectWorkflow();simplifySpike();simplifyPlug();simplifyActions();simplifyValidation();linkMeasures();watchInputs();syncPrimaryAction()}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,180));else setTimeout(init,180);
})();