import express from "express";
import cors from "cors";
const app=express();const PORT=Number(process.env.PORT||8787);const OPENAI_API_KEY=process.env.OPENAI_API_KEY;const MODEL=process.env.OPENAI_MODEL||"gpt-5.6-terra";const ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||"https://vilmusenahojuha-stack.github.io";
app.use(cors({origin(origin,cb){if(!origin||origin===ALLOWED_ORIGIN||origin.startsWith("http://localhost:")||origin.startsWith("http://127.0.0.1:"))return cb(null,true);cb(new Error("Origin not allowed"));}}));app.use(express.json({limit:"12mb"}));
function requireKey(req,res,next){if(!OPENAI_API_KEY)return res.status(503).json({error:"OPENAI_API_KEY puuttuu palvelimelta."});next()}
function cleanJson(text){const s=String(text||"").trim().replace(/^```json\s*/i,"").replace(/^```\s*/,"").replace(/```$/," ").trim();return JSON.parse(s)}
async function response(input,json=true){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:MODEL,input})});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`OpenAI API ${r.status}`);const text=data.output_text||data.output?.flatMap(x=>x.content||[]).map(x=>x.text).filter(Boolean).join("\n")||"";return json?cleanJson(text):text.trim()}
app.get("/health",(req,res)=>res.json({ok:true,model:MODEL,keyConfigured:Boolean(OPENAI_API_KEY)}));
app.post("/api/chat",requireKey,async(req,res)=>{try{const {messages=[],projectName="3D-projekti"}=req.body||{};const history=messages.slice(-24).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.text||"").slice(0,4000)}));const instruction=`Olet AI 3D Studion suomalainen 3D-suunnitteluavustaja projektissa "${projectName}". Keskustele lyhyesti ja käytännöllisesti. Tavoite on tehdä oikeasti tulostettava CAD-osa. Älä arvaa kriittisiä fyysisiä mittoja. Kysy puuttuvat mitat yksi tai muutama kerrallaan. Kun mitat riittävät, kerro että CAD-ehdotus voidaan muodostaa. Tuetut nykyiset osat: piikkimutterinsuojus, suorakaideputken päätytulppa, holkki/soviterengas ja levy/kiinnike, jossa keskireikä tai 4 symmetristä reikää. Jos käyttäjä pyytää muuta osaa, auta suunnittelussa mutta kerro rehellisesti ettei nykyinen CAD-moottori ehkä vielä generoi sitä. Materiaalit PLA, PETG, ASA. Älä väitä mallia luoduksi ennen CAD-moottorin hyväksyntää.`;const out=await response([{role:"developer",content:instruction},...history],false);res.json({reply:out})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/image/analyze",requireKey,async(req,res)=>{try{const{image,note=""}=req.body||{};if(typeof image!=="string"||!image.startsWith("data:image/"))return res.status(400).json({error:"Kuva puuttuu tai formaatti ei kelpaa."});const prompt=`Olet mekaanisen 3D-tulostuksen CAD-avustaja. Analysoi kuva geometrisesti. Älä arvaa mittakaavaa. Tunnista lähin: spike, plug, sleeve, plate tai unknown. Kysy vain malliin tarvittavat fyysiset mitat. Palauta VAIN JSON {"summary":"...","partType":"spike|plug|sleeve|plate|unknown","confidence":0.0,"questions":[{"key":"...","label":"...","example":"..."}],"visibleFeatures":[],"warnings":[]}. Lisätieto: ${note||"ei"}`;res.json(await response([{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:image}]}]))}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/image/finalize",requireKey,async(req,res)=>{try{const{analysis,answers={},note=""}=req.body||{};if(!analysis)return res.status(400).json({error:"Kuva-analyysi puuttuu."});const prompt=`Muunna analyysi ja mitat CAD-parametreiksi. Älä keksi kriittisiä mittoja. spike: nutAf,clearance,lockAmount,lockZ,wall,baseHeight,totalHeight,tipRadius. plug: tubeW,tubeH,tubeWall,plugClear,insertDepth,capThickness,capOverhang. sleeve: sleeveID,sleeveWall,sleeveLength. plate: plateL,plateW,plateT,plateHolePattern,plateHoleD,plateHoleEdge,plateCornerStyle,plateCornerSize. Palauta VAIN JSON {"partType":"spike|plug|sleeve|plate","values":{},"material":"PLA|PETG|ASA","missing":[],"explanation":"...","warnings":[]}. Analyysi:${JSON.stringify(analysis)} Vastaukset:${JSON.stringify(answers)} Lisätieto:${note}`;const result=await response(prompt);if(result.missing?.length)return res.status(422).json({error:`Tarvitaan vielä: ${result.missing.join(", ")}`,result});res.json(result)}catch(e){res.status(500).json({error:e.message})}});
app.use((err,req,res,next)=>res.status(403).json({error:err.message||"Pyyntö estettiin."}));app.listen(PORT,()=>console.log(`AI 3D Studio backend listening on ${PORT}`));