"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const ROOT=path.resolve(__dirname,"..");
const elements={status:{textContent:"",disabled:false},validation:{querySelector(){return null}},btnDownload:{disabled:false},btnFitTest:{disabled:false},btnCentauriStl:{disabled:false},dimensions:{textContent:"100 × 50 × 4 mm"}};
const document={readyState:"complete",getElementById:id=>elements[id]||null};
let generated=0;
const window={AI3D:{setPart(){return true}},AI3DPlanV2CAD:{apply(){generated++;return true}}};
const context={window,document,console,Number,Math,Set,Error,currentMesh:{stale:true},currentFitMesh:{stale:true},draw(){}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,"cad_apply_guard.js"),"utf8"),context,{filename:"cad_apply_guard.js"});
assert.throws(()=>window.AI3DPlanV2CAD.apply({schemaVersion:2,partType:"adapter",material:"ABS",parameters:{length:30,insideDiameter:20,wall:3}}),/tulostusmateriaalia ei tueta/);
assert.equal(generated,0,"unsupported imported material must be rejected before CAD generation");
assert.equal(context.currentMesh,null,"rejected import must clear stale preview mesh");
assert.equal(context.currentFitMesh,null,"rejected import must clear stale fit mesh");
assert.equal(elements.btnDownload.disabled,true,"rejected import must disable STL export");
assert.equal(elements.btnCentauriStl.disabled,true,"rejected import must disable Centauri export");
assert.equal(elements.dimensions.textContent,"–","rejected import must clear stale dimensions");
assert.equal(window.AI3DPlanV2CAD.apply({schemaVersion:2,partType:"adapter",material:"PETG",parameters:{length:30,insideDiameter:20,wall:3}}),true);
assert.equal(generated,1,"supported material must still reach CAD generation");
console.log("CAD plan material preflight regression: ok");
