"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/cad_plan_v2\.js\?v=1\.5/,"index.html must load the current CAD v2 core cache version");
assert.match(index,/cad_v2_editor\.js\?v=1\.5/,"index.html must load the current CAD v2 editor cache version");
assert.match(index,/plan_preflight\.js\?v=1\.13/,"index.html must load the current ChatGPT preflight cache version");
assert.match(index,/plan_operation_guard\.js\?v=1\.14/,"index.html must load the current ChatGPT operation guard cache version");
assert.match(index,/project_tools\.js\?v=1\.14/,"index.html must load the current project tools cache version");
assert.match(index,/storage_commit_guard\.js\?v=1\.9/,"index.html must load the current storage commit guard cache version");
assert.match(index,/preview_guard\.js\?v=1\.7/,"index.html must load the current 3D preview guard cache version");
assert.match(runtime,/\["cadV2Core",\(\)=>!cadV2CoreReady\(\),"cad_plan_v2\.js\?v=1\.5"\]/,"runtime fallback must use the same CAD v2 core version");
assert.match(runtime,/\["cadV2",\(\)=>!cadV2EditorReady\(\),"cad_v2_editor\.js\?v=1\.5"\]/,"runtime fallback must use the same CAD v2 editor version");
assert.match(runtime,/"plan_preflight\.js\?v=1\.13"/,"runtime fallback must use the same ChatGPT preflight version");
assert.match(runtime,/"plan_operation_guard\.js\?v=1\.14"/,"runtime fallback must use the same ChatGPT operation guard version");
assert.match(runtime,/\["projectTools",\(\)=>!projectToolsReady\(\),"project_tools\.js\?v=1\.14"\]/,"runtime fallback must use the same project tools version");
assert.match(runtime,/\["storageCommitGuard",\(\)=>!storageCommitGuardReady\(\),"storage_commit_guard\.js\?v=1\.9"\]/,"runtime fallback must use the same storage commit guard version");
assert.match(runtime,/\["previewGuard",\(\)=>!previewGuardReady\(\),"preview_guard\.js\?v=1\.7"\]/,"runtime fallback must use the same 3D preview guard version");
assert.match(runtime,/\["centauri",\(\)=>!centauriReady\(\),"centauri\.js\?v=1\.9"\]/,"runtime fallback must use the same Centauri profile version");
assert.match(runtime,/\["CAD v2 -ydin",cadV2CoreReady\]/,"runtime health must report a missing CAD v2 core");
assert.match(runtime,/\["CAD v2 -editori",cadV2EditorReady\]/,"runtime health must report a missing CAD v2 editor");
assert.match(runtime,/\["projektityökalut",projectToolsReady\]/,"runtime health must report missing project tools");
assert.match(runtime,/\["projektitallennuksen varmennus",storageCommitGuardReady\]/,"runtime health must report a missing storage commit guard");
assert.match(runtime,/\["3D-esikatselun suojaus",previewGuardReady\]/,"runtime health must report a missing 3D preview guard");
assert.match(runtime,/\["Centauri-profiili",centauriReady\]/,"runtime health must report a missing Centauri profile");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={
 readyState:"complete",hidden:false,
 getElementById:id=>elements[id]||null,
 querySelector:()=>null,
 createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},
 head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},
 addEventListener(){}
};
const window={AI3D:{setPart(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth,"runtime health API must initialize");
assert.ok(window.AI3DRuntimeHealth.missing().includes("CAD v2 -ydin"),"missing CAD v2 core must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("CAD v2 -editori"),"missing CAD v2 editor must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("ChatGPT-ennakkotarkistus"),"missing ChatGPT preflight must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("ChatGPT-operaatiotarkistus"),"missing ChatGPT operation guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("projektityökalut"),"missing project tools must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("projektitallennuksen varmennus"),"missing storage commit guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("3D-esikatselun suojaus"),"missing 3D preview guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("Centauri-profiili"),"missing Centauri profile must be visible in health status");
window.AI3DRuntimeHealth.retryDependencies();
const core=appended.find(s=>s.dataset.ai3dCadFallback==="cadV2Core");
assert.ok(core,"manual dependency retry must append a CAD v2 core recovery script");
assert.match(core.src,/^cad_plan_v2\.js\?v=1\.5&healthRetry=\d+$/,"CAD v2 core recovery must be cache-busted without changing its pinned version");
const v2=appended.find(s=>s.dataset.ai3dCadFallback==="cadV2");
assert.ok(v2,"manual dependency retry must append a CAD v2 editor recovery script");
assert.match(v2.src,/^cad_v2_editor\.js\?v=1\.5&healthRetry=\d+$/,"CAD v2 editor recovery must be cache-busted without changing its pinned version");
const preflight=appended.find(s=>s.dataset.ai3dCadFallback==="planPreflight");
assert.ok(preflight,"manual dependency retry must append a ChatGPT preflight recovery script");
assert.match(preflight.src,/^plan_preflight\.js\?v=1\.13&healthRetry=\d+$/,"ChatGPT preflight recovery must be cache-busted without changing its pinned version");
const operations=appended.find(s=>s.dataset.ai3dCadFallback==="planOperations");
assert.ok(operations,"manual dependency retry must append a ChatGPT operation guard recovery script");
assert.match(operations.src,/^plan_operation_guard\.js\?v=1\.14&healthRetry=\d+$/,"ChatGPT operation guard recovery must be cache-busted without changing its pinned version");
const projectTools=appended.find(s=>s.dataset.ai3dCadFallback==="projectTools");
assert.ok(projectTools,"manual dependency retry must append a project tools recovery script");
assert.match(projectTools.src,/^project_tools\.js\?v=1\.14&healthRetry=\d+$/,"project tools recovery must be cache-busted without changing its pinned version");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectTools,"missing","project tools state must stay missing until all required controls exist");
elements.btnDuplicateProject={};elements.btnExportAllProjects={};elements.btnImportAllProjects={};elements.btnRestoreProjects={};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectTools,"ready","project tools state must become ready only when its required controls exist");
const storageCommit=appended.find(s=>s.dataset.ai3dCadFallback==="storageCommitGuard");
assert.ok(storageCommit,"manual dependency retry must append a storage commit guard recovery script");
assert.match(storageCommit.src,/^storage_commit_guard\.js\?v=1\.9&healthRetry=\d+$/,"storage commit guard recovery must be cache-busted without changing its pinned version");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().storageCommitGuard,"missing","storage commit guard state must stay missing until verify API exists");
window.AI3DStorageCommitGuard={verify(){return true}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().storageCommitGuard,"ready","storage commit guard state must become ready only when verify API exists");
const preview=appended.find(s=>s.dataset.ai3dCadFallback==="previewGuard");
assert.ok(preview,"manual dependency retry must append a 3D preview guard recovery script");
assert.match(preview.src,/^preview_guard\.js\?v=1\.7&healthRetry=\d+$/,"3D preview guard recovery must be cache-busted without changing its pinned version");
const centauri=appended.find(s=>s.dataset.ai3dCadFallback==="centauri");
assert.ok(centauri,"manual dependency retry must append a Centauri recovery script");
assert.strictEqual(centauri.dataset.ai3dCentauri,"1","Centauri recovery must keep the shared loader marker");
assert.match(centauri.src,/^centauri\.js\?v=1\.9&healthRetry=\d+$/,"Centauri recovery script must be cache-busted without changing its pinned profile version");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().previewGuard,"missing","3D preview guard state must stay missing until its complete API exists");
window.AI3DPreviewGuard={clear(){},check(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().previewGuard,"missing","partial 3D preview guard API must not be treated as ready");
window.AI3DPreviewGuard.failureReason=()=>"";
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().previewGuard,"ready","3D preview guard state must become ready only when its complete API exists");
let safeInstalls=0,refreshes=0;
window.AI3DCentauriStateGuard={installSafeCheck(){safeInstalls++},refresh(clearDirty){assert.strictEqual(clearDirty,true);refreshes++}};
window.CentauriProfile={check(){},bounds(){},printability(){}};
assert.doesNotThrow(()=>centauri.onload(),"late Centauri recovery must not fail even when state recovery hooks run");
assert.strictEqual(safeInstalls,1,"late-loaded Centauri profile must be wrapped by the state guard immediately");
assert.strictEqual(refreshes,1,"late-loaded Centauri profile must trigger a fresh compatibility check immediately");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadV2,"missing","combined CAD v2 state must stay missing while core/editor are unavailable");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadV2Core,"missing","dependency state must expose a missing CAD v2 core");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().planPreflight,"missing","dependency state must expose a missing ChatGPT preflight");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().planOperations,"missing","dependency state must expose a missing ChatGPT operation guard");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriProfile,"ready","dependency state must see the recovered Centauri profile as ready");
window.AI3DPlanV2CAD={apply(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadV2Core,"ready","CAD v2 core state must become ready only when its apply API exists");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadV2,"missing","combined CAD v2 state must still require the editor API");
window.AI3DV2Editor={apply(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadV2,"ready","combined CAD v2 state must require both core and editor APIs");
window.AI3DPlanPreflight={validate(){},run(){},getLastResult(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().planPreflight,"ready","ChatGPT preflight state must become ready only when its required API exists");
window.AI3DPlanOperationGuard={validate(){},run(){},getLastResult(){},isAllowed(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().planOperations,"ready","ChatGPT operation guard state must become ready only when its required API exists");
console.log("CAD v2, ChatGPT guards, project tools, storage commit guard, 3D preview and Centauri runtime recovery regression: ok");