"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const ROOT=path.resolve(__dirname,"..");
function el(extra={}){return{value:"",valueAsNumber:NaN,min:"",max:"",defaultValue:"",hidden:false,disabled:false,textContent:"",innerHTML:"",style:{},querySelector(){return null},querySelectorAll(){return[]},insertAdjacentHTML(){},appendChild(){},...extra}}
function fixture(rawApply){
 const elements={partType:el({value:"adapter",onchange:null}),"fields-plate":el(),"fields-adapter":el(),"fields-enclosure":el(),btnGenerate:el({onclick:null}),material:el({value:"PETG"}),status:el(),validation:el(),btnDownload:el(),btnFitTest:el(),btnCentauriStl:el(),dimensions:el({textContent:"26 × 26 × 30 mm"}),partTitle:el(),adapterLength:el({valueAsNumber:30,min:"2",max:"5000"}),adapterID1:el({valueAsNumber:20,min:"0.1",max:"5000"}),adapterID2:el({valueAsNumber:20,min:"0.1",max:"5000"}),adapterOD1:el({valueAsNumber:26,min:"0.1",max:"5000"}),adapterOD2:el({valueAsNumber:26,min:"0.1",max:"5000"}),enclosureW:el({valueAsNumber:80,min:"3",max:"5000"}),enclosureD:el({valueAsNumber:60,min:"3",max:"5000"}),enclosureH:el({valueAsNumber:30,min:"3",max:"5000"}),enclosureWall:el({valueAsNumber:2.4,min:"0.8",max:"5000"}),enclosureFloor:el({valueAsNumber:2.4,min:"0.8",max:"5000"})};
 const partFields=[elements["fields-plate"],elements["fields-adapter"],elements["fields-enclosure"]],document={getElementById:id=>elements[id]||null,querySelectorAll:sel=>sel===".part-fields"?partFields:[],createElement:()=>el()},window={AI3D:{setPart(){return true}},AI3DPlanV2CAD:{apply:rawApply}},context={window,document,console,Number,Math,Set,Error,Promise,Object,String,Array,currentMesh:{old:true},currentFitMesh:{old:true},draw(){}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,"cad_v2_editor.js"),"utf8"),context,{filename:"cad_v2_editor.js"});return{window,elements,context};
}
function deferred(){let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej});return{promise,resolve,reject}}
async function main(){
 let resolveSuccess;const success=fixture(()=>new Promise(resolve=>{resolveSuccess=resolve}));const pending=success.window.AI3DV2Editor.apply("adapter");assert.ok(pending&&typeof pending.then==="function");resolveSuccess({ok:true});assert.equal(await pending,true);
 let resolveFalse;const rejected=fixture(()=>new Promise(resolve=>{resolveFalse=resolve}));rejected.elements.btnDownload.disabled=false;rejected.elements.btnCentauriStl.disabled=false;const falseResult=rejected.window.AI3DV2Editor.apply("adapter");resolveFalse(false);assert.equal(await falseResult,false);assert.equal(rejected.context.currentMesh,null);assert.equal(rejected.elements.btnDownload.disabled,true);assert.equal(rejected.elements.btnCentauriStl.disabled,true);
 const failed=fixture(()=>Promise.reject(Error("myöhäinen CAD-virhe")));assert.equal(await failed.window.AI3DV2Editor.apply("adapter"),false);assert.match(failed.elements.status.textContent,/myöhäinen CAD-virhe/);
 let resolveSetPart;const imported=fixture(()=>new Promise(resolve=>{resolveSetPart=resolve}));const setPartResult=imported.window.AI3D.setPart("adapter",{material:"PETG",adapterLength:30,adapterID1:20,adapterID2:20,adapterOD1:26,adapterOD2:26});resolveSetPart(false);await assert.rejects(setPartResult,/CAD-moottori hylkäsi mallin|^Virhe:/);
 const a=deferred(),b=deferred(),queue=[a,b];const raced=fixture(()=>queue.shift().promise);raced.elements.btnDownload.disabled=false;raced.elements.btnCentauriStl.disabled=false;const old=raced.window.AI3DV2Editor.apply("adapter"),newest=raced.window.AI3DV2Editor.apply("adapter");b.resolve(true);assert.equal(await newest,true);raced.context.currentMesh={newest:true};raced.context.currentFitMesh={newest:true};raced.elements.btnDownload.disabled=false;raced.elements.btnCentauriStl.disabled=false;a.reject(Error("vanha CAD-virhe"));assert.equal(await old,false);assert.deepEqual(raced.context.currentMesh,{newest:true},"stale async failure must not clear the newest mesh");assert.deepEqual(raced.context.currentFitMesh,{newest:true},"stale async failure must not clear the newest fit mesh");assert.equal(raced.elements.btnDownload.disabled,false,"stale async failure must not disable newest STL export");assert.equal(raced.elements.btnCentauriStl.disabled,false,"stale async failure must not disable newest Centauri export");
 const pa=deferred(),pb=deferred(),plans=[pa,pb],synced=fixture(()=>plans.shift().promise);const planA={schemaVersion:2,partType:"adapter",material:"PETG",parameters:{length:31,insideDiameter1:20,insideDiameter2:20,outsideDiameter1:27,outsideDiameter2:27}},planB={schemaVersion:2,partType:"adapter",material:"PETG",parameters:{length:44,insideDiameter1:22,insideDiameter2:22,outsideDiameter1:30,outsideDiameter2:30}};const applyA=synced.window.AI3DPlanV2CAD.apply(planA),applyB=synced.window.AI3DPlanV2CAD.apply(planB);pb.resolve(true);await applyB;pa.resolve(true);await applyA;assert.equal(synced.elements.adapterLength.value,44,"stale ChatGPT plan success must not overwrite newest editor values");assert.equal(synced.elements.adapterID1.value,22);
 console.log("CAD v2 editor async regression: ok");
}
main().catch(error=>{console.error(error);process.exitCode=1});
