"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/centauri_orientation\.js\?v=1\.6/,"index must load current Centauri orientation version");
assert.match(index,/runtime_health_guard\.js\?v=1\.20/,"index must invalidate runtime health cache after orientation recovery changes");
assert.match(runtime,/\["centauriOrientation",\(\)=>!centauriOrientationReady\(\),"centauri_orientation\.js\?v=1\.6"\]/,"runtime fallback must pin the same Centauri orientation version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},CentauriProfile:{check(){},bounds(){},printability(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("tulostusasennon arvio"),"missing Centauri orientation module must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriOrientation,"missing","orientation dependency must start missing");
window.AI3DRuntimeHealth.retryDependencies();
const orientation=appended.find(s=>s.dataset.ai3dCadFallback==="centauriOrientation");
assert.ok(orientation,"manual dependency retry must append a Centauri orientation recovery script");
assert.match(orientation.src,/^centauri_orientation\.js\?v=1\.6&healthRetry=\d+$/,"orientation recovery must be cache-busted without changing pinned version");
window.CentauriOrientation={analyse(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriOrientation,"missing","partial orientation API must not be treated as ready");
window.CentauriOrientation={analyse(){},render(){},stability(){}};
orientation.onload();
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriOrientation,"ready","full orientation API must become ready after recovery");
console.log("Centauri orientation runtime recovery regression: ok");
