"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/printability_summary\.js\?v=1\.3/,"index must load current printability summary version");
assert.match(index,/fit_calibration\.js\?v=1\.1/,"index must load current fit calibration version");
assert.match(index,/runtime_health_guard\.js\?v=1\.23/,"index must invalidate runtime health cache after Centauri panel recovery changes");
assert.match(runtime,/\["printability",\(\)=>!printabilityReady\(\),"printability_summary\.js\?v=1\.3"\]/,"runtime fallback must pin current printability summary version");
assert.match(runtime,/\["fitCalibration",\(\)=>!fitCalibrationReady\(\),"fit_calibration\.js\?v=1\.1"\]/,"runtime fallback must pin current fit calibration version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},CentauriProfile:{check(){},bounds(){},printability(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("tulostettavuusarvio"),"missing printability summary must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("sovituskalibrointi"),"missing fit calibration must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().printability,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().fitCalibration,"missing");
window.AI3DRuntimeHealth.retryDependencies();
const printability=appended.find(s=>s.dataset.ai3dCadFallback==="printability");
const fit=appended.find(s=>s.dataset.ai3dCadFallback==="fitCalibration");
assert.ok(printability,"manual dependency retry must append printability recovery script");
assert.ok(fit,"manual dependency retry must append fit calibration recovery script");
assert.match(printability.src,/^printability_summary\.js\?v=1\.3&healthRetry=\d+$/);
assert.match(fit.src,/^fit_calibration\.js\?v=1\.1&healthRetry=\d+$/);
window.AI3DPrintability={render(){},componentInfo(){}};
window.AI3DFitCalibration={render(){},getCorrection(){},getSuggestionFor(){}};
printability.onload();fit.onload();
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().printability,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().fitCalibration,"ready");
console.log("Centauri panel runtime recovery regression: ok");