"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/centauri_state_guard\.js\?v=1\.6/,"index must load current Centauri state guard version");
assert.match(index,/runtime_health_guard\.js\?v=1\.19/,"index must invalidate the runtime health guard cache after Centauri state recovery support changes");
assert.match(runtime,/\["centauriState",\(\)=>!centauriStateReady\(\),"centauri_state_guard\.js\?v=1\.6"\]/,"runtime fallback must pin the same Centauri state guard version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},CentauriProfile:{check(){},bounds(){},printability(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("Centauri-tilavahti"),"missing Centauri state guard must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriState,"missing","Centauri state guard must start missing");
window.AI3DRuntimeHealth.retryDependencies();
const state=appended.find(s=>s.dataset.ai3dCadFallback==="centauriState");
assert.ok(state,"manual dependency retry must append a Centauri state guard recovery script");
assert.match(state.src,/^centauri_state_guard\.js\?v=1\.6&healthRetry=\d+$/,"Centauri state guard recovery must be cache-busted without changing pinned version");
let installed=0,refreshed=0;
window.AI3DCentauriStateGuard={refresh(force){if(force)refreshed++},isDirty(){return false},installSafeCheck(){installed++}};
state.onload();
assert.strictEqual(installed,1,"recovered state guard must install the safe Centauri check");
assert.strictEqual(refreshed,1,"recovered state guard must refresh compatibility immediately");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().centauriState,"ready","Centauri state guard state must become ready after recovery");
console.log("Centauri state runtime recovery regression: ok");
