"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/mesh_integrity_guard\.js\?v=1\.6/,"index must load current mesh integrity guard version");
assert.match(runtime,/\["meshIntegrity",\(\)=>!meshIntegrityReady\(\),"mesh_integrity_guard\.js\?v=1\.6"\]/,"runtime fallback must pin the same mesh integrity version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("mesh-eheystarkistus"),"missing mesh integrity guard must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().meshIntegrity,"missing","mesh integrity state must start missing");
window.AI3DRuntimeHealth.retryDependencies();
const mesh=appended.find(s=>s.dataset.ai3dCadFallback==="meshIntegrity");
assert.ok(mesh,"manual dependency retry must append a mesh integrity recovery script");
assert.match(mesh.src,/^mesh_integrity_guard\.js\?v=1\.6&healthRetry=\d+$/,"mesh integrity recovery must be cache-busted without changing the pinned version");
window.AI3DMeshIntegrity={check(){},checkFit(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().meshIntegrity,"missing","partial mesh integrity API must not be treated as ready");
window.AI3DMeshIntegrity.inspect=()=>"";
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().meshIntegrity,"ready","mesh integrity state must require check, checkFit and inspect APIs");
console.log("Mesh integrity runtime recovery regression: ok");
