"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.resolve(__dirname,"..","printability_summary.js"),"utf8");
const window={};
const document={readyState:"loading",getElementById(){return null},addEventListener(){}};
const context={window,document,console,Int32Array,Map,Number,Math,Array,Object,String,Set};
vm.createContext(context);vm.runInContext(source,context,{filename:"printability_summary.js"});
const componentInfo=window.AI3DPrintability?.componentInfo;
assert.equal(typeof componentInfo,"function","printability component analysis must be available");
const v=(x,y,z)=>({x,y,z});
const o=v(0,0,0),a=v(1,0,0),b=v(0,1,0),c=v(0,0,1),d=v(-1,0,0),e=v(0,-1,0),f=v(0,0,-1);
const tetraA=[[o,a,b],[o,c,a],[o,b,c],[a,c,b]];
const tetraB=[[o,e,d],[o,d,f],[o,f,e],[d,e,f]];
const pointTouch=componentInfo({triangles:[...tetraA,...tetraB]});
assert.equal(pointTouch.count,2,"closed shells that touch only at one vertex must remain separate printability components");
assert.deepEqual(Array.from(pointTouch.sizes),[4,4],"point-touching tetrahedra must keep independent triangle groups");
const sharedEdge=componentInfo({triangles:[[o,a,b],[a,o,e]]});
assert.equal(sharedEdge.count,1,"triangles sharing a complete edge must be treated as one component");
const disjoint=componentInfo({triangles:[[o,a,b],[d,e,f]]});
assert.equal(disjoint.count,2,"geometrically disjoint triangles must remain separate components");
console.log("printability component edge-connectivity regression: ok");
