"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/cad_apply_guard\.js\?v=1\.4/,"index must load current CAD apply guard version");
assert.match(index,/project_open_guard\.js\?v=1\.3/,"index must load current project open guard version");
assert.match(index,/storage_recovery\.js\?v=1\.12/,"index must load current project storage recovery version");
assert.match(index,/ui_simplify\.js\?v=1\.4/,"index must load current guided UI helper version");
assert.match(index,/measure_focus_guard\.js\?v=1\.0/,"index must load current measure focus guard version");
assert.match(index,/runtime_health_guard\.js\?v=1\.21/,"index must invalidate runtime health cache after guided UI recovery changes");
assert.match(runtime,/\["cadApplyGuard",\(\)=>!cadApplyGuardReady\(\),"cad_apply_guard\.js\?v=1\.4"\]/,"runtime fallback must pin current CAD apply guard version");
assert.match(runtime,/\["projectOpenGuard",\(\)=>!projectOpenGuardReady\(\),"project_open_guard\.js\?v=1\.3"\]/,"runtime fallback must pin current project open guard version");
assert.match(runtime,/\["storageRecovery",\(\)=>!storageRecoveryReady\(\),"storage_recovery\.js\?v=1\.12"\]/,"runtime fallback must pin current project storage recovery version");
assert.match(runtime,/\["guidedUI",\(\)=>!guidedUIReady\(\),"ui_simplify\.js\?v=1\.4"\]/,"runtime fallback must pin current guided UI helper version");
assert.match(runtime,/\["measureFocus",\(\)=>!measureFocusReady\(\),"measure_focus_guard\.js\?v=1\.0"\]/,"runtime fallback must pin current measure focus guard version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("CAD-sovellussuoja"),"missing CAD apply guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("projektin avaussuoja"),"missing project open guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("projektitallennuksen palautus"),"missing project storage recovery must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("ohjattu käyttöliittymä"),"missing guided UI helper must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("mittakentän ohjaus"),"missing 3D measure focus guard must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectOpenGuard,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().storageRecovery,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().guidedUI,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().measureFocus,"missing");
window.AI3DRuntimeHealth.retryDependencies();
const cad=appended.find(s=>s.dataset.ai3dCadFallback==="cadApplyGuard");
const project=appended.find(s=>s.dataset.ai3dCadFallback==="projectOpenGuard");
const storage=appended.find(s=>s.dataset.ai3dCadFallback==="storageRecovery");
const guided=appended.find(s=>s.dataset.ai3dCadFallback==="guidedUI");
const measure=appended.find(s=>s.dataset.ai3dCadFallback==="measureFocus");
assert.ok(cad,"manual dependency retry must append CAD apply guard recovery script");
assert.ok(project,"manual dependency retry must append project open guard recovery script");
assert.ok(storage,"manual dependency retry must append project storage recovery script");
assert.ok(guided,"manual dependency retry must append guided UI recovery script");
assert.ok(measure,"manual dependency retry must append 3D measure focus recovery script");
assert.match(cad.src,/^cad_apply_guard\.js\?v=1\.4&healthRetry=\d+$/);
assert.match(project.src,/^project_open_guard\.js\?v=1\.3&healthRetry=\d+$/);
assert.match(storage.src,/^storage_recovery\.js\?v=1\.12&healthRetry=\d+$/);
assert.match(guided.src,/^ui_simplify\.js\?v=1\.4&healthRetry=\d+$/);
assert.match(measure.src,/^measure_focus_guard\.js\?v=1\.0&healthRetry=\d+$/);
window.AI3DCADApplyGuard={check(){},wrapV2(){}};
window.AI3DGuidedUI={refreshValidation(){}};
window.AI3DMeasureFocus={highlight(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"missing","partial CAD guard API must not be accepted");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().guidedUI,"missing","guided UI API without its required DOM must not be accepted");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().measureFocus,"missing","partial measure focus API must not be accepted");
window.AI3DCADApplyGuard.validatePlanHoleBounds=()=>true;
window.AI3D.__applyGuard=true;
window.AI3DProjectOpenGuard={check(){}};
window.AI3DStorageRecovery={checked:true,recovered:false,error:""};
elements.workflowSteps={};elements.validationSummary={};elements.secondaryActions={};
window.AI3DMeasureFocus.clear=()=>{};
cad.onload();project.onload();storage.onload();guided.onload();measure.onload();
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectOpenGuard,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().storageRecovery,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().guidedUI,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().measureFocus,"ready");
console.log("runtime CAD, project safety, storage recovery, guided UI and measure focus regression: ok");
