"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const runtime=fs.readFileSync(path.join(root,"runtime_health_guard.js"),"utf8");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.match(index,/cad_apply_guard\.js\?v=1\.4/,"index must load current CAD apply guard version");
assert.match(index,/project_open_guard\.js\?v=1\.3/,"index must load current project open guard version");
assert.match(index,/runtime_health_guard\.js\?v=1\.17/,"index must invalidate runtime health cache after safety guard recovery changes");
assert.match(runtime,/\["cadApplyGuard",\(\)=>!cadApplyGuardReady\(\),"cad_apply_guard\.js\?v=1\.4"\]/,"runtime fallback must pin current CAD apply guard version");
assert.match(runtime,/\["projectOpenGuard",\(\)=>!projectOpenGuardReady\(\),"project_open_guard\.js\?v=1\.3"\]/,"runtime fallback must pin current project open guard version");
const appended=[];
const warning={hidden:true,textContent:""};
const elements={projectPrintInfo:{after(){}},runtimeHealthWarning:warning};
const document={readyState:"complete",hidden:false,getElementById:id=>elements[id]||null,querySelector:()=>null,createElement:tag=>tag==="script"?{dataset:{},async:false,onload:null,onerror:null,src:""}:{id:"",className:"",hidden:false,textContent:""},head:{appendChild(){}},body:{appendChild:s=>appended.push(s)},addEventListener(){}};
const window={AI3D:{setPart(){}},addEventListener(){}};
const context={window,document,setTimeout:fn=>{context._timer=fn;return 1},clearTimeout(){},Date};
vm.createContext(context);vm.runInContext(runtime,context,{filename:"runtime_health_guard.js"});
assert.ok(window.AI3DRuntimeHealth.missing().includes("CAD-sovellussuoja"),"missing CAD apply guard must be visible in health status");
assert.ok(window.AI3DRuntimeHealth.missing().includes("projektin avaussuoja"),"missing project open guard must be visible in health status");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"missing");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectOpenGuard,"missing");
window.AI3DRuntimeHealth.retryDependencies();
const cad=appended.find(s=>s.dataset.ai3dCadFallback==="cadApplyGuard");
const project=appended.find(s=>s.dataset.ai3dCadFallback==="projectOpenGuard");
assert.ok(cad,"manual dependency retry must append CAD apply guard recovery script");
assert.ok(project,"manual dependency retry must append project open guard recovery script");
assert.match(cad.src,/^cad_apply_guard\.js\?v=1\.4&healthRetry=\d+$/);
assert.match(project.src,/^project_open_guard\.js\?v=1\.3&healthRetry=\d+$/);
window.AI3DCADApplyGuard={check(){},wrapV2(){}};
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"missing","partial CAD guard API must not be accepted");
window.AI3DCADApplyGuard.validatePlanHoleBounds=()=>true;
window.AI3D.__applyGuard=true;
window.AI3DProjectOpenGuard={check(){}};
cad.onload();project.onload();
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().cadApplyGuard,"ready");
assert.strictEqual(window.AI3DRuntimeHealth.dependencyState().projectOpenGuard,"ready");
console.log("runtime CAD and project safety guard recovery regression: ok");
